### ISSUE TITLE
Assertion failure in Legion Tracing

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#1004]
I encountered the following assertion failure when enabling tracing for multi-node runs. This is using the most recent control_replication branch. Running the same program on a single node works fine.

```
/ccs/home/zhihao/FlexFlow/legion/runtime/legion/legion_trace.cc:5856: virtual void Legion::Internal::PhysicalTemplate::record_complete_replay(Legion::Internal::Memoizable*, Legion::Internal::ApEvent): Assertion `is_recording()' failed.
```
A backtrace:
```
#0  0x000020002014f648 in nanosleep () from /lib64/libc.so.6
#1  0x000020002014f37c in sleep () from /lib64/libc.so.6
#2  0x000000001365e778 in Realm::realm_freeze (signal=6) at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/runtime_impl.cc:166
#3  <signal handler called>
#4  0x00002000200afbf0 in raise () from /lib64/libc.so.6
#5  0x00002000200b1f6c in abort () from /lib64/libc.so.6
#6  0x00002000200a56d4 in __assert_fail_base () from /lib64/libc.so.6
#7  0x00002000200a57c4 in __assert_fail () from /lib64/libc.so.6
#8  0x0000000011be8614 in Legion::Internal::PhysicalTemplate::record_complete_replay (this=0x2000602e5120, memo=0x200074626158, rhs=...)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/legion_trace.cc:5856
#9  0x0000000011f10b4c in Legion::Internal::ReplFenceOp::trigger_mapping (this=0x200074625ed0)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/legion_replication.cc:5406
#10 0x000000001214511c in Legion::Internal::Runtime::legion_runtime_task (args=0x2000581d8060, arglen=12, userdata=0x44ca67a0, userlen=8, p=...)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/runtime.cc:28578
#11 0x0000000013da138c in Realm::LocalTaskProcessor::execute_task (this=0x44c3e9e0, func_id=4, task_args=...)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/proc_impl.cc:1124
#12 0x0000000014c79d40 in Realm::Task::execute_on_processor (this=0x2000581d7ee0, p=...) at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/tasks.cc:307
#13 0x0000000014c80148 in Realm::UserThreadTaskScheduler::execute_task (this=0x44c3ecb0, task=0x2000581d7ee0)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/tasks.cc:1646
#14 0x0000000014c7d950 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x44c3ecb0) at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/tasks.cc:1127
#15 0x0000000014c89184 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x44c3ecb0)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/threads.inl:97
#16 0x0000000013b0ab4c in Realm::UserThread::uthread_entry () at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/threads.cc:1335
#17 0x00002000200c37fc in makecontext () from /lib64/libc.so.6
#18 0x0000000000000000 in ?? ()
```

**Comment by lightsighter** [comment]
Can you get me frozen processes on sapling?
