### ISSUE TITLE
Failure in process_post_end_tasks: Assertion `num_ready > 0' failed.

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#1005]
Encountered the following failure when running Legion w/ DEBUG mode on multiple nodes. The failure is nondeterministic.

```
/ccs/home/zhihao/FlexFlow/legion/runtime/legion/legion_context.cc:7104: bool Legion::Internal::InnerContext::process_post_end_tasks(): Assertion `num_ready > 0' failed.
#0  0x000020002014f648 in nanosleep () from /lib64/libc.so.6
#1  0x000020002014f37c in sleep () from /lib64/libc.so.6
#2  0x000000001365e778 in Realm::realm_freeze (signal=6) at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/runtime_impl.cc:166
#3  <signal handler called>
#4  0x00002000200afbf0 in raise () from /lib64/libc.so.6
#5  0x00002000200b1f6c in abort () from /lib64/libc.so.6
#6  0x00002000200a56d4 in __assert_fail_base () from /lib64/libc.so.6
#7  0x00002000200a57c4 in __assert_fail () from /lib64/libc.so.6
#8  0x0000000011abfa9c in Legion::Internal::InnerContext::process_post_end_tasks (this=0x200070201270)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/legion_context.cc:7104
#9  0x0000000011acdfc0 in Legion::Internal::InnerContext::handle_post_end_task (args=0x20005023f360)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/legion_context.cc:9919
#10 0x0000000012144e7c in Legion::Internal::Runtime::legion_runtime_task (args=0x20005023f360, arglen=12, userdata=0x25b95d30, userlen=8, p=...)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/runtime.cc:28493
#11 0x0000000013da138c in Realm::LocalTaskProcessor::execute_task (this=0x25b2db80, func_id=4, task_args=...)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/proc_impl.cc:1124
#12 0x0000000014c79d40 in Realm::Task::execute_on_processor (this=0x20005023f1e0, p=...) at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/tasks.cc:307
#13 0x0000000014c80148 in Realm::UserThreadTaskScheduler::execute_task (this=0x25b2de50, task=0x20005023f1e0)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/tasks.cc:1646
#14 0x0000000014c7d950 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x25b2de50) at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/tasks.cc:1127
#15 0x0000000014c89184 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x25b2de50)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/threads.inl:97
#16 0x0000000013b0ab4c in Realm::UserThread::uthread_entry () at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/threads.cc:1335
#17 0x00002000200c37fc in makecontext () from /lib64/libc.so.6
#18 0x0000000000000000 in ?? ()
```

**Comment by lightsighter** [comment]
Same thing here. Get me frozen processes on sapling.

**Comment by lightsighter** [comment]
Although @streichler too for visibility since this suggests a possible bug with Realm completion queue semantics. It returned no ready events despite triggering the event saying that the completion queue had some non-empty events.

**Comment by lightsighter** [comment]
Have you reproduced this after we fixed #1004?

**Comment by jiazhihao** [comment]
Haven't seen this after the fix. Close it for now.

**Comment by lightsighter** [comment]
Ok, please reopen if it recurs.
