### ISSUE TITLE
Spy: Assertion failure during dataflow graph simplification

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1012]
Running Legion spy on the attached files produces the following failure:

[legate_0.txt](https://github.com/StanfordLegion/legion/files/5935671/legate_0.txt)
[legate_1.txt](https://github.com/StanfordLegion/legion/files/5935674/legate_1.txt)

```
$ ~/legion/tools/legion_spy.py -d *.txt
Reading log file legate_0.txt...
WARNING: Skipped 7 lines when reading legate_0.txt
Reading log file legate_1.txt...
WARNING: Skipped 7 lines when reading legate_1.txt
Reading log file out.txt...
WARNING: file out.txt contained no valid lines!
WARNING: Skipped 4285 lines when reading out.txt
Reducing top-level index space shapes...
 |||||||||||||||||||||||||||||||||||||||||||||||||||| 100.0%
Done
Computing refinement points...
Dim 2: |||||||||||||||||||||||||||||||||||||||||||||||||||| 100.0%
Dim 1: |||||||||||||||||||||||||||||||||||||||||||||||||||| 100.0%
Done
INFO: No logical dependence data was found so we are running logical analysis to show the dataflow graphs that the runtime should compute. These are not the actual dataflow graphs computed.
Performing logical analysis...
Performing logical dependence analysis for legion_python_main (Shard 0)...
Pass
Performing logical dependence analysis for legion_python_main (Shard 1)...
Pass
Making dataflow graphs...
Simplifying dataflow graph for legion_python_main (Shard 0)...
Traceback (most recent call last):|||||||-----------| 79.1%
  File "/Users/mpapadakis/legion/tools/legion_spy.py", line 13509, in <module>
    main(temp_dir)
  File "/Users/mpapadakis/legion/tools/legion_spy.py", line 13481, in main
    state.make_dataflow_graphs(temp_dir, simplify_graphs, zoom_graphs)
  File "/Users/mpapadakis/legion/tools/legion_spy.py", line 12696, in make_dataflow_graphs
    total_dataflow_graphs += task.print_dataflow_graph(path, simplify_graphs, zoom_graphs)
  File "/Users/mpapadakis/legion/tools/legion_spy.py", line 8644, in print_dataflow_graph
    assert dst not in all_ops
AssertionError
```

**Comment by lightsighter** [comment]
I will look at it. Control replication? Did the application run to completion or did it die in the middle?

**Comment by manopapad** [comment]
This was the legate.numpy stencil example running with control replication. The application ran to completion.

No rush on this one, I figured out what I needed without the spy plot, just posting a small reproducer here for tracking.

**Comment by lightsighter** [comment]
Can you also capture the same logs but with detailed Legion Spy logging? I'm pretty sure this is just an emulation bug, but I want to see the difference between the two kinds of logs.

**Comment by lightsighter** [comment]
Should be fixed now. Pull either master or control replication and try again.

**Comment by manopapad** [comment]
Bug is fixed. Sorry I couldn't get you the detailed spy log in time (let me know if you still want it).
