### ISSUE TITLE
LLVM Patch Error

### ISSUE THREAD

**Issue by qyz96** [StanfordLegion/legion#1022]
Hi! I am installing Legion with GPU configuration with the following command on Slurm:
```
# Module loads
ml gnu7/7.3.0 pmix/2.2.2 intel/python/2019-3.6.8 cuda/10.2 openmpi3/3.1.0
# Build config
export CONDUIT=ibv
export CC=gcc
export CXX=g++
# Path setup
export LEGION_DIR=~/codes/legion
export HDF_ROOT="$LEGION_DIR"/language/hdf/install
export HTR_DIR=~/codes/HTR-solver
# CUDA config
export CUDA_HOME=/usr/local/cuda-10.2
export CUDA="$CUDA_HOME"
export GPU_ARCH=kepler
# Legion setup
export USE_CUDA=1
export USE_OPENMP=1
export USE_GASNET=1
export USE_HDF=1
export MAX_DIM=3

mkdir -p ~/codes && cd ~/codes
git clone -b control_replication https://gitlab.com/StanfordLegion/legion.git "$LEGION_DIR"
git clone https://github.com/stanfordhpccenter/HTR-solver.git "$HTR_DIR"

cd $LEGION_DIR/language
srun -p gpu scripts/setup_env.py --llvm-version 38 --terra-url 'https://github.com/StanfordLegion/terra.git' --terra-branch 'luajit2.1'
```
However, I am encountering the following error:
```
make[3]: Leaving directory `/home/darve/adncat/codes/legion/language/gasnet/release'
make[2]: Leaving directory `/home/darve/adncat/codes/legion/language/gasnet/release'
make[1]: Leaving directory `/home/darve/adncat/codes/legion/language/gasnet/release'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.7M  100 15.7M    0     0  11.3M      0  0:00:01  0:00:01 --:--:-- 11.3M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9380k  100 9380k    0     0  13.1M      0 --:--:-- --:--:-- --:--:-- 13.1M
Traceback (most recent call last):
  File "scripts/setup_env.py", line 456, in driver
    install_llvm(llvm_dir, llvm_install_dir, scratch_dir, llvm_version, llvm_use_cmake, cmake_exe, thread_count, cache, is_cray, insecure)
  File "scripts/setup_env.py", line 274, in install_llvm
    apply_patch(llvm_source_dir, os.path.join(os.path.dirname(os.path.realpath(__file__)), 'llvm-3.8-gcc.patch'))
  File "scripts/setup_env.py", line 88, in apply_patch
    subprocess.check_call(['patch', '-p%d' % strip_levels, '-i', diff_path], cwd=dest_dir)
  File "/opt/ohpc/pub/compiler/intel-19/intelpython3/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/ohpc/pub/compiler/intel-19/intelpython3/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/ohpc/pub/compiler/intel-19/intelpython3/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/opt/ohpc/pub/compiler/intel-19/intelpython3/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'patch': 'patch'
```
I am not sure what to do at this point, any help would be appreciated. Thanks!

**Comment by streichler** [comment]
Looks like you somehow don't have `patch` in your path?  What does
```
which patch
```
say on that system?

**Comment by qyz96** [comment]
Yes it is not in my path. Is this a package that I should install myself on Slurm?

**Comment by streichler** [comment]
`patch` is a standard tool that usually lives in /usr/bin.  What kind of system are you running on?

**Comment by qyz96** [comment]
Here are the system info:
`Linux yellowstone-login-0-2 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
It looks like there is no patch in usr/bin, 
```
[adncat@yellowstone-login-0-2 bin]$ which patch
/usr/bin/which: no patch in (/opt/ohpc/pub/compiler/gcc/7.3.0/bin:/opt/ohpc/pub/compiler/intel-18/compilers_and_libraries_2018.2.199/linux/bin/intel64:/opt/ohpc/pub/compiler/intel-18/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/darve/adncat/.local/bin:/home/darve/adncat/bin:/home/darve/adncat/julia-1.5.0/bin)
```
I will ask the system manager about this issue then. Thanks!

**Comment by jordanhubbard** [comment]
Can this be closed?

**Comment by qyz96** [comment]
Yes, I am closing this issue. Thank you.
