### ISSUE TITLE
Segmentation Fault in Multi-node run

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#1065]
I can deterministically reproduce the following segmentation fault when running Legion with control replication on 4 nodes. Executions on 1 or 2 nodes work fine.

```
(gdb) bt
#0  0x0000200029f1f648 in nanosleep () from /lib64/libc.so.6
#1  0x0000200029f1f37c in sleep () from /lib64/libc.so.6
#2  0x0000000012956f48 in Realm::realm_freeze (signal=11) at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/realm/runtime_impl.cc:177
#3  <signal handler called>
#4  0x0000000011683688 in Legion::Internal::Collectable::remove_reference (this=0x84, cnt=1)
    at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/legion/garbage_collection.h:560
#5  0x0000000011667698 in Legion::PhysicalRegion::operator= (this=0x200084354a18, rhs=...) at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/legion/legion.cc:2568
#6  0x000000001141f3f4 in Tensor::operator= (this=0x200084354998, rhs=...) at /ccs/home/zhihao/FlexFlow/src/runtime/model.cc:57
#7  0x0000000011400b7c in interact_features (model=0x2000841f3770, x=..., ly=..., interaction=...) at dlrm.cc:59
#8  0x00000000114013d8 in top_level_task (task=0x200078402430, regions=..., ctx=0x200074272b40, runtime=0x5a8ba530) at dlrm.cc:123
#9  0x000000001152ea14 in Legion::LegionTaskWrapper::legion_task_wrapper<&(top_level_task(Legion::Task const*, std::vector<Legion::PhysicalRegion, std::allocator<Legion::PhysicalRegion> > const&, Legion::Internal::TaskContext*, Legion::Runtime*))> (args=0x200074565720, arglen=8, userdata=0x0, userlen=0, p=...)
    at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/legion/legion.inl:20956
#10 0x0000000012df1650 in Realm::LocalTaskProcessor::execute_task (this=0x5a88af00, func_id=11, task_args=...)
    at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/realm/proc_impl.cc:1133
#11 0x0000000013cf5e68 in Realm::Task::execute_on_processor (this=0x2000745655a0, p=...) at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/realm/tasks.cc:307
#12 0x0000000013cfc270 in Realm::UserThreadTaskScheduler::execute_task (this=0x5a88b220, task=0x2000745655a0)
    at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/realm/tasks.cc:1646
#13 0x0000000013cf9a78 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x5a88b220) at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/realm/tasks.cc:1127
#14 0x0000000013d05174 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x5a88b220)
    at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/realm/threads.inl:97
#15 0x0000000012b5df20 in Realm::UserThread::uthread_entry () at /ccs/home/zhihao/FlexFlow/deps/legion/runtime/realm/threads.cc:1335
#16 0x0000200029e937fc in makecontext () from /lib64/libc.so.6
#17 0x0000000000000000 in ?? ()
```

**Comment by jiazhihao** [comment]
This turns out to be an application bug.
