### ISSUE TITLE
gasnetex: invalid attempt to perform a gather from gpu device memory

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#1122]
I have a program that fails on two nodes with this stack trace:

```
(gdb) bt
#0  0x000020000612eb88 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x000020000612e8bc in __sleep (seconds=0) at ../sysdeps/unix/sysv/linux/sleep.c:137
#2  0x000000001287c5c8 in Realm::realm_freeze (signal=11) at /g/g15/yadav2/taco/legion/legion/runtime/realm/runtime_impl.cc:177
#3  <signal handler called>
#4  __memcpy_power7 () at ../sysdeps/powerpc/powerpc64/power7/memcpy.S:90
#5  0x00002000060f35a8 in __GI_memmove (dest=0x20009cf90000, src=<optimized out>, len=<optimized out>) at ../sysdeps/powerpc/memmove.c:50
#6  0x00000000130c4210 in std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<Realm::dummy_32b_t> (__first=0x20290727e6c0, __last=0x20290727f580, __result=0x20009cf90000)
    at /usr/tce/packages/gcc/gcc-4.9.3/gnu/include/c++/4.9.3/bits/stl_algobase.h:378
#7  0x00000000130c1dd8 in std::__copy_move_a<false, Realm::dummy_32b_t const*, Realm::dummy_32b_t*> (__first=0x20290727e6c0, __last=0x20290727f580, __result=0x20009cf90000)
    at /usr/tce/packages/gcc/gcc-4.9.3/gnu/include/c++/4.9.3/bits/stl_algobase.h:396
#8  0x00000000130be488 in std::__copy_move_a2<false, Realm::dummy_32b_t const*, Realm::dummy_32b_t*> (__first=0x20290727e6c0, __last=0x20290727f580, __result=0x20009cf90000)
    at /usr/tce/packages/gcc/gcc-4.9.3/gnu/include/c++/4.9.3/bits/stl_algobase.h:434
#9  0x00000000130ba47c in std::copy<Realm::dummy_32b_t const*, Realm::dummy_32b_t*> (__first=0x20290727e6c0, __last=0x20290727f580, __result=0x20009cf90000)
    at /usr/tce/packages/gcc/gcc-4.9.3/gnu/include/c++/4.9.3/bits/stl_algobase.h:466
#10 0x00000000130b19b0 in Realm::memcpy_2d_typed<Realm::dummy_32b_t> (dst_base=35187005652992, dst_lstride=3776, src_base=35360585803456, src_lstride=15104, bytes=3776, lines=4)
    at /g/g15/yadav2/taco/legion/legion/runtime/realm/transfer/channel.cc:57
#11 0x000000001309ac28 in Realm::memcpy_2d (dst_base=35187005652992, dst_lstride=3776, src_base=35360585803456, src_lstride=15104, bytes=3776, lines=4)
    at /g/g15/yadav2/taco/legion/legion/runtime/realm/transfer/channel.cc:150
#12 0x00000000130a8e38 in Realm::RemoteWriteXferDes::progress_xd (this=0x2034a867abb0, channel=0x1a0e94d0, work_until=...) at /g/g15/yadav2/taco/legion/legion/runtime/realm/transfer/channel.cc:3751
#13 0x00000000130c9e78 in Realm::XDQueue<Realm::RemoteWriteChannel, Realm::RemoteWriteXferDes>::do_work (this=0x1a0e9508, work_until=...) at /g/g15/yadav2/taco/legion/legion/runtime/realm/transfer/channel.inl:161
#14 0x00000000127041b8 in Realm::BackgroundWorkManager::Worker::do_work (this=0x20002a87e930, max_time_in_ns=-1, interrupt_flag=0x0) at /g/g15/yadav2/taco/legion/legion/runtime/realm/bgwork.cc:611
#15 0x0000000012701460 in Realm::BackgroundWorkThread::main_loop (this=0x16aa3770) at /g/g15/yadav2/taco/legion/legion/runtime/realm/bgwork.cc:158
#16 0x0000000012706624 in Realm::Thread::thread_entry_wrapper<Realm::BackgroundWorkThread, &Realm::BackgroundWorkThread::main_loop> (obj=0x16aa3770) at /g/g15/yadav2/taco/legion/legion/runtime/realm/threads.inl:97
#17 0x000000001290bb00 in Realm::KernelThread::pthread_entry (data=0x16aa7ef0) at /g/g15/yadav2/taco/legion/legion/runtime/realm/threads.cc:774
#18 0x00002000000f8cd4 in start_thread (arg=0x20002a87f8b0) at pthread_create.c:309
#19 0x0000200006177e14 in clone () at ../sysdeps/unix/sysv/linux/powerpc/powerpc64/clone.S:104
```

Talking to @streichler on slack, he asked for the following information from GDB:
```
(gdb) f 12
(gdb) p *this
$1 = {<Realm::XferDes> = {_vptr.XferDes = 0x13e4f430 <vtable for Realm::RemoteWriteXferDes+16>, dma_op = 35410557294304, xferDes_queue = 0x13e9ec30 <Realm::XferDesQueue::get_singleton()::xferDes_queue>,
    launch_node = 0, iteration_completed = {value = {<std::atomic_bool> = {_M_base = {_M_i = false}}, <No data fields>}}, transfer_completed = {value = {<std::atomic_bool> = {_M_base = {
            _M_i = false}}, <No data fields>}}, current_in_port_mask = 9223512774455328808, current_out_port_mask = 333942808, current_in_port_remain = 0, current_out_port_remain = 334913280,
    input_ports = std::vector of length 1, capacity 1 = {{mem = 0x1a07c8d0, iter = 0x2034dc002d90, serdez_op = 0x0, peer_guid = 0, peer_port_idx = 0, indirect_port_idx = -1, is_indirect_port = false,
        needs_pbt_update = {value = {<std::atomic_bool> = {_M_base = {_M_i = false}}, <No data fields>}}, local_bytes_total = 0, local_bytes_cons = {value = {<std::__atomic_base<unsigned long>> = {
              _M_i = 0}, <No data fields>}}, remote_bytes_total = {value = {<std::__atomic_base<unsigned long>> = {_M_i = 18446744073709551615}, <No data fields>}}, seq_local = {contig_amount_x2 = {
            value = {<std::__atomic_base<unsigned long>> = {_M_i = 0}, <No data fields>}}, first_noncontig = {value = {<std::__atomic_base<unsigned long>> = {_M_i = 18446744073709551615}, <No data fields>}},
          mutex = 0x2034dc002d30, spans = std::map with 0 elements}, seq_remote = {contig_amount_x2 = {value = {<std::__atomic_base<unsigned long>> = {_M_i = 0}, <No data fields>}}, first_noncontig = {
            value = {<std::__atomic_base<unsigned long>> = {_M_i = 18446744073709551615}, <No data fields>}}, mutex = 0x2034dc002280, spans = std::map with 0 elements}, ib_mem = {id = 0, static NO_MEMORY = {id = 0,
            static NO_MEMORY = <same as static member of an already seen type>}}, ib_offset = 0, ib_size = 0, addrlist = {total_bytes = 3564544, write_pointer = 4, read_pointer = 0, static MAX_ENTRIES = 1000, data = {
            60418, 14601308160, 944, 15104, 0 <repeats 996 times>}}, addrcursor = {addrlist = 0x2034dc0035f0, partial = false, static MAX_DIM = 8, partial_dim = 0, pos = {0, 0, 0, 0, 0, 0, 0, 0}}}},
    output_ports = std::vector of length 1, capacity 1 = {{mem = 0x2034a0002520, iter = 0x2034dc002560, serdez_op = 0x0, peer_guid = 0, peer_port_idx = 0, indirect_port_idx = -1, is_indirect_port = false,
        needs_pbt_update = {value = {<std::atomic_bool> = {_M_base = {_M_i = false}}, <No data fields>}}, local_bytes_total = 0, local_bytes_cons = {value = {<std::__atomic_base<unsigned long>> = {
              _M_i = 0}, <No data fields>}}, remote_bytes_total = {value = {<std::__atomic_base<unsigned long>> = {_M_i = 18446744073709551615}, <No data fields>}}, seq_local = {contig_amount_x2 = {
            value = {<std::__atomic_base<unsigned long>> = {_M_i = 0}, <No data fields>}}, first_noncontig = {value = {<std::__atomic_base<unsigned long>> = {_M_i = 18446744073709551615}, <No data fields>}},
          mutex = 0x2034dc002b50, spans = std::map with 0 elements}, seq_remote = {contig_amount_x2 = {value = {<std::__atomic_base<unsigned long>> = {_M_i = 0}, <No data fields>}}, first_noncontig = {
            value = {<std::__atomic_base<unsigned long>> = {_M_i = 18446744073709551615}, <No data fields>}}, mutex = 0x2034dc0027b0, spans = std::map with 0 elements}, ib_mem = {id = 0, static NO_MEMORY = {id = 0,
            static NO_MEMORY = <same as static member of an already seen type>}}, ib_offset = 0, ib_size = 0, addrlist = {total_bytes = 3564544, write_pointer = 2, read_pointer = 0, static MAX_ENTRIES = 1000, data = {
            57032705, 14647647232, 0 <repeats 998 times>}}, addrcursor = {addrlist = 0x2034dc005690, partial = false, static MAX_DIM = 8, partial_dim = 0, pos = {0, 0, 0, 0, 0, 0, 0, 0}}}}, input_control = {decoder = {
        temp_count = 0, port_shift = 0}, control_port_idx = -1, current_io_port = 0, remaining_count = 18446744073709551615, eos_received = false}, output_control = {decoder = {temp_count = 0, port_shift = 0},
      control_port_idx = -1, current_io_port = 0, remaining_count = 18446744073709551615, eos_received = false}, max_req_size = 16777216, priority = 0, guid = 46, kind = Realm::XFER_REMOTE_WRITE, channel = 0x16b92020,
    fill_data = 0x2034dc003120, fill_size = 0, orig_fill_size = 0, static ALIGNED_FILL_STORAGE_SIZE = 32, inline_fill_storage = {
      data = '\000' <repeats 12 times>, "d", '\000' <repeats 11 times>, "\241\005\000\000\000\000\000"}, xd_lock = {{placeholder = {0, 0, 0, 0, 0, 4503646872010754, 0, 4}}}, update_read_lock = {{placeholder = {0, 0, 0,
          0, 0, 8589935362, 0, 0}}}, update_write_lock = {{placeholder = {0, 0, 0, 0, 0, 60129542221, 8589935362, 0}}}, progress_counter = {value = {<std::__atomic_base<unsigned int>> = {_M_i = 0}, <No data fields>}},
    reference_count = {value = {<std::__atomic_base<unsigned int>> = {_M_i = 1}, <No data fields>}}, xd_link = {next_within_pri = 0x0, lastlink_within_pri = 0x2034dc003208, next_lower_pri = 0x0}, available_req_mutex = {
      {placeholder = {0, 0, 0, 0, 0, 0, 1, 4294967296}}}, available_reqs = std::queue wrapping: std::deque with 0 elements, deferred_enqueue = {<Realm::EventWaiter> = {
        _vptr.EventWaiter = 0x13e4f098 <vtable for Realm::XferDes::DeferredXDEnqueue+16>, ew_list_link = {next = 0x0}}, xferDes_queue = 0x200000202, xd = 0x0}}, requests = 0x0}
(gdb) p/x input_ports[0].mem->me
$2 = {id = 0x1e00000000000001, static NO_MEMORY = {id = 0x0, static NO_MEMORY = <same as static member of an already seen type>}}
(gdb) p/x output_ports[0].mem->me
$3 = {id = 0x1e00010000000002, static NO_MEMORY = {id = 0x0, static NO_MEMORY = <same as static member of an already seen type>}}
```

The problem goes away when `-gex:bindcuda 0` is passed to the program.

**Comment by rohany** [comment]
I think that this is also fixed for me.
