### ISSUE TITLE
Double-free error when inline-mapping 9d array

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1171]
The following cunumeric program causes a double-free error in Realm:

```
import cunumeric as num
print(num.ones(9 * (4,)))
```

This program tries to create a 9-dimensional `4x4x...x4` array and inline-map it. The crash does not happen for an 8-dimensional array, or for a `3x3x…x3` 9-dimensional array.

Looking through gdb, it looks like Realm tries to delete the same `GPUXferDes` object twice. The same object appears under two different `xd_id`’s (10 and 11):

```
#6  0x00007fffebfa2fa8 in Realm::TransferOperation::notify_xd_completion (this=0x7fff700128d0, xd_id=10) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/transfer/transfer.cc:4734
#7  0x00007fffec2baf39 in Realm::XferDes::mark_completed (this=0x7fff70012e30) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/transfer/channel.cc:1265
```

```
#6  0x00007fffebfa2fa8 in Realm::TransferOperation::notify_xd_completion (this=0x7fff80004880, xd_id=11) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/transfer/transfer.cc:4734
#7  0x00007fffec2baf39 in Realm::XferDes::mark_completed (this=0x7fff70012e30) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/transfer/channel.cc:1265
```

Here is how the program is being invoked:

```
mpirun -n 1 --npernode 1 --bind-to none --mca mpi_warn_on_fork 0 -x LD_LIBRARY_PATH -x UCX_TLS -x LEGATE_DIR -x UCX_MEMTYPE_CACHE -x REALM_VERSION -x PYTHONDONTWRITEBYTECODE -x PYTHONPATH -x NCCL_LAUNCH_MODE -x LEGATE_NEED_CUDA -x LEGATE_NEED_OPENMP -x LEGATE_MAX_DIM -x LEGATE_MAX_FIELDS -x REALM_BACKTRACE /gpfs/fs1/mpapadakis/legate.core/install/bin/legion_python -ll:py 1 -lg:local 0 -ll:gpu 1 -cuda:skipbusy -ll:ocpu 2 -ll:othr 18 -ll:onuma 1 -ll:util 2 -ll:csize 256 -ll:nsize 200000 -ll:fsize 14500 -ll:zsize 32 -level openmp=5,gpu=5 -lg:eager_alloc_percentage 50 a.py -cunumeric:test -logfile /gpfs/fs1/mpapadakis/2022/01/11/165547/%.log
```

Running with `-level dma=2,xplan=1` I see:

```
[0 - 7fa0ca0e8700]    2.433603 {2}{xplan}: created: plan=0x7fa09c012400 domain=IS:<0>..<7>,dense srcs=1 dsts=1
[0 - 7fa0ca0e8700]    2.433834 {1}{xplan}: created: plan=0x7fa09c012400 srcs[0]=field(0, inst=4000000000000002, size=1)
[0 - 7fa0ca0e8700]    2.433865 {1}{xplan}: created: plan=0x7fa09c012400 dsts[0]=field(0, inst=4000000000c00002, size=1)
[0 - 7fa0ca0e8700]    2.434249 {1}{xplan}: analysis: plan=0x7fa09c012400 dim_order=[0] xds=1 ibs=0
[0 - 7fa0ca0e8700]    2.434291 {1}{xplan}: analysis: plan=0x7fa09c012400 xds[0]: target=0 inputs=[inst(4000000000000002,0+1)] outputs=[inst(4000000000c00002,0+1)]
[0 - 7fa0ca0e8700]    2.434339 {2}{dma}: dma request 0x7fa09c0128d0 created - plan=0x7fa09c012400 before=0 after=8000000001300003
[0 - 7fa0ca0e8700]    2.434357 {2}{dma}: dma request 0x7fa09c0128d0 ready - plan=0x7fa09c012400 before=0 after=8000000001300003
[0 - 7fa0ca0e8700]    2.434368 {2}{dma}: dma request 0x7fa09c0128d0 started - plan=0x7fa09c012400 before=0 after=8000000001300003
[0 - 7fa0ce8f8700]    2.435802 {2}{dma}: dma request 0x7fa09c0128d0 completed - plan=0x7fa09c012400 before=0 after=8000000001300003
[0 - 7fa0ce8f8700]    2.435862 {2}{xplan}: destroyed: plan=0x7fa09c012400
[0 - 7fa0ca318700]    2.437470 {2}{xplan}: created: plan=0x7fa0ac001760 domain=IS:<0,0,0,0,0,0,0,0,0>..<3,3,3,3,3,3,3,3,3>,dense srcs=1 dsts=1
[0 - 7fa0ca318700]    2.437513 {1}{xplan}: created: plan=0x7fa0ac001760 srcs[0]=field(1048577, inst=4000000000c00001, size=8)
[0 - 7fa0ca318700]    2.437529 {1}{xplan}: created: plan=0x7fa0ac001760 dsts[0]=field(1048577, inst=4000000000000001, size=8)
[0 - 7fa0ca318700]    2.437759 {1}{xplan}: analysis: plan=0x7fa0ac001760 dim_order=[3, 4, 5, 6, 7, 8, 2, 0, 1] xds=2 ibs=1
[0 - 7fa0ca318700]    2.437790 {1}{xplan}: analysis: plan=0x7fa0ac001760 xds[0]: target=0 inputs=[inst(4000000000c00001,0+1)] outputs=[edge(0)]
[0 - 7fa0ca318700]    2.437805 {1}{xplan}: analysis: plan=0x7fa0ac001760 xds[1]: target=0 inputs=[edge(0)] outputs=[inst(4000000000000001,0+1)]
[0 - 7fa0ca318700]    2.437817 {1}{xplan}: analysis: plan=0x7fa0ac001760 ibs[0]: memory=1a00000000000000 size=2097152
[0 - 7fa0ca318700]    2.437828 {1}{xplan}: analysis: plan=0x7fa0ac001760 ib_alloc=[0]
[0 - 7fa0ca318700]    2.437858 {2}{dma}: dma request 0x7fa0ac001aa0 created - plan=0x7fa0ac001760 before=8000000001500007 after=8000000000d0000c
[0 - 7fa0ce8f8700]    2.982960 {2}{dma}: dma request 0x7fa0ac001aa0 ready - plan=0x7fa0ac001760 before=8000000001500007 after=8000000000d0000c
[0 - 7fa0ce8f8700]    2.983031 {2}{dma}: dma request 0x7fa0ac001aa0 started - plan=0x7fa0ac001760 before=8000000001500007 after=8000000000d0000c
```

**Comment by manopapad** [comment]
This has been fixed with ceec163db0bf52926cb714524c0773af9a6ae6ed
