### ISSUE TITLE
realm: incorrect usage of gex events in rma put path

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#1173]
This failure from a debug gasnet build:
```
[0] #6  0x00000000005405a1 in gasneti_error_abort () at /gpfs/fs1/wonchanl/gasnet/GASNet-2021.9.0/gasnet_tools.c:770                                                                                        
[0] #7  0x000000000054075c in _gasneti_fatalerror (msg=0x8cc04d "Invalid use of free eop") at /gpfs/fs1/wonchanl/gasnet/GASNet-2021.9.0/gasnet_tools.c:806                                                  
[0] #8  0x0000000000725064 in gasnete_op_try_free (event=0x7fb6ec075681) at /gpfs/fs1/wonchanl/gasnet/GASNet-2021.9.0/gasnet_event.c:375                                                                    
[0] #9  0x000000000072531c in gasnete_test (event=0x7fb6ec075681) at /gpfs/fs1/wonchanl/gasnet/GASNet-2021.9.0/gasnet_event.c:406                                                                           
[0] #10 0x00007fc07125bbf2 in _gex_Event_Test (_event=0x7fb6ec075681) at /gpfs/fs1/wonchanl/legate/gasnet_debug/include/ibv-conduit/gasnet_extended.h:138                                                   
[0] #11 0x00007fc07126aa92 in Realm::GASNetEXPoller::do_work (this=0x1c42360, work_until=...) at /gpfs/fs1/wonchanl/legate.core/legion/runtime/realm/gasnetex/gasnetex_internal.cc:2774 
```
is believed to be due to Realm treating the local and remote completion of the put as two independent gasnet events.  In reality, the local completion is a "leaf event" of the remote completion's "root event", and and a successful test of the remote completion invalidates the local completion event.  Need to fix this and scrub other paths that use gasnet events as well.

**Comment by streichler** [comment]
This was fixed with commit e600c7eb.
