### ISSUE TITLE
Legion spy error

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1179]
On `control_replication` commit `f7edcc514c7aaf848e7617f107692f113f0a2ead`, using `legion_spy.py` leads to this error
```
Reading log file log_0.log...
Traceback (most recent call last):
  File "/home/bandokihiro/Builds_GPUNodes/legion/tools/legion_spy.py", line 13613, in <module>
    main(temp_dir)
  File "/home/bandokihiro/Builds_GPUNodes/legion/tools/legion_spy.py", line 13488, in main
    total_matches += state.parse_log_file(file_name)
  File "/home/bandokihiro/Builds_GPUNodes/legion/tools/legion_spy.py", line 12121, in parse_log_file
    if parse_legion_spy_line(line, self):
  File "/home/bandokihiro/Builds_GPUNodes/legion/tools/legion_spy.py", line 11331, in parse_legion_spy_line
    op.set_launch_rect(Rect(lo, hi))
  File "/home/bandokihiro/Builds_GPUNodes/legion/tools/legion_spy.py", line 5890, in set_launch_rect
    assert not self.launch_rect
AssertionError
```
To reproduce, the log files are here:
- https://drive.google.com/file/d/14MkS8RGcKDTLV_stsYw41bZSVqaO1Uan/view?usp=sharing
- https://drive.google.com/file/d/1NJzUSZgZTHy3grOOCZtikWYW7W5HtDAT/view?usp=sharing

and the command used is
```
legion_spy.py -d log*
```

**Comment by lightsighter** [comment]
Pull and try again. The logging format didn't change so your logs are still good.

**Comment by bandokihiro** [comment]
Fixed. Thanks.
