### ISSUE TITLE
segfault in perform_dma  on dma branch

### ISSUE THREAD

**Issue by gshipman** [StanfordLegion/legion#118]
When running the legion version of pennant on a single node with the general runtime (Gasnet udp) I'm getting a segmentation fault: 

```
LegionRuntime::LowLevel::CopyRequest::perform_dma(this=0x00007fdfc846a780) + 1650 at lowlevel_dma.cc:3542
```

When the application starts up I get a warning (reservation cannot be satisfied): 

```
Pinned Memory Usage: GASNET=256, RMEM=0, LMB=2, SDP=64, total=322
[0 - 7fff7c222300] {4}{threads}: reservation ('EndpointManager workers') cannot be satisfied
********************
Running PENNANT v0.6
********************

Running Legion on 1 piece(s)
--- Mesh Information ---
Points:  61
Zones:  40
Sides:  158
Side chunks:  10
Point chunks:  4
Zone chunks:  3
Chunk size:  16
------------------------
Connection to localhost closed by remote host.
```

A backtrace of the offending thread reveals: 

```
* thread #4: tid = 0x35ad11, 0x0000000103e3aae2 pennant`LegionRuntime::LowLevel::CopyRequest::perform_dma(this=0x00007fdfc846a780) + 1650 at lowlevel_dma.cc:3542, stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x0000000103e3aae2 pennant`LegionRuntime::LowLevel::CopyRequest::perform_dma(this=0x00007fdfc846a780) + 1650 at lowlevel_dma.cc:3542
    frame #1: 0x0000000103e343ad pennant`LegionRuntime::LowLevel::CopyRequest::check_readiness(this=0x00007fdfc846a780, just_check=false, rq=0x0000000000000000) + 2637 at lowlevel_dma.cc:623
    frame #2: 0x0000000103e43735 pennant`Realm::Domain::copy(this=0x00007fdfc8455c0c, srcs=0x0000000125b1e0e0, dsts=0x0000000125b1e0c8, requests=0x0000000125b1dcf8, wait_on=(id = 0, gen = 0), redop_id=0, red_fold=false) const + 8421 at lowlevel_dma.cc:5265
    frame #3: 0x0000000103e415fa pennant`Realm::Domain::copy(this=0x00007fdfc8455c0c, srcs=0x0000000125b1e0e0, dsts=0x0000000125b1e0c8, wait_on=(id = 0, gen = 0), redop_id=0, red_fold=false) const + 122 at lowlevel_dma.cc:5126
    frame #4: 0x0000000103ac46f6 pennant`LegionRuntime::HighLevel::RegionTreeForest::issue_copy(this=0x00007fdfc8600220, dom=0x00007fdfc8455c0c, op=0x00007fdfc8852188, src_fields=0x0000000125b1e0e0, dst_fields=0x0000000125b1e0c8, precondition=(id = 0, gen = 0)) + 262 at region_tree.cc:3823
    frame #5: 0x0000000103b31148 pennant`LegionRuntime::HighLevel::RegionTreeNode::issue_grouped_copies(context=0x00007fdfc8600220, info=0x0000000125b205a0, dst=0x00007fdfc84691e0, preconditions=0x0000000125b1ee78, update_mask=0x0000000125b1ee00, copy_domains_precondition=(id = 0, gen = 0), copy_domains=0x0000000125b1ed98, src_instances=0x0000000125b1eeb8, src_version_info=0x00007fdfc98b2170, postconditions=0x0000000125b1edc0, tracker=0x0000000000000000) + 4728 at region_tree.cc:13234
    frame #6: 0x0000000103b1f504 pennant`LegionRuntime::HighLevel::RegionTreeNode::issue_update_copies(this=0x00007fdfc9858ea0, info=0x0000000125b205a0, dst=0x00007fdfc84691e0, copy_mask=<unavailable>, valid_instances=0x0000000125b20268, tracker=0x0000000000000000) + 7316 at region_tree.cc:12923
    frame #7: 0x0000000103abaef7 pennant`LegionRuntime::HighLevel::RegionNode::register_region(this=0x00007fdfc9858ea0, info=0x0000000125b205a0, term_event=(id = 536871037, gen = 9), usage=0x0000000125b20580, user_mask=0x0000000125b20640, view=0x00007fdfc84691e0, needed_fields=0x00007fdfc8468d40) + 871 at region_tree.cc:15083
    frame #8: 0x0000000103aba6da pennant`LegionRuntime::HighLevel::RegionTreeForest::register_physical_region(this=0x00007fdfc8600220, ctx=(ctx = 0), ref=0x00007fdfc8468d20, req=0x00007fdfc8852800, index=0, version_info=0x00007fdfc98b2170, op=0x00007fdfc8852188, local_proc=(id = 2147483649), term_event=(id = 536871037, gen = 9), log_name=0x00007fdfc8405320, uid=118) + 826 at region_tree.cc:1976
    frame #9: 0x000000010383cc93 pennant`LegionRuntime::HighLevel::SingleTask::map_all_regions(this=0x00007fdfc8852000, target=(id = 2147483649), user_event=(id = 536871037, gen = 9), mapper_invoked=false) + 11091 at legion_tasks.cc:4580
    frame #10: 0x0000000103858688 pennant`LegionRuntime::HighLevel::PointTask::perform_mapping(this=0x00007fdfc8852000, mapper_invoked=false) + 120 at legion_tasks.cc:7590
    frame #11: 0x000000010386cd3c pennant`LegionRuntime::HighLevel::SliceTask::map_and_launch(this=0x00007fdfca826c00) + 1452 at legion_tasks.cc:10338
    frame #12: 0x000000010384be98 pennant`LegionRuntime::HighLevel::MultiTask::trigger_execution(this=0x00007fdfca826c00) + 632 at legion_tasks.cc:5992
    frame #13: 0x0000000103870d9b pennant`LegionRuntime::HighLevel::DeferredSlicer::perform_slice(this=0x000000012521d890, slice=0x00007fdfca826c00) + 75 at legion_tasks.cc:11087
    frame #14: 0x0000000103870f69 pennant`LegionRuntime::HighLevel::DeferredSlicer::handle_slice(args=0x00007fdfc8467c60) + 41 at legion_tasks.cc:11099
    frame #15: 0x0000000103c7b1d3 pennant`LegionRuntime::HighLevel::Internal::high_level_runtime_task(args=0x00007fdfc8467c60, arglen=20, userdata=0x0000000000000000, userlen=0, p=(id = 2147483648)) + 1347 at runtime.cc:16797
    frame #16: 0x0000000103f00adb pennant`Realm::LocalTaskProcessor::execute_task(this=0x00007fdfc8407ac0, func_id=4, task_args=0x00007fdfc8467eb0) + 1707 at proc_impl.cc:719
    frame #17: 0x0000000103ebd424 pennant`Realm::Task::execute_on_processor(this=0x00007fdfc8467df0, p=(id = 2147483648)) + 228 at tasks.cc:108
    frame #18: 0x0000000103ec2379 pennant`Realm::UserThreadTaskScheduler::execute_task(this=0x00007fdfc8407c00, task=0x00007fdfc8467df0) + 41 at tasks.cc:939
    frame #19: 0x0000000103ebf380 pennant`Realm::ThreadedTaskScheduler::scheduler_loop(this=0x00007fdfc8407c00) + 1840 at tasks.cc:492
    frame #20: 0x0000000103ec555e pennant`void Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &(obj=0x00007fdfc8407c00))>(void*) + 94 at threads.inl:127
    frame #21: 0x0000000103ea11e7 pennant`Realm::UserThread::uthread_entry() + 359 at threads.cc:747
    frame #22: 0x00007fff96c8e35b libsystem_platform.dylib`_ctx_start + 11
```

**Comment by jiazhihao** [comment]
The warning message indicates that the Legion runtime has allocated more threads than allowed; it is not suggested but shouldn't lead to segment fault. Are you running with the most up-to-date dma code? It seems a little bit weird to me that the dma thread crashed when doing logging. Is there any possibility for me to reproduce the failure case?

**Comment by gshipman** [comment]
I am running on eadf87d07a2f4fbdec6a1a410253cacb50ce52f4
I just tested this again and I get the same failure when running on a single node. 
You can reproduce by using the pennant-legion example located here: 
https://github.com/gshipman/pennant-legion

The latest failure is: 
```
pennant: /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:2951: void LegionRuntime::LowLevel::CopyRequest::perform_new_dma(LegionRuntime::LowLevel::Memory, LegionRuntime::LowLevel::Memory) [with unsigned int DIM = 0u; LegionRuntime::LowLevel::Memory = Realm::Memory]: Assertion `ispace->me == get_runtime()->get_instance_impl(dst_inst)->metadata.is' failed.
```

Here is the backtrace of the offending thread: 

```
[0] Thread 10 (Thread 0x7fe8e3c44700 (LWP 36742)):
[0] #0  0x00007fe8e1cc50a7 in sched_yield () from /usr/lib64/libc.so.6
[0] #1  0x000000000101a420 in gasneti_system_redirected_coprocess ()
[0] #2  0x000000000101acf5 in gasneti_print_backtrace ()
[0] #3  0x000000000108540d in gasneti_defaultSignalHandler ()
[0] #4  <signal handler called>
[0] #5  0x00007fe8e1c1f5f7 in raise () from /usr/lib64/libc.so.6
[0] #6  0x00007fe8e1c20ce8 in abort () from /usr/lib64/libc.so.6
[0] #7  0x00007fe8e1c18566 in __assert_fail_base () from /usr/lib64/libc.so.6
[0] #8  0x00007fe8e1c18612 in __assert_fail () from /usr/lib64/libc.so.6
[0] #9  0x0000000000f2cd3b in LegionRuntime::LowLevel::CopyRequest::perform_new_dma<0u> (this=0x7fe8a5454b10, src_mem=..., dst_mem=...) at /home/gshipman/local/src/legion/runtime/lowl
evel_dma.cc:2951
[0] #10 0x0000000000f1c82f in LegionRuntime::LowLevel::CopyRequest::perform_dma (this=0x7fe8a5454b10) at /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:3482
[0] #11 0x0000000000f19e77 in LegionRuntime::LowLevel::CopyRequest::check_readiness (this=0x7fe8a5454b10, just_check=false, rq=0x0) at /home/gshipman/local/src/legion/runtime/lowlevel
_dma.cc:613
[0] #12 0x0000000000f2127f in Realm::Domain::copy (this=0x7fe8a54163f0, srcs=std::vector of length 1, capacity 1 = {...}, dsts=std::vector of length 1, capacity 1 = {...}, requests=..
., wait_on=..., redop_id=0, red_fold=false) at /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:5206
[0] #13 0x0000000000f208b2 in Realm::Domain::copy (this=0x7fe8a54163f0, srcs=std::vector of length 1, capacity 1 = {...}, dsts=std::vector of length 1, capacity 1 = {...}, wait_on=...
, redop_id=0, red_fold=false) at /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:5067
[0] #14 0x0000000000d7eae0 in LegionRuntime::HighLevel::RegionTreeForest::issue_copy (this=0x2a61ab0, dom=..., op=0x7fe8dee88d00, src_fields=std::vector of length 1, capacity 1 = {...
}, dst_fields=std::vector of length 1, capacity 1 = {...}, precondition=...) at /home/gshipman/local/src/legion/runtime/legion/region_tree.cc:3862
[0] #15 0x0000000000da5cea in LegionRuntime::HighLevel::RegionTreeNode::issue_grouped_copies (context=0x2a61ab0, info=..., dst=0x7fe8a54512c0, preconditions=std::map with 0 elements, 
update_mask=..., copy_domains_precondition=..., copy_domains=std::set with 1 elements, src_instances=std::map with 1 elements, src_version_info=..., postconditions=std::map with 0 ele
ments, tracker=0x0) at /home/gshipman/local/src/legion/runtime/legion/region_tree.cc:13398
[0] #16 0x0000000000ce64ee in LegionRuntime::HighLevel::CompositeNode::issue_update_copies (this=0x7fe8a5648d60, info=..., dst=0x7fe8a54512c0, traversal_mask=..., copy_mask=..., preco
nds=std::map with 0 elements, postconditions=std::map with 0 elements, tracker=0x0) at /home/gshipman/local/src/legion/runtime/legion/legion_views.cc:4476
[0] #17 0x0000000000ce4318 in LegionRuntime::HighLevel::CompositeView::issue_deferred_copies (this=0x7fe8a5453f80, info=..., dst=0x7fe8a54512c0, copy_mask=..., tracker=0x0) at /home/g
shipman/local/src/legion/runtime/legion/legion_views.cc:3952
[0] #18 0x0000000000da455b in LegionRuntime::HighLevel::RegionTreeNode::issue_update_copies (this=0x2c115a0, info=..., dst=0x7fe8a54512c0, copy_mask=..., valid_instances=std::map with
 1 elements, tracker=0x0) at /home/gshipman/local/src/legion/runtime/legion/region_tree.cc:13124
[0] #19 0x0000000000dab873 in LegionRuntime::HighLevel::RegionNode::register_region (this=0x2c115a0, info=..., term_event=..., usage=..., user_mask=..., view=0x7fe8a54512c0, needed_fi
elds=...) at /home/gshipman/local/src/legion/runtime/legion/region_tree.cc:15203
[0] #20 0x0000000000d76cab in LegionRuntime::HighLevel::RegionTreeForest::register_physical_region (this=0x2a61ab0, ctx=..., ref=..., req=..., index=2, version_info=..., op=0x7fe8dee8
8d00, local_proc=..., term_event=..., log_name=0x2899a00 "calcedgelen", uid=274) at /home/gshipman/local/src/legion/runtime/legion/region_tree.cc:1986
[0] #21 0x0000000000c5bf57 in LegionRuntime::HighLevel::SingleTask::map_all_regions (this=0x7fe8dee88b60, target=..., user_event=..., mapper_invoked=false) at /home/gshipman/local/src
/legion/runtime/legion/legion_tasks.cc:4604
[0] #22 0x0000000000c66d97 in LegionRuntime::HighLevel::PointTask::perform_mapping (this=0x7fe8dee88b60, mapper_invoked=false) at /home/gshipman/local/src/legion/runtime/legion/legion
_tasks.cc:7495
[0] #23 0x0000000000c702b7 in LegionRuntime::HighLevel::SliceTask::map_and_launch (this=0x2c103d0) at /home/gshipman/local/src/legion/runtime/legion/legion_tasks.cc:10206
[0] #24 0x0000000000c61112 in LegionRuntime::HighLevel::MultiTask::trigger_execution (this=0x2c103d0) at /home/gshipman/local/src/legion/runtime/legion/legion_tasks.cc:5907
[0] #25 0x0000000000c72a4c in LegionRuntime::HighLevel::DeferredSlicer::perform_slice (this=0x7fe8a5be9190, slice=0x2c103d0) at /home/gshipman/local/src/legion/runtime/legion/legion_t
asks.cc:10918
[0] #26 0x0000000000c72aeb in LegionRuntime::HighLevel::DeferredSlicer::handle_slice (args=0x7fe8dee4c0a0) at /home/gshipman/local/src/legion/runtime/legion/legion_tasks.cc:10930
[0] #27 0x0000000000e3e7b8 in LegionRuntime::HighLevel::Internal::high_level_runtime_task (args=0x7fe8dee4c0a0, arglen=20, userdata=0x0, userlen=0, p=...) at /home/gshipman/local/src/
legion/runtime/legion/runtime.cc:17758
[0] #28 0x0000000000f93824 in Realm::LocalTaskProcessor::execute_task (this=0x2a45e00, func_id=4, task_args=...) at /home/gshipman/local/src/legion/runtime/realm/proc_impl.cc:795
[0] #29 0x0000000000f6b8fe in Realm::Task::execute_on_processor (this=0x7fe8a56ad230, p=...) at /home/gshipman/local/src/legion/runtime/realm/tasks.cc:108
[0] #30 0x0000000000f6e1a8 in Realm::UserThreadTaskScheduler::execute_task (this=0x2a46160, task=0x7fe8a56ad230) at /home/gshipman/local/src/legion/runtime/realm/tasks.cc:939
[0] #31 0x0000000000f6c874 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x2a46160) at /home/gshipman/local/src/legion/runtime/realm/tasks.cc:492
[0] #32 0x0000000000f7213c in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x2a46160) at /home/gshipman/local/
src/legion/runtime/realm/threads.inl:127
[0] #33 0x0000000000f56af1 in Realm::UserThread::uthread_entry () at /home/gshipman/local/src/legion/runtime/realm/threads.cc:747
[0] #34 0x00007fe8e1c31110 in ?? () from /usr/lib64/libc.so.6
[0] #35 0x0000000000000000 in ?? ()
```

**Comment by gshipman** [comment]
If I run on more than one node (change -n in run-darwin.sh), I get the following failure: 
```
pennant: /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:2885: void LegionRuntime::LowLevel::find_shortest_path(LegionRuntime::LowLevel::Memory, LegionRuntime::LowLevel::Memor
y, std::vector<Realm::Memory>&): Assertion `dist.find(dst_mem) != dist.end()' failed.
```
Here is the backtrace of the offending thread: 
```
0] Thread 11 (Thread 0x7fea9835b700 (LWP 36808)):
[0] #0  0x00007fead8c980a7 in sched_yield () from /usr/lib64/libc.so.6
[0] #1  0x000000000101a420 in gasneti_system_redirected_coprocess ()
[0] #2  0x000000000101acf5 in gasneti_print_backtrace ()
[0] #3  0x000000000108540d in gasneti_defaultSignalHandler ()
[0] #4  <signal handler called>
[0] #5  0x00007fead8bf25f7 in raise () from /usr/lib64/libc.so.6
[0] #6  0x00007fead8bf3ce8 in abort () from /usr/lib64/libc.so.6
[0] #7  0x00007fead8beb566 in __assert_fail_base () from /usr/lib64/libc.so.6
[0] #8  0x00007fead8beb612 in __assert_fail () from /usr/lib64/libc.so.6
[0] #9  0x0000000000f1c5d8 in LegionRuntime::LowLevel::find_shortest_path (src_mem=..., dst_mem=..., path=std::vector of length 0, capacity 0) at /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:2885  
[0] #10 0x0000000000f2c6c7 in LegionRuntime::LowLevel::CopyRequest::perform_new_dma<0u> (this=0x7fea95270fe0, src_mem=..., dst_mem=...) at /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:2894
[0] #11 0x0000000000f1c82f in LegionRuntime::LowLevel::CopyRequest::perform_dma (this=0x7fea95270fe0) at /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:3482
[0] #12 0x0000000000f19e77 in LegionRuntime::LowLevel::CopyRequest::check_readiness (this=0x7fea95270fe0, just_check=false, rq=0x0) at /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:613
[0] #13 0x0000000000f197ab in LegionRuntime::LowLevel::DmaRequest::Waiter::event_triggered (this=0x7fea95271188) at /home/gshipman/local/src/legion/runtime/lowlevel_dma.cc:501
[0] #14 0x0000000000f80bf7 in Realm::GenEventImpl::trigger (this=0x7fea978e1120, gen_triggered=2, trigger_node=0, wait_on=...) at /home/gshipman/local/src/legion/runtime/realm/event_impl.cc:903
[0] #15 0x0000000000f8084f in Realm::GenEventImpl::trigger_current (this=0x7fea978e1120) at /home/gshipman/local/src/legion/runtime/realm/event_impl.cc:817
[0] #16 0x0000000000f7d6d1 in Realm::MetadataBase::handle_response (this=0x7fea952824d8) at /home/gshipman/local/src/legion/runtime/realm/metadata.cc:80
[0] #17 0x0000000000f7dd19 in Realm::MetadataResponseMessage::handle_request (args=..., data=0x7feaccfe4280, datalen=204) at /home/gshipman/local/src/legion/runtime/realm/metadata.cc:279
[0] #18 0x0000000000f1140b in IncomingMediumMessage<Realm::MetadataResponseMessage::RequestArgs, 172, &Realm::MetadataResponseMessage::handle_request, 6>::run_handler (this=0x7fea95252ab0) at /home/gshipman/local/src/legion/runtime/activemsg.h:372
[0] #19 0x0000000000fdc34b in IncomingMessageManager::handler_thread_loop (this=0x1f6e020) at /home/gshipman/local/src/legion/runtime/activemsg.cc:770
[0] #20 0x0000000000fe49d8 in Realm::Thread::thread_entry_wrapper<IncomingMessageManager, &IncomingMessageManager::handler_thread_loop> (obj=0x1f6e020) at /home/gshipman/local/src/legion/runtime/realm/threads.inl:127
[0] #21 0x0000000000f55f65 in Realm::KernelThread::pthread_entry (data=0x1f6e210) at /home/gshipman/local/src/legion/runtime/realm/threads.cc:562
[0] #22 0x00007feada7cbdc5 in start_thread () from /usr/lib64/libpthread.so.0
[0] #23 0x00007fead8cb321d in clone () from /usr/lib64/libc.so.6

```

**Comment by streichler** [comment]
Galen,
  Does the single-node failure occur when using the master branch, or just the dma branch?

**Comment by gshipman** [comment]
Just the dma branch. I can also get the multi-node version to run using master if I map tasks locally.

**Comment by jiazhihao** [comment]
I have pushed implementation for unstructured data into dma branch. @gshipman Could you please pull and try how it works?
