### ISSUE TITLE
legion: hang on 2 nodes of sapling

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#1196]
I don't have enough information for a more descriptive title.

I see two threads stuck with these backtraces:
```
Thread 20 (Thread 0x7f25714e6840 (LWP 1364330)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000555e32fe06fa in Realm::Doorbell::wait_slow (this=this@entry=0x7f25714e67d0) at /home/rohany/taco/legion/legion/runtime/realm/mutex.cc:241
#2  0x0000555e32fe1248 in Realm::Doorbell::wait (this=0x7f25714e67d0) at /home/rohany/taco/legion/legion/runtime/realm/mutex.inl:81
#3  Realm::UnfairCondVar::wait (this=this@entry=0x7f25714dfd60) at /home/rohany/taco/legion/legion/runtime/realm/mutex.cc:874
#4  0x0000555e32f9e040 in Realm::KernelThreadTaskScheduler::worker_sleep (this=0x555e37772e90, switch_to=0x7f0ba0001880) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:1403
#5  0x0000555e32f9f189 in Realm::ThreadedTaskScheduler::thread_blocking (this=0x555e37772e90, thread=<optimized out>) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:908
#6  0x0000555e32efc455 in Realm::Thread::wait_for_condition<Realm::EventTriggeredCondition> (cond=..., poisoned=@0x7f25714e034f: false) at /home/rohany/taco/legion/legion/runtime/realm/event_impl.cc:160
#7  0x0000555e32eea828 in Realm::Event::wait_faultaware (this=0x7f25714e0618, poisoned=@0x7f25714e034f: false) at /home/rohany/taco/legion/legion/runtime/realm/event_impl.cc:254
#8  0x0000555e32eead64 in Realm::Event::wait (this=0x7f25714e0618) at /home/rohany/taco/legion/legion/runtime/realm/event_impl.cc:206
#9  0x0000555e32562a75 in Legion::Internal::LgEvent::wait (this=0x7f25714e0618) at /home/rohany/cmake-install/include/legion/legion_types.h:2793
#10 0x0000555e32c76f59 in Legion::Internal::ReplicateContext::add_to_dependence_queue (unordered=false, outermost=true, op=0x7f0ba001d870, this=0x7f0bac000ba0) at /home/rohany/taco/legion/legion/runtime/legion/legion_context.cc:18445
#11 Legion::Internal::ReplicateContext::add_to_dependence_queue (this=0x7f0bac000ba0, op=0x7f0ba001d870, unordered=<optimized out>, outermost=<optimized out>) at /home/rohany/taco/legion/legion/runtime/legion/legion_context.cc:18424
#12 0x0000555e32c679e0 in Legion::Internal::InnerContext::execute_task_launch (this=0x7f0bac000ba0, task=<optimized out>, index=<optimized out>, current_trace=0x0, silence_warnings=<optimized out>, inlining_enabled=<optimized out>) at /home/rohany/taco/legion/legion/runtime/legion/legion_context.cc:11007
#13 0x0000555e32ca6c02 in Legion::Internal::ReplicateContext::execute_index_space (this=0x7f0bac000ba0, launcher=..., outputs=0x0) at /home/rohany/taco/legion/legion/runtime/legion/legion_context.cc:16876
#14 0x0000555e327ff2f0 in Legion::Internal::Runtime::execute_index_space (this=<optimized out>, ctx=ctx@entry=0x7f0bac000ba0, launcher=..., outputs=outputs@entry=0x0) at /home/rohany/taco/legion/legion/runtime/legion/runtime.cc:18799
#15 0x0000555e325d14c5 in Legion::Runtime::execute_index_space (this=this@entry=0x555e37ddedc0, ctx=ctx@entry=0x7f0bac000ba0, launcher=..., outputs=outputs@entry=0x0) at /home/rohany/taco/legion/legion/runtime/legion/legion.cc:6052
#16 0x0000555e3253094e in computeLegionBatched (ctx=0x7f0bac000ba0, runtime=0x555e37ddedc0, A=<optimized out>, B=<optimized out>, C=<optimized out>, partitionPack=<optimized out>, gy=<optimized out>, gx=<optimized out>) at /home/rohany/taco/legion/spmm/taco-generated.cu:462
#17 0x0000555e32520037 in <lambda()>::operator() (__closure=0x7f0ba004aca0) at /home/rohany/taco/legion/spmm/main.cpp:74
#18 std::_Function_handler<void(), top_level_task(const Legion::Task*, const std::vector<Legion::PhysicalRegion>&, Legion::Context, Legion::Runtime*)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/9/bits/std_function.h:300
#19 0x0000555e3254f301 in std::function<void ()>::operator()() const (this=0x7f25714e4820) at /usr/include/c++/9/bits/std_function.h:683
#20 benchmarkAsyncCallWithWarmup(Legion::Internal::TaskContext*, Legion::Runtime*, int, int, std::function<void ()>) (ctx=0x7f0bac000ba0, runtime=0x555e37ddedc0, warmup=<optimized out>, numIter=1, f=...) at /home/rohany/taco/legion/src/legion_utils.cpp:74
#21 0x0000555e32521d8a in top_level_task (task=<optimized out>, regions=..., ctx=<optimized out>, runtime=<optimized out>) at /usr/include/c++/9/bits/std_function.h:87
#22 0x0000555e3252e384 in Legion::LegionTaskWrapper::legion_task_wrapper<&(top_level_task(Legion::Task const*, std::vector<Legion::PhysicalRegion, std::allocator<Legion::PhysicalRegion> > const&, Legion::Internal::TaskContext*, Legion::Runtime*))> (args=<optimized out>, arglen=<optimized out>, userdata=<optimized out>, userlen=<optimized out>, p=...) at /home/rohany/cmake-install/include/legion/legion.inl:22743
#23 0x0000555e32f5c32a in Realm::LocalTaskProcessor::execute_task (this=0x555e35c3d8f0, func_id=13, task_args=...) at /home/rohany/taco/legion/legion/runtime/realm/bytearray.inl:150
#24 0x0000555e32f9e313 in Realm::Task::execute_on_processor (this=0x555e365ab760, p=...) at /home/rohany/taco/legion/legion/runtime/realm/bytearray.inl:39
#25 0x0000555e32f9e39a in Realm::KernelThreadTaskScheduler::execute_task (this=<optimized out>, task=<optimized out>) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:1355
#26 0x0000555e32fa0c44 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x555e37772e90) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:1092
#27 0x0000555e32fa1201 in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x555e37772e90) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:1206
#28 0x0000555e32fa37b6 in Realm::KernelThread::pthread_entry (data=0x555e379e63a0) at /home/rohany/taco/legion/legion/runtime/realm/threads.cc:774
#29 0x00007f2591322609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#30 0x00007f258f2ba293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

```
Thread 26 (Thread 0x7f25704c6840 (LWP 1364429)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000555e32fe06fa in Realm::Doorbell::wait_slow (this=this@entry=0x7f25704c67d0) at /home/rohany/taco/legion/legion/runtime/realm/mutex.cc:241
#2  0x0000555e32fe1248 in Realm::Doorbell::wait (this=0x7f25704c67d0) at /home/rohany/taco/legion/legion/runtime/realm/mutex.inl:81
#3  Realm::UnfairCondVar::wait (this=this@entry=0x7f25704c19e0) at /home/rohany/taco/legion/legion/runtime/realm/mutex.cc:874
#4  0x0000555e32f9e040 in Realm::KernelThreadTaskScheduler::worker_sleep (this=0x555e37e1e820, switch_to=0x7f0b8c0850b0) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:1403
#5  0x0000555e32f9fa4e in Realm::ThreadedTaskScheduler::thread_blocking (this=0x555e37e1e820, thread=<optimized out>) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:872
#6  0x0000555e32efc455 in Realm::Thread::wait_for_condition<Realm::EventTriggeredCondition> (cond=..., poisoned=@0x7f25704c1fcf: false) at /home/rohany/taco/legion/legion/runtime/realm/event_impl.cc:160
#7  0x0000555e32eea828 in Realm::Event::wait_faultaware (this=0x7f25704c22b0, poisoned=@0x7f25704c1fcf: false) at /home/rohany/taco/legion/legion/runtime/realm/event_impl.cc:254
#8  0x0000555e32eead64 in Realm::Event::wait (this=0x7f25704c22b0) at /home/rohany/taco/legion/legion/runtime/realm/event_impl.cc:206
#9  0x0000555e32562a75 in Legion::Internal::LgEvent::wait (this=0x7f25704c22b0) at /home/rohany/cmake-install/include/legion/legion_types.h:2793
#10 0x0000555e32765fbc in Legion::Internal::RegionTreeForest::get_node (this=0x555e37ddc050, space=..., defer=<optimized out>, can_fail=<optimized out>, first=<optimized out>) at /home/rohany/taco/legion/legion/runtime/legion/region_tree.cc:4565
#11 0x0000555e3277cc8c in Legion::Internal::IndexPartNode::get_child (this=0x7f0ba002e4e0, c=1, defer=0x0) at /home/rohany/taco/legion/legion/runtime/legion/region_tree.cc:10718
#12 0x0000555e3278deb2 in Legion::Internal::RegionTreeForest::get_logical_subregion_by_color (this=<optimized out>, parent=..., realm_color=realm_color@entry=0x7f25704c54e0, type_tag=type_tag@entry=258) at /home/rohany/taco/legion/legion/runtime/legion/region_tree.cc:1604
#13 0x0000555e327ce4f9 in Legion::Internal::Runtime::get_logical_subregion_by_color (this=<optimized out>, par=..., realm_color=realm_color@entry=0x7f25704c54e0, type_tag=type_tag@entry=258) at /home/rohany/taco/legion/legion/runtime/legion/runtime.cc:18598
#14 0x0000555e325d0a68 in Legion::Runtime::get_logical_subregion_by_color (this=<optimized out>, parent=..., c=...) at /home/rohany/taco/legion/legion/runtime/legion/legion.cc:5803
#15 0x0000555e327c2ba9 in Legion::Internal::IdentityProjectionFunctor::project (this=this@entry=0x555e34e723b0, up_bound=..., point=..., launch_domain=...) at /home/rohany/taco/legion/legion/runtime/legion/runtime.cc:15120
#16 0x0000555e328184c1 in Legion::Internal::ProjectionFunction::project_points (this=0x7f0bb000e370, req=..., idx=idx@entry=5, runtime=<optimized out>, launch_domain=..., point_tasks=std::vector of length 1, capacity 1 = {...}) at /usr/include/c++/9/bits/stl_iterator.h:806
#17 0x0000555e326b82ba in Legion::Internal::SliceTask::enumerate_points (this=0x7f0b8c082890, inline_task=inline_task@entry=false) at /home/rohany/taco/legion/legion/runtime/legion/legion_tasks.cc:11464
#18 0x0000555e326b86d7 in Legion::Internal::SliceTask::map_and_launch (this=0x7f0b8c082890) at /home/rohany/taco/legion/legion/runtime/legion/legion_tasks.cc:10952
#19 0x0000555e326ada7d in Legion::Internal::MultiTask::trigger_mapping (this=0x7f0b8c082890) at /home/rohany/taco/legion/legion/runtime/legion/legion_tasks.cc:5443
#20 0x0000555e32867ec0 in Legion::Internal::Runtime::legion_runtime_task (args=0x7f0b7003ec10, arglen=12, userdata=<optimized out>, userlen=<optimized out>, p=...) at /home/rohany/taco/legion/legion/runtime/legion/runtime.cc:31238
#21 0x0000555e32f5c32a in Realm::LocalTaskProcessor::execute_task (this=0x555e37ad2080, func_id=4, task_args=...) at /home/rohany/taco/legion/legion/runtime/realm/bytearray.inl:150
#22 0x0000555e32f9e313 in Realm::Task::execute_on_processor (this=0x7f0b7003ea90, p=...) at /home/rohany/taco/legion/legion/runtime/realm/bytearray.inl:39
#23 0x0000555e32f9e39a in Realm::KernelThreadTaskScheduler::execute_task (this=<optimized out>, task=<optimized out>) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:1355
#24 0x0000555e32fa0c44 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x555e37e1e820) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:1092
#25 0x0000555e32fa1201 in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x555e37e1e820) at /home/rohany/taco/legion/legion/runtime/realm/tasks.cc:1206
#26 0x0000555e32fa37b6 in Realm::KernelThread::pthread_entry (data=0x7f0bbc00e820) at /home/rohany/taco/legion/legion/runtime/realm/threads.cc:774
#27 0x00007f2591322609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#28 0x00007f258f2ba293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I'm running with `-ll:defalloc 0 -ll:force_kthreads -lg:inorder -lg:safe_ctrlrepl 1` and am on `ebd70cc1015a931d6e8f6af2be503a4f21a7aa60` of Legion.

To reproduce on sapling, navigate to `/home/rohany/taco/build` and do `./runner.sh`, which runs on `g0001,g0002`. The Legion build there is `RelWithDebInfo`.

cc @lightsighter

**Comment by lightsighter** [comment]
Pull and try again.
