### ISSUE TITLE
Error with a debug build

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1197]
My applications triggered an error only with a debug build. I am (mostly) on ebd70cc. The command line was
```
mpirun --report-bindings -n 8 -npernode 4 -x LEGION_FREEZE_ON_ERROR --map-by numa:PE=5 ./wrapper.sh /home/bandokihiro/Builds_GPUNodes/DG-Legion/build_debug/exec/solver -logfile logs/log_%.log -hdf5:forcerw -dm:memoize -ll:cpu 0 -ll:util 1 -ll:bgwork 1 -ll:bgworkpin 1 -ll:csize 20000 -ll:rsize 0 -ll:gpu 1 -ll:fsize 14000 -ll:onuma 0 -ll:ocpu 1 -ll:othr 1 -lg:warn -lg:partcheck -lg:safe_ctrlrepl 1 -lg:safe_mapper -ll:force_kthreads
```
Here is an example backtrace.
[gdb.txt](https://github.com/StanfordLegion/legion/files/8084229/gdb.txt)

**Comment by streichler** [comment]
This looks like the relevant part:
```
#8  0x00007f8597280f36 in __GI___assert_fail (assertion=0x5593876db010 "origin_index < total_spaces", file=0x5593876d44f8 "/home/bandokihiro/Builds_GPUNodes/legion/runtime/legion/legion_replication.cc", line=8580, function=0x5593876db030 "void Legion::Internal::CollectiveMapping::get_children(Legion::AddressSpaceID, Legion::AddressSpaceID, std::vector<unsigned int>&) const") at assert.c:101
#9  0x0000559386354e94 in Legion::Internal::CollectiveMapping::get_children (this=0x7f773c01c7a0, origin=0, local=3, children=std::vector of length 0, capacity 0) at /home/bandokihiro/Builds_GPUNodes/legion/runtime/legion/legion_replication.cc:8580
#10 0x0000559386188c95 in Legion::Internal::EquivalenceSet::initialize_collective_references (this=0x7f772c23de60, local_valid=1) at /home/bandokihiro/Builds_GPUNodes/legion/runtime/legion/legion_analysis.cc:10156
#11 0x0000559386358fe2 in Legion::Internal::ShardManager::deduplicate_equivalence_set_creation (this=0x7f773c020f40, region_node=0x7f77500348c0, mask=..., did=64, first=@0x7f856a36aea3: false) at /home/bandokihiro/Builds_GPUNodes/legion/runtime/legion/legion_replication.cc:9257
#12 0x000055938633615d in Legion::Internal::ReplMergeCloseOp::trigger_mapping (this=0x7f772c23d4a0) at /home/bandokihiro/Builds_GPUNodes/legion/runtime/legion/legion_replication.cc:1456
#13 0x0000559385a4816a in Legion::Internal::Runtime::legion_runtime_task (args=0x7f7750036100, arglen=12, userdata=0x55986ce2a710, userlen=8, p=...) at /home/bandokihiro/Builds_GPUNodes/legion/runtime/legion/runtime.cc:31230
```
@lightsighter thoughts?

**Comment by lightsighter** [comment]
This is likely to be something that I'm not going to fix as this code has already been deleted in the collective instance branch, so the lifetime of this code can be measured in weeks. If you do want me to look at it I need a reproducer.

**Comment by bandokihiro** [comment]
do you have a rough ETA for the merge of the collective instance branch?

**Comment by lightsighter** [comment]
I'm aiming for mid-to-late March at this point, but it's highly variable depending on a lot of factors.

**Comment by bandokihiro** [comment]
I wasn't able to reproduce with fcced203e so closing this issue.
