### ISSUE TITLE
Choices of COORD_T other than Legion::coord_t break construction of RectInDomainIterator

### ISSUE THREAD

**Issue by dzhang314** [StanfordLegion/legion#1202]
Consider the following Legion program:

https://github.com/dzhang314/LegionSolvers/blob/main/src/Test01DenseVectorArithmetic.cpp

The main body of this program is the following task, which creates an index space of a given type, constructs several vectors based on that index space, and then performs a few arithmetic operations.

```
template <typename ENTRY_T, int DIM, typename COORD_T>
void test_task(const Legion::Task *,
               const std::vector<Legion::PhysicalRegion> &,
               Legion::Context ctx, Legion::Runtime *rt) {

    Legion::Rect<DIM, COORD_T> rect = create_rect<DIM, COORD_T>(100);
    Legion::IndexSpaceT<DIM, COORD_T> index_space = rt->create_index_space(ctx, rect);

    {
        LegionSolvers::DenseVector<ENTRY_T> u{ctx, rt, "u", index_space};
        LegionSolvers::DenseVector<ENTRY_T> v{ctx, rt, "v", u.get_index_space()};
        LegionSolvers::DenseVector<ENTRY_T> w{ctx, rt, "w", v.get_index_space()};

        u.random_fill();
        v.random_fill();
        w = u;

        w.axpy(1.0, v);
        v.xpay(-1.0, u);
        u.axpy(-0.5, v);
        u.axpy(-0.5, w);

        u.dot(u).assert_small();
    }

    rt->destroy_index_space(ctx, index_space);

}
```

This works fine when `COORD_T = Legion::coord_t` (i.e., `long long`), but breaks when `COORD_T` is one of the other types supported by Realm (`int` or `unsigned int`). What happens is that, inside the AXPY task, the construction of a `Legion::RectInDomainIterator<DIM, COORD_T>` throws the following assertion failure:

```
include/legion/legion_domain.inl:1013: Legion::Domain::operator Legion::DomainT<DIM, T>() const [with int DIM = 1; T = int; Legion::DomainT<DIM, T> = Realm::IndexSpace<1, int>]: Assertion `is_type == type' failed.
```

This failure appears to be specific to `RectInDomainIterator`; note that the preceding `random_fill` task runs without issue, and `random_fill` uses a `PointInDomainIterator`.

To reproduce this issue on Sapling, run the following command:

```
/home/dkzhang/LegionSolvers/build_master_debug/Test01DenseVectorArithmetic -ll:ocpu 1 -ll:onuma 0 -ll:gpu 1
```

**Comment by lightsighter** [comment]
Which branch and which commit are you on? That function and line number do not align with the `master` branch nor the `control_replication` branch.

**Comment by lightsighter** [comment]
This isn't a bug in the runtime. This is a bug in your application. If you have a sparsity map then you have to convert the `Domain` into precisely the right type for that sparsity map. If you give the wrong base coordinate type for the sparsity map then that is your fault. There is no way for the runtime to convert it.

**Comment by lightsighter** [comment]
Also, this doesn't have anything to do with the `RectInDomainIterator`. You're asking for the `Domain` here:

```
#4  0x00005555584591e1 in _ZNK6Legion6DomaincvN5Realm10IndexSpaceIXT_ET0_EEILi1EiEEv (this=0x7fffe3ff8800)
    at /scratch2/dkzhang/lib/legion_master_debug/include/legion/legion_domain.inl:1013
#5  0x000055555848a21b in LegionSolvers::AxpyTask<float, 1, int>::KokkosTaskTemplate<Kokkos::Cuda>::task_body (
    task=0x7fffdc29ad90, regions=std::vector of length 2, capacity 2 = {...}, ctx=0x7fffe44c5c00, rt=0x55556129f4f0)
    at /home/dkzhang/LegionSolvers/src/LinearAlgebraTasks.cpp:110
```

**Comment by dzhang314** [comment]
@lightsighter Hmm, you're right -- the problematic part actually seems to be the call to `get_index_space_domain`. This seriously confuses me, as I don't think what I'm doing should be an application error, but possibly I'm not understanding the Legion type system correctly.

What I do in this program is:

- I construct an `IndexSpaceT<1, int> I`.
- I construct a logical region `R` based on that index space `I`.
- Later, inside a task that uses `R`, I call `rt->get_index_space_domain(ctx, R.get_index_space())` to retrieve the domain `D` on which my region `R` is based.
- At this point, Legion mistakenly tells me "hey, the types don't match" (``Assertion `is_type == type' failed.``).

Am I simply not allowed to call `get_index_space_domain` for region `R` based on an index space `I` whose coordinate type is different from `Legion::coord_t`? I thought that `Legion::Domain` was type-erased, so regardless of what the dimension and coordinate type of `I` are, I would always be able to call `get_index_space_domain`.

**Comment by lightsighter** [comment]
> I thought that Legion::Domain was type-erased, so regardless of what the dimension and coordinate type of I are, I would always be able to call get_index_space_domain.

That is not accurate. Realm sparsity maps have a coordinate type and there is no way for Legion to convert them.

**Comment by dzhang314** [comment]
Hm, okay. So I'm not allowed to call `get_index_space_domain`; in that case, what is the idiomatic Legion way to iterate over the rectangles in my region `R`?

**Comment by lightsighter** [comment]
>  So I'm not allowed to call get_index_space_domain;

Legion will do the implicit conversion for you in the case that your `Domain` objects are dense, because it can do that trivially. There is no primitive in Realm that supports conversion of the types for a sparsity map. If you want to go build that in Realm then I'll be happy to teach Legion to use it so you can get implicit conversion of sparsity maps.

>  what is the idiomatic Legion way to iterate over the rectangles in my region R?

Assuming R is a physical region, then you want the `PieceIterator` class to iterate over the rectangles in the physical instance.
