### ISSUE TITLE
HIP: legion_prof.py fails on circuit

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1213]
I am not able to use legion_prof.py on circuit when using hip. I do not have problems when using cuda. I am seeing the following error on the latest control_replication (e08ecb0f14):

 ```
[seshuy@crusher017.crusher circuit]$ legion_prof.py prof_0.gz 
Reading log file prof_0.gz...
parsing prof_0.gz
Matched 6056 objects
Traceback (most recent call last):
  File "/gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_crusher/legion/tools/legion_prof.py", line 4143, in <module>
    main()
  File "/gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_crusher/legion/tools/legion_prof.py", line 4136, in main
    state.emit_interactive_visualization(output_dirname, show_procs,
  File "/gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_crusher/legion/tools/legion_prof.py", line 3843, in emit_interactive_visualization
    self.assign_colors()
  File "/gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_crusher/legion/tools/legion_prof.py", line 3240, in assign_colors
    for variant in sorted(itervalues(self.variants), key=lambda v: (v.task_kind.task_id, v.variant_id)):
  File "/gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_crusher/legion/tools/legion_prof.py", line 3240, in <lambda>
    for variant in sorted(itervalues(self.variants), key=lambda v: (v.task_kind.task_id, v.variant_id)):
AttributeError: 'NoneType' object has no attribute 'task_id'
```

There is a log here: http://sapling.stanford.edu/~seshu/prof_0.gz

**Comment by eddy16112** [comment]
@lightsighter I think the Task 17 is the internal reduction task, because if I enable `USE_GPU_REDUCTIONS`, I can reproduce the same error with cuda module, and on the other side, if I disable `USE_GPU_REDUCTIONS` for hip module, the error is gone.

**Comment by lightsighter** [comment]
@syamajala Can you test the CUDA version again with `USE_GPU_REDUCTIONS` again and see if you see the same problem? We need to resolve the different behavior that you and @eddy16112 are observing with the CUDA version.

**Comment by lightsighter** [comment]
@syamajala Pull and try again.

**Comment by eddy16112** [comment]
@lightsighter It works for me now. Thank you for the fix.

**Comment by syamajala** [comment]
This works on both CUDA and HIP.
