### ISSUE TITLE
Realm: gasnetex seg fault on Summit

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1226]
I'm seeing a seg. fault on 16 nodes on Summit when using gasnetex.

```
[65] #9  0x000020000458c744 in std::__atomic_base<unsigned int>::fetch_or (__m=std::memory_order_acq_rel, __i=1, this=0x1) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/mutex.inl:168
[65] #10 Realm::atomic<unsigned int>::fetch_or_acqrel (to_or=1, this=0x1) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/atomics.inl:241
[65] #11 Realm::UnfairMutex::lock (this=0x1) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/mutex.inl:168
[65] #12 Realm::AutoLock<Realm::UnfairMutex>::AutoLock (mutex=..., this=<synthetic pointer>) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/mutex.inl:253
[65] #13 Realm::XferDesQueue::enqueue_xferDes_local (this=0x1, xd=0x2015b2233c50, add_to_queue=false) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/transfer/channel.cc:6310
[65] #14 0x00002000045a1080 in Realm::SingleXDQChannel<Realm::RemoteWriteChannel, Realm::RemoteWriteXferDes>::enqueue_ready_xd (this=0x1ba02d60, xd=0x2015b2233c50) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/transfer/channel.inl:300
[65] #15 0x0000200004594398 in Realm::SimpleXferDesFactory::create_xfer_des (this=0x1ba02d88, dma_op=<optimized out>, launch_node=<optimized out>, target_node=<optimized out>, guid=18296152659305946, inputs_info=..., outputs_info=..., priority=<optimized out>, redop_info=..., fill_data=0x0, fill_size=0) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/transfer/channel.cc:4819
[65] #16 0x00002000045b0bd8 in Realm::TransferOperation::create_xds (this=0x201446ef96c0) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/transfer/transfer.cc:4700
[65] #17 0x00002000045b1e00 in Realm::TransferOperation::allocate_ibs (this=0x201446ef96c0) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/transfer/transfer.cc:4327
[65] #18 0x00002000047f4188 in Realm::EventTriggerNotifier::trigger_event_waiters (this=0x150982d8, to_trigger=..., poisoned=<optimized out>, trigger_until=...) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/event_impl.cc:543
[65] #19 0x00002000047fe2bc in Realm::GenEventImpl::process_update (this=0x2015b1567678, current_gen=<optimized out>, new_poisoned_generations=0x0, new_poisoned_count=0, work_until=...) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/runtime_impl.h:395
[65] #20 0x00002000047fe794 in Realm::EventUpdateMessage::handle_message (sender=<optimized out>, args=..., data=0x0, datalen=<optimized out>, work_until=...) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/id.h:73
[65] #21 0x000020000497c880 in Realm::IncomingMessageManager::do_work (this=0x1551fed0, work_until=...) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/activemsg.cc:740
[65] #22 0x00002000047ed304 in Realm::BackgroundWorkManager::Worker::do_work (this=0x200041b4eb18, max_time_in_ns=-1, interrupt_flag=0x0) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/timers.inl:255
[65] #23 0x00002000047edb90 in Realm::BackgroundWorkThread::main_loop (this=0x15319590) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/bgwork.cc:125
[65] #24 0x0000200004905bb0 in Realm::KernelThread::pthread_entry (data=0x1b9fc2f0) at /gpfs/alpine/cmb103/scratch/seshuy/legion_s3d_nscbc_summit/legion/runtime/realm/threads.cc:774
[65] #25 0x0000200000878ae0 in start_thread () from /lib64/power9/libpthread.so.0
[65] #26 0x00002000009ee7c8 in clone () from /lib64/power9/libc.so.6
```

**Comment by streichler** [comment]
@syamajala is this still occurring with recent versions of legion/realm?

**Comment by syamajala** [comment]
I will try a recent version and let you know.

**Comment by syamajala** [comment]
I ran up to 64 nodes with gasnetex on Summit without any issues.
