### ISSUE TITLE
Realm: PendingCompletion::invoke_local_completions assertion

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1233]
I am hitting this assertion on Perlmutter at 96 and 128 nodes:

```
s3d.x: /global/u1/s/seshu/legion_s3d/legion/runtime/realm/gasnet1/gasnetmsg.cc:3233: bool PendingCompletion::invoke_local_completions(): Assertion `(prev_state & LOCAL_PENDING_BIT) != 0' failed.
```

Here is a stack trace:
```
[127] Thread 6 (Thread 0x7fe9523fc700 (LWP 129402) "s3d.x"):
[127] #0  0x00007fe96cb07157 in waitpid () from /lib64/libc.so.6
[127] #1  0x00007fe96ca846af in do_system () from /lib64/libc.so.6
[127] #2  0x00007fe9669cd829 in gasneti_system_redirected () from /global/homes/s/seshu/legion_s3d/legion/language/build/lib/librealm.so.1
[127] #3  0x00007fe9669cdee8 in gasneti_bt_gdb () from /global/homes/s/seshu/legion_s3d/legion/language/build/lib/librealm.so.1
[127] #4  0x00007fe9669d16ac in gasneti_print_backtrace () from /global/homes/s/seshu/legion_s3d/legion/language/build/lib/librealm.so.1
[127] #5  0x00007fe9661d5907 in gasneti_defaultSignalHandler () from /global/homes/s/seshu/legion_s3d/legion/language/build/lib/librealm.so.1
[127] #6  <signal handler called>
[127] #7  0x00007fe96ca77360 in raise () from /lib64/libc.so.6
[127] #8  0x00007fe96ca78941 in abort () from /lib64/libc.so.6
[127] #9  0x00007fe96ca6fa5a in __assert_fail_base () from /lib64/libc.so.6
[127] #10 0x00007fe96ca6fad2 in __assert_fail () from /lib64/libc.so.6
[127] #11 0x00007fe9664f5776 in PendingCompletion::invoke_local_completions (this=this@entry=0xb49e230) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/gasnet1/gasnetmsg.cc:3233
[127] #12 0x00007fe9664f5ac8 in PendingCompletionManager::invoke_completions (this=0x7fe966f16da0 <completion_manager>, index=<optimized out>, do_local=<optimized out>, do_remote=<optimized out>) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/gasnet1/gasnetmsg.cc:3396
[127] #13 0x00007fe9669ca77b in gasnetc_ofi_poll () from /global/homes/s/seshu/legion_s3d/legion/language/build/lib/librealm.so.1
[127] #14 0x00007fe9669bee59 in gasnetc_AMPoll () from /global/homes/s/seshu/legion_s3d/legion/language/build/lib/librealm.so.1
[127] #15 0x00007fe9664f7bab in _gasneti_AMPoll () at /global/u1/s/seshu/legion_s3d/gasnet/release/include/gasnet_help.h:1310
[127] #16 _gasnet_AMPoll () at /global/u1/s/seshu/legion_s3d/gasnet/release/include/gasnet_help.h:1523
[127] #17 EndpointManager::do_work (this=0xb37c5a0, work_until=...) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/gasnet1/gasnetmsg.cc:2825
[127] #18 0x00007fe9663c7349 in Realm::BackgroundWorkManager::Worker::do_work (this=0x7fe9523f8a00, max_time_in_ns=<optimized out>, interrupt_flag=0x0) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/bgwork.cc:621
[127] #19 0x00007fe9663c7b71 in Realm::BackgroundWorkThread::main_loop (this=0xb256fd0) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/bgwork.cc:125
[127] #20 0x00007fe9664a9d8f in Realm::KernelThread::pthread_entry (data=0xb451f80) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/threads.cc:774
[127] #21 0x00007fe965ca1539 in start_thread () from /lib64/libpthread.so.0
[127] #22 0x00007fe96cb39e0f in clone () from /lib64/libc.so.6
```

**Comment by syamajala** [comment]
Using gasnetex works on Perlmutter.
