### ISSUE TITLE
Non-deterministic failure

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1239]
In order to find the most convenient set of data for #1235, I have been runnning on Piz Daint in a while true loop. The 12-node configuration failed a few times with the same backtrace. I wanted to report this because I am not sure this is the same problem as #1235.
```
[1] #5  <signal handler called>
[1] #6  Legion::Internal::PhysicalTemplate::ViewUser::ViewUser (this=0x1554bc128cf0, r=..., u=727, e=0x0, s=0) at /users/kbando/Softwares/legion/runtime/legion/legion_trace.cc:6213
[1] #7  0x0000000001f95e1f in Legion::Internal::PhysicalTemplate::add_view_user (this=0x155484010380, view=0x155484060950, usage=..., user_index=727, user_expr=0x0, user_mask=..., applied=..., owner_shard=0) at /users/kbando/Softwares/legion/runtime/legion/legion_trace.cc:6234
[1] #8  0x0000000001f9ca7f in Legion::Internal::ShardedPhysicalTemplate::handle_update_view_user (this=0x155484010380, view=0x155484060950, user_expr=0x0, derez=..., applied=..., done=..., dargs=0x0) at /users/kbando/Softwares/legion/runtime/legion/legion_trace.cc:7786
[1] #9  0x0000000001f9a8cf in Legion::Internal::ShardedPhysicalTemplate::handle_trace_update (this=0x155484010380, derez=..., source=0) at /users/kbando/Softwares/legion/runtime/legion/legion_trace.cc:7300
[1] #10 0x0000000002956d80 in Legion::Internal::ReplicateContext::handle_trace_update (this=0x1554cc000b50, derez=..., source=0) at /users/kbando/Softwares/legion/runtime/legion/legion_context.cc:19051
[1] #11 0x0000000001f2cd18 in Legion::Internal::ShardTask::handle_trace_update (this=0x1554d40266f0, derez=..., source=0) at /users/kbando/Softwares/legion/runtime/legion/legion_tasks.cc:8093
[1] #12 0x0000000002a120d8 in Legion::Internal::ShardManager::handle_trace_update (this=0x1554d40262b0, derez=..., source=0) at /users/kbando/Softwares/legion/runtime/legion/legion_replication.cc:10148
[1] #13 0x0000000002a126d8 in Legion::Internal::ShardManager::handle_trace_update (derez=..., runtime=0x596bd20, source=0) at /users/kbando/Softwares/legion/runtime/legion/legion_replication.cc:10298
[1] #14 0x0000000002159559 in Legion::Internal::Runtime::handle_control_replicate_trace_update (this=0x596bd20, derez=..., source=0) at /users/kbando/Softwares/legion/runtime/legion/runtime.cc:24017
[1] #15 0x0000000002129713 in Legion::Internal::VirtualChannel::handle_messages (this=0x1554c4000b80, num_messages=1, runtime=0x596bd20, remote_address_space=0, args=0x15546c0425a0 "\f", arglen=152) at /users/kbando/Softwares/legion/runtime/legion/runtime.cc:12141
[1] #16 0x00000000021284f0 in Legion::Internal::VirtualChannel::process_message (this=0x1554c4000b80, args=0x15546c042584, arglen=172, runtime=0x596bd20, remote_address_space=0) at /users/kbando/Softwares/legion/runtime/legion/runtime.cc:11396
[1] #17 0x000000000212a645 in Legion::Internal::MessageManager::receive_message (this=0x1554c4000b50, args=0x15546c042580, arglen=180) at /users/kbando/Softwares/legion/runtime/legion/runtime.cc:12844
[1] #18 0x000000000215d20e in Legion::Internal::Runtime::process_message_task (this=0x596bd20, args=0x15546c04257c, arglen=184) at /users/kbando/Softwares/legion/runtime/legion/runtime.cc:25418
[1] #19 0x0000000002172037 in Legion::Internal::Runtime::legion_runtime_task (args=0x15546c042570, arglen=188, userdata=0x596b6f0, userlen=8, p=...) at /users/kbando/Softwares/legion/runtime/legion/runtime.cc:30941
[1] #20 0x0000000002eaac98 in Realm::LocalTaskProcessor::execute_task (this=0x58c4080, func_id=4, task_args=...) at /users/kbando/Softwares/legion/runtime/realm/proc_impl.cc:1135
[1] #21 0x0000000002f079b4 in Realm::Task::execute_on_processor (this=0x1554f009b4f0, p=...) at /users/kbando/Softwares/legion/runtime/realm/tasks.cc:302
[1] #22 0x0000000002f0b560 in Realm::KernelThreadTaskScheduler::execute_task (this=0x58c43c0, task=0x1554f009b4f0) at /users/kbando/Softwares/legion/runtime/realm/tasks.cc:1355
[1] #23 0x0000000002f0a427 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x58c43c0) at /users/kbando/Softwares/legion/runtime/realm/tasks.cc:1094
[1] #24 0x0000000002f0aa04 in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x58c43c0) at /users/kbando/Softwares/legion/runtime/realm/tasks.cc:1206
[1] #25 0x0000000002f11b60 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock> (obj=0x58c43c0) at /users/kbando/Softwares/legion/runtime/realm/threads.inl:97
[1] #26 0x0000000002f1d971 in Realm::KernelThread::pthread_entry (data=0x15548801c120) at /users/kbando/Softwares/legion/runtime/realm/threads.cc:774
[1] #27 0x000015554c9c04f9 in start_thread () from /lib64/libpthread.so.0
[1] #28 0x000015554bd95ecf in clone () from /lib64/libc.so.6
```

**Comment by lightsighter** [comment]
It's not, pull and try again.

**Comment by bandokihiro** [comment]
Seems fixed. Thanks.
