### ISSUE TITLE
Realm: GasnetEX init failure using OFI

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1247]
I am no longer able to run on Perlmutter using the latest legion (5f820549e5d7c9) with GasnetEX and the OFI conduit. I see this error:
```
*** FATAL ERROR (proc 0): in gasnetc_ofi_init() at ion_s3d/gasnet/GASNet-2022.3.0/ofi-conduit/gasnet_ofi.c:722: fi_endpoint for rdma failed: -61(No data available)
```

It happens on 1 node with 4 ranks. Here is a stack trace:
```
[3] #6  0x00007f4473a7d169 in _gasneti_fatalerror () from /global/homes/s/seshu/legion_s3d/legion/language/build/lib/librealm.so.1
[3] #7  0x00007f4474285674 in gasnetc_ofi_init () from /global/homes/s/seshu/legion_s3d/legion/language/build/lib/librealm.so.1
[3] #8  0x00007f447427c4d5 in gex_Client_Init_GASNET_202230PARnopshmFASTnodebugnotracenostatsnodebugmallocnosrclines () from /global/homes/s/seshu/legion_s3d/legion/language/build/lib/librealm.so.1
[3] #9  0x00007f4473db6d0b in Realm::GASNetEXInternal::init (this=0x4cc77e0, argc=argc@entry=0x7ffc4dde1fe4, argv=argv@entry=0x7ffc4dde1fe8) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/gasnetex/gasnetex_internal.cc:3176
[3] #10 0x00007f4473da3900 in Realm::GASNetEXModule::create_network_module (runtime=0x4cc6540, argc=0x7ffc4dde1fe4, argv=0x7ffc4dde1fe8) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/gasnetex/gasnetex_module.cc:470
[3] #11 0x00007f4473dc38b2 in Realm::ModuleRegistrar::create_network_modules (this=0x4cc75d8, modules=..., argc=argc@entry=0x7ffc4dde1fe4, argv=argv@entry=0x7ffc4dde1fe8) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/network.cc:593
[3] #12 0x00007f4473d2a87e in Realm::RuntimeImpl::network_init (this=<optimized out>, argc=0x7ffc4dde3b6c, argv=0x7ffc4dde3b60) at /global/u1/s/seshu/legion_s3d/legion/runtime/realm/runtime_impl.cc:1022
[3] #13 0x00007f4475014f73 in Legion::Internal::Runtime::initialize (argc=0x7ffc4dde3b6c, argv=0x7ffc4dde3b60, filter=<optimized out>) at /global/u1/s/seshu/legion_s3d/legion/runtime/legion/runtime.cc:29082
[3] #14 0x00007f4475069c38 in Legion::Internal::Runtime::start (argc=<optimized out>, argv=<optimized out>, background=<optimized out>, supply_default_mapper=<optimized out>) at /global/u1/s/seshu/legion_s3d/legion/runtime/legion/runtime.cc:29002
```

**Comment by streichler** [comment]
Can you confirm that an older legion build still works?  I don't think anything has changed in the Realm network init code in a while.

**Comment by syamajala** [comment]
Old legion fails too actually. Its possible this is an issue with Perlmutter. They're having some issues with the machine right now and a number of people are complaining about issues with MPI_Init failing.

I am actually able to run on Crusher using OFI.

**Comment by syamajala** [comment]
I think this was a problem with the machine. I am able to run again on Perlmutter.
