### ISSUE TITLE
legion_spy and stack depth

### ISSUE THREAD

**Issue by fdouglis** [StanfordLegion/legion#1269]
I tried to run spy on a FlexFlow run.  It blew up in size (400GB when I last checked it) and eventually died with a python recursion level exception.  This seems like the sort of thing it should be able to guard against and try to do a best-effort result rather than complete failure.

```Traceback (most recent call last):
  File "/home/fdouglis/src/legion/tools/legion_prof.py", line 4073, in <module>
    main()
  File "/home/fdouglis/src/legion/tools/legion_prof.py", line 4066, in main
    state.emit_interactive_visualization(output_dirname, show_procs,
  File "/home/fdouglis/src/legion/tools/legion_prof.py", line 3830, in emit_interactive_visualization
    op_dependencies, transitive_map = self.get_op_dependencies(file_names)
  File "/home/fdouglis/src/legion/tools/legion_prof.py", line 3605, in get_op_dependencies
    self.spy_state.simplify_physical_graph(need_cycle_check=False)
  File "/misc/gw/home/fdouglis/src/legion/tools/legion_spy.py", line 12339, in simplify_physical_graph
    topological_sorter.visit_node(op)
  File "/misc/gw/home/fdouglis/src/legion/tools/legion_spy.py", line 10632, in visit_node
    self.visit_node(next_node)
  File "/misc/gw/home/fdouglis/src/legion/tools/legion_spy.py", line 10632, in visit_node
    self.visit_node(next_node)
  File "/misc/gw/home/fdouglis/src/legion/tools/legion_spy.py", line 10632, in visit_node
    self.visit_node(next_node)
  [Previous line repeated 991 more times]
  File "/misc/gw/home/fdouglis/src/legion/tools/legion_spy.py", line 10619, in visit_node
    if node.generation == self.generation:
RecursionError: maximum recursion depth exceeded in comparison```

**Comment by lightsighter** [comment]
Legion Spy is a formal verification tool, and like most formal verification tools, there is a limit to its powers and it's often prone to out-of-memory errors. In this particular case it looks like you gave it a graph with a very large depth, and one of the depth-first search algorithms recursed too many times for Python to handle.  Certainly we can rewrite the depth-first search traversals to do it using an explicit stack instead of relying on recursion, but I bet we're still going to run out of memory. An immediate work around is to manually alter the recursion depth of your Python interpreter:
https://docs.python.org/3/library/sys.html#sys.setrecursionlimit

**Comment by lightsighter** [comment]
This is fixed with https://gitlab.com/StanfordLegion/legion/-/merge_requests/505 which moves all the depth-first search algorithms in Legion Spy to using a stack. Running out of memory is still a very real possibility, but is a limitation of many formal verification tools.

**Comment by fdouglis** [comment]
Thanks!
