### ISSUE TITLE
Realm: ctxswitch test fail on Apple M1

### ISSUE THREAD

**Issue by eddy16112** [StanfordLegion/legion#1286]
After I run the `./test.py -v -j 10 --test realm` on my MacBook, the cxtswitch test fails, other realm tests as well as legion_cxx tests are running OK. This test works fine on Mac OS with intel CPU. 
```
./ctxswitch -ll:io 1 -t 20 -i 10000
[0 - 102ad8580]    0.000000 {4}{threads}: reservation ('dedicated worker (generic) #1') cannot be satisfied
Realm context switching test - 4 children, 10000 iterations, 20s timeout
testing processor 1d00000000000000 (kind=3)
switch: proc 1d00000000000000 (kind=3) finished: elapsed= 0.00s time/switch=     1ns
sleep: proc 1d00000000000000 (kind=3) finished: elapsed= 0.00s expected= 2.00s
TOO FAST!
testing processor 1d00000000000001 (kind=4)
switch: proc 1d00000000000001 (kind=4) finished: elapsed= 0.00s time/switch=     1ns
sleep: proc 1d00000000000001 (kind=4) finished: elapsed= 0.00s expected= 2.00s
TOO FAST!
testing processor 1d00000000000002 (kind=2)
switch: proc 1d00000000000002 (kind=2) finished: elapsed= 0.00s time/switch=     1ns
sleep: proc 1d00000000000002 (kind=2) finished: elapsed= 0.00s expected= 2.00s
TOO FAST!
Exiting with errors
make: *** [run_ctxswitch] Error 1

############################################################
### Exiting Stage: realm
###   * Exception Type: <class 'subprocess.CalledProcessError'>
###   * Elapsed Time: 0:00:41.628346
############################################################

Removing build directory:
  /Users/weiwu/legion_test/tmpb0ulx8o0
Traceback (most recent call last):
  File "/Users/weiwu/legion_test/./test.py", line 1209, in <module>
    driver()
  File "/Users/weiwu/legion_test/./test.py", line 1206, in driver
    run_tests(**vars(args))
  File "/Users/weiwu/legion_test/./test.py", line 1074, in run_tests
    run_test_realm(launcher, root_dir, tmp_dir, bin_dir, env, thread_count, timelimit)
  File "/Users/weiwu/legion_test/./test.py", line 347, in run_test_realm
    cmd([make_exe, '-C', test_dir, 'DEBUG=0', 'run_all'], env=env, timelimit=timelimit)
  File "/Users/weiwu/legion_test/./test.py", line 230, in cmd
    return subprocess.check_call(command, env=env, cwd=cwd)
  File "/Users/weiwu/opt/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '/Users/weiwu/legion_test/test/realm', 'DEBUG=0', 'run_all']' returned non-zero exit status 2.
```

**Comment by lightsighter** [comment]
I can reproduce this on my M1 laptop as well. Despite the fact that the elapsed times are all "0.00", that doesn't actually seem to be the case. When I look at `t_start` and `t_end` they look like this:

```
(lldb) p t_start
(double) $0 = 0.00016545200000000001
(lldb) p t_end
(double) $1 = 0.001328868
(lldb) p elapsed
(double) $2 = 0.001163416
(lldb) p exp_time
(double) $3 = 2
```

It looks like everything is just off by a factor of a 1000. I looked through the code a bit, but couldn't see anywhere obvious that we were missing the extra factor. We're going down the slow path to compute times using `mach_absolute_time`:

```
  * frame #0: 0x00000001005c8198 ctxswitch`Realm::Clock::native_time_slower() at timers.cc:68:18
    frame #1: 0x00000001000026f4 ctxswitch`Realm::Clock::native_time() at timers.inl:84:12
    frame #2: 0x0000000100002660 ctxswitch`Realm::Clock::current_time_in_nanoseconds(absolute=false) at timers.inl:66:23
    frame #3: 0x0000000100001fd4 ctxswitch`Realm::Clock::current_time(absolute=false) at timers.inl:56:13
```

and then the converting:

```
  * frame #0: 0x000000010000271c ctxswitch`Realm::Clock::TimescaleConverter::convert_forward_absolute(this=0x000000010066f140, ta=56923077095774) at timers.inl:133:5
    frame #1: 0x0000000100002674 ctxswitch`Realm::Clock::current_time_in_nanoseconds(absolute=false) at timers.inl:67:50
    frame #2: 0x0000000100001fd4 ctxswitch`Realm::Clock::current_time(absolute=false) at timers.inl:56:13
```

I have a vague understanding of what `slope_a_to_b` is doing, trying to interpolate times, but I'm not entirely sure:

```
p slope_a_to_b
(uint64_t) $10 = 103079215
```
