### ISSUE TITLE
Legion Spy crash on provenance

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1334]
Log file: [spy_0.log](https://github.com/StanfordLegion/legion/files/9640115/spy_0.log)

Causes this crash:

```
$ python3 ../legion_spy.py -e ../../language/spy_0.log 
Reading log file ../../language/spy_0.log...
...
Traceback (most recent call last):
  File "../legion_spy.py", line 13080, in <module>
    main(temp_dir)
  File "../legion_spy.py", line 13055, in main
    state.make_event_graph(temp_dir, zoom_graphs)
  File "../legion_spy.py", line 12273, in make_event_graph
    op.print_event_graph(printer, elevate, all_nodes, True) 
  File "../legion_spy.py", line 7662, in print_event_graph
    task.print_event_graph_context(printer, elevate, all_nodes, top)
  File "../legion_spy.py", line 8331, in print_event_graph_context
    op.print_event_graph(printer, elevate, all_nodes, False)
  File "../legion_spy.py", line 7662, in print_event_graph
    task.print_event_graph_context(printer, elevate, all_nodes, top)
  File "../legion_spy.py", line 8309, in print_event_graph_context
    title = self.html_safe_name + ' (UID: '+str(self.op.uid)+')'
  File "../legion_spy.py", line 7873, in html_safe_name
    provenance = self.get_provenance()
  File "../legion_spy.py", line 7868, in get_provenance
    return op.get_provenance()
NameError: name 'op' is not defined
```

This is on my branch based on `master` f94a50bd52305de7015d55b33a4a1d26e44fd1a8, and I have no local changes to `legion_spy.py`.

**Comment by lightsighter** [comment]
You probably could have fixed this one yourself:

https://gitlab.com/StanfordLegion/legion/-/commit/198b1df3ebac8888428a2e3d318c49f55340819e

**Comment by elliottslaughter** [comment]
Thanks!
