### ISSUE TITLE
Profiler: Cannot process only a subset of the log files

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#1372]
It looks like recent changes to the profiling now make it impossible to process only a subset of the files, e.g. from a 2-node run:

```
prm-login:/gpfs/fs1/mpapadakis/2023/01/05/100735/temp> /gpfs/fs1/mpapadakis/legion/tools/legion_prof.py ../legate_0.prof
Reading log file ../legate_0.prof...
parsing ../legate_0.prof
Matched 17588 objects
Traceback (most recent call last):
  File "/gpfs/fs1/mpapadakis/legion/tools/legion_prof.py", line 5567, in <module>
    main()
  File "/gpfs/fs1/mpapadakis/legion/tools/legion_prof.py", line 5552, in main
    state.link_instances()
  File "/gpfs/fs1/mpapadakis/legion/tools/legion_prof.py", line 5160, in link_instances
    copy.link_instance(self.instances)
  File "/gpfs/fs1/mpapadakis/legion/tools/legion_prof.py", line 2196, in link_instance
    node.link_instance(instances)
  File "/gpfs/fs1/mpapadakis/legion/tools/legion_prof.py", line 2066, in link_instance
    assert 0, "Copy can not find src_inst:" + str(hex(self.src_inst_uid))
AssertionError: Copy can not find src_inst:0x8000800004a00001
```

However, I might only want to emit the first 5 nodes from a large run, so the html output isn't overwhelming.

Even if now we need to consult the log files from all nodes, it would be good to have an option to only actually emit a subset of the nodes to the html output.

**Comment by eddy16112** [comment]
Yes, we can not process a subset of the files because we need to associate instances with operations. This error tells that the instance of the Copy Operator is not logged.

**Comment by elliottslaughter** [comment]
Would it be possible to generate output in this case, and assign the copy to an "unknown" channel or similar? I realize we may have holes in our information, but this seems like a big loss in functionality.

**Comment by eddy16112** [comment]
I think we might be able to safely ignore the error. @manopapad could you please provide me your log files and I can play with it.

**Comment by eddy16112** [comment]
The bug has been fixed by this MR https://gitlab.com/StanfordLegion/legion/-/merge_requests/632, and is now in the master branch.

**Comment by manopapad** [comment]
This works now, although we lose the outgoing transfers, e.g. if node 0 is included in the processing, but node 1 isn't, then we will see the transfers from node 1 to node 0, but we won't see any transfers from node 0 to node 1.

<img width="1068" alt="Screen Shot 2023-01-09 at 2 05 18 PM" src="https://user-images.githubusercontent.com/215728/211417810-18909f09-7fc2-4f01-be0e-23438f4eeedc.png">

Previously, the behavior was reversed; we would only see transfers from node 0 to 1:

<img width="1068" alt="Screen Shot 2023-01-09 at 2 05 01 PM" src="https://user-images.githubusercontent.com/215728/211418059-54654ac0-6e0b-4055-829b-c2756720af1d.png">

Is it a fundamental limitation that we can't see both?

**Comment by eddy16112** [comment]
@lightsighter for visibility. 
I think it depends on how Legion dumps the logs. I print the `src` and `dst` memory of each Copy (`CopyInstInfo`) in the log file of node 0 and 1 respectively. 
node 0:
```
0x1e00000000000002 0x1e00000000000002
0x1e00010000000002 0x1e00000000000002
0x1e00010000000002 0x1e00000000000002
0x1e00000000000002 0x1e00000000000002
0x1e00010000000002 0x1e00000000000002
0x1e00010000000002 0x1e00000000000002
0x1e00000000000002 0x1e00000000000002
0x1e00010000000002 0x1e00000000000002
0x1e00000000000002 0x1e00000000000002
...
```

node 1:
```
0x1e00010000000002 0x1e00010000000002
0x1e00010000000002 0x1e00010000000002
0x1e00000000000002 0x1e00010000000002
0x1e00010000000002 0x1e00010000000002
0x1e00000000000002 0x1e00010000000002
0x1e00000000000002 0x1e00010000000002
0x1e00010000000002 0x1e00010000000002
0x1e00010000000002 0x1e00010000000002
0x1e00010000000002 0x1e00010000000002
...
```

So node 0 contains copies from node 0 to 0 and 1 to 0, while node 1 contains copies from node 1 to 1 and 0 to 1. So if only dumping the logs of node 0, we can not see the copies from 0 to 1.

**Comment by eddy16112** [comment]
I have pushed changes to a new branch https://gitlab.com/StanfordLegion/legion/-/commits/subnodes, which allows people to select a subset of nodes by:
```
legion_prof.py --nodes 0,1 eight_node_run/*.log
```
It does not improve the performance of legion_prof.py because we still need to process all the log files. The only benefit is that the dumped tsv files are smaller than the whole set, so it take less time for the browser to load the trace. 
@manopapad let me know if it is what you need.

**Comment by elliottslaughter** [comment]
One way to make this more scalable would be to make it an input filter rather than an output filter. I.e., for every log message, before we process it we check the filter, and if the filter rejects the log message we don't end up processing it (and therefore it doesn't increase the size of the state).

We could apply this both to nodes and also to the trim options we already have. Currently we have to build up the entire state for both of those *before* we get to cut that state back down, but this doesn't reduce the profiler backend's peak memory usage.

**Comment by eddy16112** [comment]
> One way to make this more scalable would be to make it an input filter rather than an output filter. I.e., for every log message, before we process it we check the filter, and if the filter rejects the log message we don't end up processing it (and therefore it doesn't increase the size of the state).
> 
> We could apply this both to nodes and also to the trim options we already have. Currently we have to build up the entire state for both of those _before_ we get to cut that state back down, but this doesn't reduce the profiler backend's peak memory usage.

It is hard to create an input filter without knowing the communication pattern. For example, if we run an all to all communication on 4 nodes, even if select node 0-1, we still have to set the input filter = all nodes. We might be able to save some memory spaces by ignore `Tasks` on node 2-3.

**Comment by lightsighter** [comment]
> Would it be possible to generate output in this case, and assign the copy to an "unknown" channel or similar? I realize we may have holes in our information, but this seems like a big loss in functionality.

Finally starting to catch up. It was technically undefined behavior before. The runtime was just silently dropping the logging completely for asymmetric copies before. For example, if you logged node 0 and not node 1, then you would see copies issued by node 0, but not copies issued by node 1, and even then things could get a bit weird with operation IDs from remote notes (which I think the profiler would just ignore). I feel like the right answer here is to just have the parser read all the log files and selectively filter for things it doesn't need (e.g. if it's only doing output for a subset of nodes). We probably do want to at least have all the meta-data in the logfiles though which is why I think it is best that we got to a mode where the runtime either dumps all the profiling information or none of it. Feel free to push back if you think there is a sane way for the runtime to selectively filter what it is logging.

**Comment by eddy16112** [comment]
I implemented a prototype that takes care of `Instance` and `Copy` in the following way. I divide them into two cases: with and without full log files
1. Instance
a. without full log files
If an instance is missing, a task/copy will be displayed as `Inst: 0x0, 0x00001234`. Once we click the task, only the valid instance will be highlighted. 
b. with full log files, but pick a subset of nodes
When parsing log files, if a `task.proc_id` or `inst.mem_id` is not in the specified nodes, we do not log it into memory. The visualization is the same as Case a.
2. Copy
a. without full log files
We will lose some of the copies that are in the missing log files.
b. with full log files, but pick a subset of nodes
When parsing log files, if `copy.src_mem` and `copy.dst_mem` are not in the specified nodes, we do not log the copy into memory. Since we have all files, we do not loose any copies. 

In Case b, we can set a filter to not log data that does not belong to the specified nodes, which could save some memory. However, not all logging statement contains the node information, so for those logs, we can not ignore them.
@elliottslaughter @lightsighter @manopapad Let me know what do you think.

**Comment by manopapad** [comment]
> b. with full log files, but pick a subset of nodes

In this case I'd personally prefer the following behavior: Say `copy.src_mem.node == A` and `copy.dst_mem.node == B`. Then render the copy under the channel for node `A` if and only if `A` is in `--nodes`, regardless of whether `B` is in `--nodes`. Similarly for `B`.

**Comment by eddy16112** [comment]
I tried further to reduce the number of logs that need to be parsed and stored, when `--nodes` is specified by comparing `node_id` (currently using the number from file name, but can be modified to use the number from the log later) of a log with `--nodes`:
```
if node_id not in nodes_list:
    if log is not in exception_log_list:
        # skip the log
        continue
# start parsing the log
```
The `exception_log_list` is a list of logging statements that are required to be parsed using log files from all nodes, just because some operations could be logged in node A but executed on node B. Currently, the list contains tasks, copies and fills (they will still be filter using the method described in Case b of my last post), but I am not sure if I need to add more logging statements into the list.

**Comment by lightsighter** [comment]
> However, not all logging statement contains the node information, so for those logs, we can not ignore them.
@elliottslaughter @lightsighter @manopapad Let me know what do you think.

I think the approach that we discussed for logging the node at the beginning of each file should help us prune down which files to pay attention to based on what nodes the profiler has been asked to log. The open questions are whether we decide to ignore data relevant to a profiling node even if it was logged on a different node? And if we do, how do we do that: does the processing script have to go look for it in those other logs, or does the runtime just duplicate logging of all such things (and what are all such things)?

**Comment by eddy16112** [comment]
>  does the processing script have to go look for it in those other logs,

Actually, the problem is we do not even know which things are missing. We do have sanity checks for missing instances, but those checks will not be useful when only using subset of nodes. For operations, even if some of them are missing, it will not trigger any errors.

**Comment by lightsighter** [comment]
> For operations, even if some of them are missing, it will not trigger any errors.

Right, there can be cases where we execute runtime meta-tasks generated by an operation on a remote node from where the operation was created. If we're just profiling the remote node, then it won't have any idea what the operation is that created the meta-task. I think the current profiler just ignores this right now, although I'm not sure. That's just another instance of a kind of cross-node logging dependence.

**Comment by elliottslaughter** [comment]
I'm not entirely sure that saving logs is a win. For example, it locks us into a serial algorithm and prevents us from parallelizing the state reconstruction, which was previously something that was at least plausible to do.

What are the open questions that need to be answered at this point?

I thought we were going to try to at least measure the overheads of having the runtime do duplicate logging, so that we do not need a `--nodes` flags in the profiler and its associated complexity (though we need to make it safe to run without all log files).

**Comment by eddy16112** [comment]
> I'm not entirely sure that saving logs is a win. For example, it locks us into a serial algorithm and prevents us from parallelizing the state reconstruction, which was previously something that was at least plausible to do.

We do not changing anything about parsing logs, I do not understand why we can parallelize the state reconstruction before but can not parallelize it now. 

> What are the open questions that need to be answered at this point?

I think the question is which approach should we do? I think there could be three approaches:
1. We duplicate the logs, then hopefully we do not need to use `--nodes` flags in the python/rust parser. If we need node 0-1, Legion will only dump two files: prof_0.gz and prof_1.gz. 
pros: we save the memory and improve the parsing speed of python/rust parser.
cons: we duplicate the logs if we profile all nodes.

2. We DO NOT duplicate the logs. The python/rust parser will parse all the log files, however, we set an input filter to ignore logs that are not needed based on `--nodes` (we will have to set a rule). We also need to an output filter to only visualize nodes belong to `--nodes`.
pros: no changes is required in the Legion side
cons: 1. we need to dump all logs. 2. we need to carefully set the rules for the input filter to avoid missing logs. 

3. We DO NOT duplicate the logs, but we move the input filter from Approach 2 into Legion, so if we need node 0-1, Legion could dump more than 2 files, for example, if there are copies between 0 and 2, we will also dump copy logs into prof_2.gz. In the python/rust parser, we only need an output filter.    
pros: we do not have to dump all logs. 
cons: we need to carefully set the rules for the input filter to avoid missing logs

Currently, I am working on Approach 2, and the challenge is I do not know if I have missed any logs.

**Comment by lightsighter** [comment]
> What are the open questions that need to be answered at this point?

Right, I think we're trying to decide which of the three approaches Wei outlined above is the right way forward. The catch is that as Wei discovered, there is likely more kinds of cross-node data that might be missing than just the copy/fill kind of information. If we do go with option 2, how much of that do we need to get right and how much of it is ok to be broken.

**Comment by elliottslaughter** [comment]
The core Legion Prof loop basically looks like this. In Rust-ish pseudocode:

```rust
var files = ...; // list of files
var logs_per_file = files.map(parse); // parse all files
var state = State::new(); // start from empty state
for file_logs in logs_per_file {
  state.process(file_logs); // process logs from each file and add to state
}
```

One critical thing to understand about this is that the `map()` step is trivially parallel: we can (and do) parse all log files in parallel. The state construction is currently serial, but under the current assumptions (that each node is independent), it's not too hard to see how you could parallelize it:

```rust
var files = ...; // list of files
var logs_per_file = files.map(parse); // parse all files
var state_per_file = logs_per_file.map(process); // build a state per file
var state = state_per_file.reduce(merge); // merge to construct a final state
```

We need a way to merge states, but that seems straightforward in a world where each `State` object concerns only the operations for a single node. We need to be slightly careful about the `ProfUID` allocator, but otherwise it should just be matter of collecting the processors/memories/channels/etc. on each node and sticking them in the one data structure.

With option 1 above, I think this all continues to "just work". Option 2, depending on how it's implemented, could either make this challenging or impossible.

 1. If we implement option 2 by building the entire state and then filtering it, then I guess that works but memory usage continues to be a concern (we might not have the memory to fit the data from all nodes).
 2. If we implement option 2 by saving all the problematic log statements and processing them all the "easy" log statements have been handled, that still increases memory usage because it means we can no longer stripmine the processing. (In my second example above, the logs only need to be kept until a certain node's state has been constructed, and then we can throw the logs away.) Also, it seems more complicated because we're introducing a multi-pass structure which now requires two merges.
 3. If we implement option 2 by assuming we can process logs in order, that is sequential and will break this entirely.

Overall, it feels like it's a lot less complicated to handle this in the runtime (i.e., option 1), when we know both endpoints of a copy (or whatever operation). The profiler (without runtime support) fundamentally has to go looking through all files to find what it needs, and cannot anticipate ahead of time which logs in which nodes are relevant. Preserving the profiler's ability to use a naive, assume-each-node-is-independent reconstruction algorithm, seems like a big win as far as distributed/parallel processing of log files goes, and also for reducing memory usage.

In my view option 3 is not helpful because it does not address the case where you have already dumped logs for all nodes, and then later decide you want to render just a subset. Needing to rerun your job because you accidentally logged too much (or too little) data is going to be horrible for usability.

**Comment by eddy16112** [comment]
Currently, I implemented option 2 by not building the entire state, here is the Rust-ish pseudocode:
```
var files = ...; // list of files
var logs_per_file = files.map(parse, input_filter); // filter logs that are not used. 
var state = State::new(); // start from empty state
for file_logs in logs_per_file {
  state.process(file_logs); // process logs from each file and add to state
}
state.filter_output() // because input_filter may contains nodes that are required to be processed but not in the --nodes, we filter those nodes out for visualization
```
The challenge is how to set the input filter correctly to avoid missing logs. Currently I implemented a script to compare results with and without input filter to make sure the input filter does not lead to missing logs. 

My concern about Option 1 is that we have a lot of duplicated logs that will increase the size of log files.

**Comment by elliottslaughter** [comment]
With this version of option 2, we're going to run out of memory because for any substantial number of nodes, we're memory-limited as we scale.

On my laptop, profiling a 16-node job of Pennant on 1000 timesteps already fills all of my memory (32 GB on this machine), and 32 nodes or more forces me into virtual memory (ok but slow on macOS, deadly on Linux). Going past 32 nodes isn't really feasible without going to a machine with more memory. But in an option 1 world, I can just pick any subset of nodes and profile those, and be confident the subset of data I'm looking at is complete.

With option 1, it's also trivial to distribute the workload (with a working set that scales `O(N/M)` if I use `M` nodes to process profiles produced by an `N`-node job), and that seems to not work with option 2 (every node needs to parse the full `O(N)` data set before filtering can be applied.

Can someone measure the overhead of option 1? At least on paper, it feels like a (conservative) 2&times; overhead vs an `O(N)` overhead. I suspect the overhead in practice will be smaller than 2&times; because not everything needs to be double-logged.

**Comment by lightsighter** [comment]
> Overall, it feels like it's a lot less complicated to handle this in the runtime (i.e., option 1), when we know both endpoints of a copy (or whatever operation).

This is going to significantly degrade the quality of the captured profile compared to running without profiling, and maintaining as close a fidelity to the un-profiled timing of an application should be our first concern. Note that it's not just copies. It's every single operation that gets referenced on a remote node, which is going to incur lots of cross-node communication adding both latency and network contention to the execution. There may even be more cross-node data that will need to be communicated that we haven't thought about yet. The more we uncover and the more the runtime has to duplicate, the worse the fidelity of the profile will degrade (we're already often off by 10-20% compared to un-profiled code).

Why do we think we need to run that `map` step in the post-processing in parallel? I would much rather wait longer for the post-processing to happen in serial and have a high fidelity profile that closely resembles the timing of an unprofiled run because it's going to allow me to understand what is actually going on in my application. Seeing a low-fidelity profile faster doesn't help me.

**Comment by lightsighter** [comment]
FWIW, I'm starting to coming around to @alexaiken idea that we should just build large distributed data structures using Legion for each of the files in parallel across as many nodes as needed, and then do queries on them to find the data for the subsets of nodes that we actually need. We could even bootstrap this on top of Legate Pandas.

**Comment by eddy16112** [comment]
The legion profiler now has supported processing a subset of log files by specifying `--nodes`.

**Comment by lightsighter** [comment]
Are we good closing this issue?

**Comment by manopapad** [comment]
After @eddy16112's change, two modes are supported today: With `--nodes` only a subset of the nodes will be plotted, and only transfers between those nodes will be visualized. If we also pass `--no-filter-input` then we should also see transfers coming in/out of those nodes even though the src/dst nodes are not listed in `--nodes` (at the expense of having to process all files). So I'm closing this issue.
