### ISSUE TITLE
Realm: completion queue overflow

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1382]
I'm seeing the following error on Perlmutter at 256 nodes when trying to scale S3D: 
```
[2 - 14a0f01d0000]  400.721478 {6}{compqueue}: completion queue overflow: cq=1900020000000002 size=1024
```

**Comment by lightsighter** [comment]
What is the backtrace? Are you using frames for managing run-ahead?

**Comment by syamajala** [comment]
Here is a stack trace:
```
[172] Thread 4 (Thread 0x1484901fc000 (LWP 62633) "s3d.x"):
[172] #0  0x00001484d9a7276f in wait4 () from /lib64/libc.so.6
[172] #1  0x00001484d99e9bc7 in do_system () from /lib64/libc.so.6
[172] #2  0x00001484b9d10209 in gasneti_system_redirected () from /global/homes/s/seshu/legion_s3d_dbo/legion/language/build/lib/librealm.so.1
[172] #3  0x00001484b9d108c8 in gasneti_bt_gdb () from /global/homes/s/seshu/legion_s3d_dbo/legion/language/build/lib/librealm.so.1
[172] #4  0x00001484b9d1405c in gasneti_print_backtrace () from /global/homes/s/seshu/legion_s3d_dbo/legion/language/build/lib/librealm.so.1
[172] #5  0x00001484b94d58eb in gasneti_defaultSignalHandler () from /global/homes/s/seshu/legion_s3d_dbo/legion/language/build/lib/librealm.so.1
[172] #6  <signal handler called>
[172] #7  0x00001484d99dbcdb in raise () from /lib64/libc.so.6
[172] #8  0x00001484d99dd375 in abort () from /lib64/libc.so.6
[172] #9  0x00001484b96e00ff in Realm::CompQueueImpl::add_completed_event (this=0x147da15affc0, event=..., waiter=0x1474a438f190, work_until=...) at /global/u1/s/seshu/legion_s3d_dbo/legion/runtime/realm/event_impl.cc:3543
[172] #10 0x00001484b96d09c2 in Realm::EventTriggerNotifier::trigger_event_waiters (this=0x71b5b88, to_trigger=..., poisoned=poisoned@entry=false, trigger_until=...) at /global/u1/s/seshu/legion_s3d_dbo/legion/runtime/realm/event_impl.cc:5
43
[172] #11 0x00001484b96e2b3e in Realm::BarrierTriggerMessage::handle_message (sender=<optimized out>, args=..., data=<optimized out>, datalen=<optimized out>, work_until=...) at /global/u1/s/seshu/legion_s3d_dbo/legion/runtime/realm/runtim
e_impl.h:395
[172] #12 0x00001484b981af4d in Realm::IncomingMessageManager::do_work (this=0x8bbd640, work_until=...) at /global/u1/s/seshu/legion_s3d_dbo/legion/runtime/realm/activemsg.cc:740
[172] #13 0x00001484b96cc059 in Realm::BackgroundWorkManager::Worker::do_work (this=0x1484901e82f0, max_time_in_ns=<optimized out>, interrupt_flag=0x0) at /global/u1/s/seshu/legion_s3d_dbo/legion/runtime/realm/bgwork.cc:621
[172] #14 0x00001484b96cc881 in Realm::BackgroundWorkThread::main_loop (this=0x8d0c920) at /global/u1/s/seshu/legion_s3d_dbo/legion/runtime/realm/bgwork.cc:125
[172] #15 0x00001484b97b2e9f in Realm::KernelThread::pthread_entry (data=0x514a1d0) at /global/u1/s/seshu/legion_s3d_dbo/legion/runtime/realm/threads.cc:781
[172] #16 0x00001484dd8896ea in start_thread () from /lib64/libpthread.so.0
[172] #17 0x00001484d9aa8a8f in clone () from /lib64/libc.so.6
```

Yes, we are using frames and calling `runtime_complete_frame` at the end of a timestep.

**Comment by lightsighter** [comment]
Pull and try again.
