### ISSUE TITLE
Legion: crash in CDUGKS

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1390]
With no application changes, a version of CDUGKS that worked with an October 2022 version of `control_repliation` (ac7a33fb8c69226599518ad1f75b205e8adc01f6) is now crashing with the latest version (cba415a857c2586b2ad2f4848d6d1cd75de7df00).

I am attaching a `DEBUG=1` backtrace from an 8-node run that crashes. I also got it to crash on 2 nodes, but for some reason that job did not produce a backtrace. These runs are on Piz Daint.

[slurm-44507823.out.txt](https://github.com/StanfordLegion/legion/files/10543259/slurm-44507823.out.txt)

The interesting thread appears to be:

```
[7] Thread 5 (Thread 0x155555523880 (LWP 18027) "cdugks_exe"):
[7] #0  0x00001555485b8157 in waitpid () from /lib64/libc.so.6
[7] #1  0x00001555485356af in do_system () from /lib64/libc.so.6
[7] #2  0x0000155551c7cda6 in gasneti_bt_gdb () from /users/eslaught/cdugks-legion-2022-10/language/run_cdugks_debug_oom_debug/libregent.so
[7] #3  0x0000155551c804ef in gasneti_print_backtrace () from /users/eslaught/cdugks-legion-2022-10/language/run_cdugks_debug_oom_debug/libregent.so
[7] #4  0x000015554cdc252c in gasneti_defaultSignalHandler () from /users/eslaught/cdugks-legion-2022-10/language/run_cdugks_debug_oom_debug/libregent.so
[7] #5  <signal handler called>
[7] #6  0x000015554d242d90 in std::_Rb_tree<Legion::Internal::LogicalView*, std::pair<Legion::Internal::LogicalView* const, Legion::Internal::FieldMaskSet<Legion::Internal::IndexSpaceExpression, (Legion::Internal::AllocationType)108, false> >, std::_Select1st<std::pair<Legion::Internal::LogicalView* const, Legion::Internal::FieldMaskSet<Legion::Internal::IndexSpaceExpression, (Legion::Internal::AllocationType)108, false> > >, std::less<Legion::Internal::LogicalView*>, Legion::Internal::LegionAllocator<std::pair<Legion::Internal::LogicalView* const, Legion::Internal::FieldMaskSet<Legion::Internal::IndexSpaceExpression, (Legion::Internal::AllocationType)108, false> >, (Legion::Internal::AllocationType)108> >::begin (this=0x20) at /opt/gcc/10.3.0/snos/include/g++/bits/stl_tree.h:1007
[7] #7  0x000015554d23014a in std::map<Legion::Internal::LogicalView*, Legion::Internal::FieldMaskSet<Legion::Internal::IndexSpaceExpression, (Legion::Internal::AllocationType)108, false>, std::less<Legion::Internal::LogicalView*>, Legion::Internal::LegionAllocator<std::pair<Legion::Internal::LogicalView* const, Legion::Internal::FieldMaskSet<Legion::Internal::IndexSpaceExpression, (Legion::Internal::AllocationType)108, false> >, (Legion::Internal::AllocationType)108> >::begin (this=0x20) at /opt/gcc/10.3.0/snos/include/g++/bits/stl_map.h:366
[7] #8  0x000015554d209126 in Legion::Internal::TraceViewSet::unpack_references (this=0x0) at /users/eslaught/cdugks-legion-2022-10/runtime/legion/legion_trace.cc:3194
[7] #9  0x000015554d38c9cb in Legion::Internal::EquivalenceSet::apply_state (this=0x155241da0120, valid_updates=..., initialized_updates=..., reduction_updates=..., restricted_updates=..., released_updates=..., precondition_updates=0x0, anticondition_updates=0x0, postcondition_updates=0x1552504afbc0, read_only_guard_updates=0x15524fe24120, reduction_fill_guard_updates=0x15524feac3a0, applied_events=..., needs_lock=false, forward_to_owner=false, unpack_references=true) at /users/eslaught/cdugks-legion-2022-10/runtime/legion/legion_analysis.cc:16938
[7] #10 0x000015554d38b592 in Legion::Internal::EquivalenceSet::apply_state (this=0x155241da0120, valid_updates=..., initialized_updates=..., reduction_updates=..., restricted_updates=..., released_updates=..., precondition_updates=0x0, anticondition_updates=0x0, postcondition_updates=0x1552504afbc0, read_only_guard_updates=0x15524fe24120, reduction_fill_guard_updates=0x15524feac3a0, applied_events=..., needs_lock=true, forward_to_owner=false, unpack_references=true) at /users/eslaught/cdugks-legion-2022-10/runtime/legion/legion_analysis.cc:16750
[7] #11 0x000015554d387e07 in Legion::Internal::EquivalenceSet::handle_apply_state (args=0x155219481860) at /users/eslaught/cdugks-legion-2022-10/runtime/legion/legion_analysis.cc:16129
[7] #12 0x000015554d5e3102 in Legion::Internal::Runtime::legion_runtime_task (args=0x155219481860, arglen=108, userdata=0xa54f90, userlen=8, p=...) at /users/eslaught/cdugks-legion-2022-10/runtime/legion/runtime.cc:31825
[7] #13 0x000015554f644ef0 in Realm::LocalTaskProcessor::execute_task (this=0x85ccb0, func_id=4, task_args=...) at /users/eslaught/cdugks-legion-2022-10/runtime/realm/proc_impl.cc:1135
[7] #14 0x000015554f1cf784 in Realm::Task::execute_on_processor (this=0x1552504a9420, p=...) at /users/eslaught/cdugks-legion-2022-10/runtime/realm/tasks.cc:302
[7] #15 0x000015554f1d42c8 in Realm::UserThreadTaskScheduler::execute_task (this=0x85cec0, task=0x1552504a9420) at /users/eslaught/cdugks-legion-2022-10/runtime/realm/tasks.cc:1632
[7] #16 0x000015554f1d2375 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x85cec0) at /users/eslaught/cdugks-legion-2022-10/runtime/realm/tasks.cc:1105
[7] #17 0x000015554f1da1aa in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x85cec0) at /users/eslaught/cdugks-legion-2022-10/runtime/realm/threads.inl:97
[7] #18 0x000015554f1adbff in Realm::UserThread::uthread_entry () at /users/eslaught/cdugks-legion-2022-10/runtime/realm/threads.cc:1355
[7] #19 0x000015554853dbe0 in ?? () from /lib64/libc.so.6
[7] #20 0x0000000000000000 in ?? ()
```

What should I do next?

**Comment by lightsighter** [comment]
Copy-paste bug:

https://gitlab.com/StanfordLegion/legion/-/commit/044e2f7aaca309e599fd81a348f8ddf3691d1163

Pull and try again.

**Comment by elliottslaughter** [comment]
Fixed. Thanks!
