### ISSUE TITLE
Construct FutureMap with empty Futures

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1402]
I'm trying to use `runtime->construct_future_map` to construct a `FutureMap` which contains empty futures. It may seem silly, but I want my code to be general, and I'd prefer not to add special cases for empty futures.

When I include an entry with `NULL` and `0` for pointer and size, respectively, it seem this code has a problem.

```
multiple_partitions: /resilience/legion/runtime/legion/runtime.cc:2575: Legion::Internal::FutureInstance::FutureInstance(const void*, size_t, Legion::Internal::ApEvent, Legion::Internal::Runtime*, bool, bool, bool, Legion::Internal::PhysicalInstance, Legion::Processor, Legion::Internal::RtEvent, Legion::Internal::ApUserEvent): Assertion `size > 0' failed.
```

Here's the interesting part of the backtrace:

```
#7  0x00007fcebbf907ad in Legion::Internal::FutureInstance::FutureInstance (this=0x7fce8400db30, d=0x7fce84002c10, s=0, r=..., 
    rt=0x56194f7aa050, eager=false, external=true, own=true, inst=..., p=..., use=..., remote_read=...)
    at /resilience/legion/runtime/legion/runtime.cc:2575
#8  0x00007fcebbf941d6 in Legion::Internal::FutureInstance::create_local (value=0x7fce84002c10, size=0, own=true, runtime=0x56194f7aa050)
    at /resilience/legion/runtime/legion/runtime.cc:3316
#9  0x00007fcebbf8bc7f in Legion::Internal::FutureImpl::set_local (this=0x7fce8400c5b0, value=0x0, size=0, own=false)
    at /resilience/legion/runtime/legion/runtime.cc:1474
#10 0x00007fcebb9cc358 in Legion::Internal::InnerContext::construct_future_map (this=0x7fce8c0019d0, space=..., 
    data=std::map with 4 elements = {...}, provenance=0x0, collective=false, sid=0, implicit=false, internal=false)
    at /resilience/legion/runtime/legion/legion_context.cc:6606
#11 0x00007fcebbae5b92 in Legion::Runtime::construct_future_map (this=0x56194f67a1d0, ctx=0x7fce8c0019d0, domain=..., 
    data=std::map with 4 elements = {...}, collective=false, sid=0, implicit=false, prov=0x0)
    at /resilience/legion/runtime/legion/legion.cc:6330
#12 0x000056194f553096 in ResilientLegion::FutureMapSerializer::inflate (this=0x7fce8400eaf0, runtime=0x7fce90ea7760, ctx=0x7fce8c0019d0)
    at /resilience/src/resilience/resilience.cc:41
#13 0x000056194f55b544 in ResilientLegion::Runtime::enable_checkpointing (this=0x7fce90ea7760, ctx=0x7fce8c0019d0)
    at /resilience/src/resilience/resilience.cc:1046
```

As my debugging session shows, some of the entries in the `data` map contain `NULL`/`0`:

```
(gdb) p is
$1 = {id = 1, tid = 1, type_tag = 258}
(gdb) p domain
$2 = {domain = {dim = 1, rects = std::vector of length 1, capacity 1 = {{lo = {p = {dim = 1, point_data = {0, 0, 0}}}, hi = {p = {dim = 1, 
            point_data = {3, 0, 0}}}}}}}
(gdb) p data
$3 = std::map with 4 elements = {[{dim = 1, point_data = {0, 0, 
      0}}] = {<Legion::Unserializable<Legion::UntypedBuffer>> = {<No data fields>}, args = 0x0, arglen = 0}, [{dim = 1, point_data = {1, 
      0, 0}}] = {<Legion::Unserializable<Legion::UntypedBuffer>> = {<No data fields>}, args = 0x0, arglen = 0}, [{dim = 1, point_data = {
      2, 0, 0}}] = {<Legion::Unserializable<Legion::UntypedBuffer>> = {<No data fields>}, args = 0x0, arglen = 0}, [{dim = 1, 
    point_data = {3, 0, 0}}] = {<Legion::Unserializable<Legion::UntypedBuffer>> = {<No data fields>}, args = 0x0, arglen = 0}}
```

I'm on commit 61b82cc43251d0e5e3727d44318b8af2bec2b7e2 of `control_replication`.

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by elliottslaughter** [comment]
Fixed, thanks!
