### ISSUE TITLE
Crash in SNAP on multiple nodes

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1416]
This is the ctrlrepl branch of SNAP, so no checkpointing here.

Command line:

```
mpirun -n 2 -oversubscribe -x REALM_FREEZE_ON_ERROR=1 $PWD/examples/snap/snap $PWD/../examples/snap/input/mms.in -lg:safe_ctrlrepl 1
```

Failure:

```
snap: /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12137: Legion::Internal::AllGatherCollective<<anonymous> >::~AllGatherCollective() [with bool INORDER = false]: Assertion `sent_stages[idx]' failed.
```

I have frozen processes if you want to look:

```
Process 3016417 on node g0004.stanford.edu is frozen!
Process 3016416 on node g0004.stanford.edu is frozen!
```

Backtrace:

```
(gdb) bt
#0  0x00007fa0d956223f in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x56125c596920, rem=rem@entry=0x56125c596920)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007fa0d9567ec7 in __GI___nanosleep (requested_time=requested_time@entry=0x56125c596920, remaining=remaining@entry=0x56125c596920) at nanosleep.c:27
#2  0x00007fa0d9567dfe in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#3  0x00007fa0da3c0afd in Realm::realm_freeze (signal=6) at /scratch2/eslaught/resilience/legion/runtime/realm/runtime_impl.cc:183
#4  <signal handler called>
#5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  0x00007fa0d94a7859 in __GI_abort () at abort.c:79
#7  0x00007fa0d94a7729 in __assert_fail_base (fmt=0x7fa0d963d588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7fa0dd86be68 "sent_stages[idx]", 
    file=0x7fa0dd8618f8 "/scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc", line=12137, function=<optimized out>) at assert.c:92
#8  0x00007fa0d94b8fd6 in __GI___assert_fail (assertion=0x7fa0dd86be68 "sent_stages[idx]", file=0x7fa0dd8618f8 "/scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc", line=12137, 
    function=0x7fa0dd86bde8 "Legion::Internal::AllGatherCollective<<anonymous> >::~AllGatherCollective() [with bool INORDER = false]") at assert.c:101
#9  0x00007fa0dcee9bf9 in Legion::Internal::AllGatherCollective<false>::~AllGatherCollective (this=0x7fa0702503b0, __in_chrg=<optimized out>)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12137
#10 0x00007fa0dced8ddf in Legion::Internal::FutureAllReduceCollective::~FutureAllReduceCollective (this=0x7fa0702503b0, __in_chrg=<optimized out>)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12547
#11 0x00007fa0dced8e04 in Legion::Internal::FutureAllReduceCollective::~FutureAllReduceCollective (this=0x7fa0702503b0, __in_chrg=<optimized out>)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12552
#12 0x00007fa0dcea8ee2 in Legion::Internal::ReplIndexTask::deactivate (this=0x7fa07033dc20, freeop=true) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:887
#13 0x00007fa0dcd5adf3 in Legion::Internal::Operation::commit_operation (this=0x7fa07033ddd0, do_deactivate=true, wait_on=...) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_ops.cc:2226
#14 0x00007fa0dcf7cf5c in Legion::Internal::IndexTask::trigger_task_commit (this=0x7fa07033dc20) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_tasks.cc:9782
#15 0x00007fa0dcf58be9 in Legion::Internal::TaskOp::trigger_children_committed (this=0x7fa07033dc20) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_tasks.cc:1999
#16 0x00007fa0dcf7b601 in Legion::Internal::IndexTask::resolve_false (this=0x7fa07033dc20, speculated=false, launched=false) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_tasks.cc:9427
#17 0x00007fa0dceab61a in Legion::Internal::ReplIndexTask::resolve_false (this=0x7fa07033dc20, speculated=false, launched=false)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:1418
#18 0x00007fa0dd3773f7 in Legion::Internal::Predicated<Legion::Internal::ReplIndexTask>::trigger_ready (this=0x7fa07033dc20) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_ops.inl:271
#19 0x00007fa0dcc0a768 in Legion::Internal::InnerContext::process_ready_queue (this=0x7fa06c079ec0) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_context.cc:8159
#20 0x00007fa0dcc1a302 in Legion::Internal::InnerContext::handle_ready_queue (args=0x7fa074023f20) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_context.cc:11728
#21 0x00007fa0dd22d804 in Legion::Internal::Runtime::legion_runtime_task (args=0x7fa074023f20, arglen=12, userdata=0x56125c582860, userlen=8, p=...)
    at /scratch2/eslaught/resilience/legion/runtime/legion/runtime.cc:31661
#22 0x00007fa0da397ba4 in Realm::LocalTaskProcessor::execute_task (this=0x56125c0f2390, func_id=4, task_args=...) at /scratch2/eslaught/resilience/legion/runtime/realm/proc_impl.cc:1135
#23 0x00007fa0da4102d1 in Realm::Task::execute_on_processor (this=0x7fa074023da0, p=...) at /scratch2/eslaught/resilience/legion/runtime/realm/tasks.cc:302 
#24 0x00007fa0da4154d2 in Realm::UserThreadTaskScheduler::execute_task (this=0x56125c429d00, task=0x7fa074023da0) at /scratch2/eslaught/resilience/legion/runtime/realm/tasks.cc:1632
#25 0x00007fa0da413275 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x56125c429d00) at /scratch2/eslaught/resilience/legion/runtime/realm/tasks.cc:1105
#26 0x00007fa0da41bd64 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x56125c429d00)
    at /scratch2/eslaught/resilience/legion/runtime/realm/threads.inl:97 
#27 0x00007fa0da42abcc in Realm::UserThread::uthread_entry () at /scratch2/eslaught/resilience/legion/runtime/realm/threads.cc:1355
#28 0x00007fa0d94e04e0 in ?? () at ../sysdeps/unix/sysv/linux/x86_64/__start_context.S:91 from /lib/x86_64-linux-gnu/libc.so.6
#29 0x0000000000000000 in ?? ()
```

Legion version for this is 3a37d58ce612ef48d969f5acbccdd1db54310595.

Message me on Zulip before rebuilding anything since I have multiple active reproducers at the moment.

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by elliottslaughter** [comment]
Hm, I'm on 68bffbf6ba3e508c85fcf14f2ba3b12c0ee5bb4a and am pretty sure I rebuilt, but it doesn't seem to be fixed:

```
snap_base: /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12142: Legion::Internal::AllGatherCollective<<anonymous> >::~AllGatherCollective() [with bool INORDER = false]: Assertion `sent_stages[idx]' failed.
```

```
(gdb) bt
#0  0x00007f3c256c923f in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x55a36afb2920, rem=rem@entry=0x55a36afb2920)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007f3c256ceec7 in __GI___nanosleep (requested_time=requested_time@entry=0x55a36afb2920, remaining=remaining@entry=0x55a36afb2920) at nanosleep.c:27
#2  0x00007f3c256cedfe in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#3  0x00007f3c26527afd in Realm::realm_freeze (signal=6) at /scratch2/eslaught/resilience/legion/runtime/realm/runtime_impl.cc:183
#4  <signal handler called>
#5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  0x00007f3c2560e859 in __GI_abort () at abort.c:79
#7  0x00007f3c2560e729 in __assert_fail_base (fmt=0x7f3c257a4588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f3c299d2e68 "sent_stages[idx]", 
    file=0x7f3c299c88f8 "/scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc", line=12142, function=<optimized out>) at assert.c:92
#8  0x00007f3c2561ffd6 in __GI___assert_fail (assertion=0x7f3c299d2e68 "sent_stages[idx]", file=0x7f3c299c88f8 "/scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc", line=12142, 
    function=0x7f3c299d2de8 "Legion::Internal::AllGatherCollective<<anonymous> >::~AllGatherCollective() [with bool INORDER = false]") at assert.c:101
#9  0x00007f3c29050c57 in Legion::Internal::AllGatherCollective<false>::~AllGatherCollective (this=0x7f3bb8275580, __in_chrg=<optimized out>)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12142
#10 0x00007f3c2903fe3d in Legion::Internal::FutureAllReduceCollective::~FutureAllReduceCollective (this=0x7f3bb8275580, __in_chrg=<optimized out>)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12552
#11 0x00007f3c2903fe62 in Legion::Internal::FutureAllReduceCollective::~FutureAllReduceCollective (this=0x7f3bb8275580, __in_chrg=<optimized out>)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12557
#12 0x00007f3c2901263e in Legion::Internal::ReplIndexTask::resolve_false (this=0x7f3bb833cf90, speculated=false, launched=false)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:1418
#13 0x00007f3c294de455 in Legion::Internal::Predicated<Legion::Internal::ReplIndexTask>::trigger_ready (this=0x7f3bb833cf90) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_ops.inl:271
#14 0x00007f3c28d71762 in Legion::Internal::InnerContext::process_ready_queue (this=0x7f3bc0078f80) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_context.cc:8159
#15 0x00007f3c28d812fc in Legion::Internal::InnerContext::handle_ready_queue (args=0x7f3bc8051980) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_context.cc:11728
#16 0x00007f3c29394862 in Legion::Internal::Runtime::legion_runtime_task (args=0x7f3bc8051980, arglen=12, userdata=0x55a36af9ed90, userlen=8, p=...)
    at /scratch2/eslaught/resilience/legion/runtime/legion/runtime.cc:31661
#17 0x00007f3c264feba4 in Realm::LocalTaskProcessor::execute_task (this=0x55a36ab13390, func_id=4, task_args=...) at /scratch2/eslaught/resilience/legion/runtime/realm/proc_impl.cc:1135
#18 0x00007f3c265772d1 in Realm::Task::execute_on_processor (this=0x7f3bc8051800, p=...) at /scratch2/eslaught/resilience/legion/runtime/realm/tasks.cc:302 
#19 0x00007f3c2657c4d2 in Realm::UserThreadTaskScheduler::execute_task (this=0x55a36ae4a990, task=0x7f3bc8051800) at /scratch2/eslaught/resilience/legion/runtime/realm/tasks.cc:1632
#20 0x00007f3c2657a275 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x55a36ae4a990) at /scratch2/eslaught/resilience/legion/runtime/realm/tasks.cc:1105
#21 0x00007f3c26582d64 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x55a36ae4a990)
    at /scratch2/eslaught/resilience/legion/runtime/realm/threads.inl:97 
#22 0x00007f3c26591bcc in Realm::UserThread::uthread_entry () at /scratch2/eslaught/resilience/legion/runtime/realm/threads.cc:1355
#23 0x00007f3c256474e0 in ?? () at ../sysdeps/unix/sysv/linux/x86_64/__start_context.S:91 from /lib/x86_64-linux-gnu/libc.so.6
#24 0x0000000000000000 in ?? ()
```

Processes:

```
Process 3022266 on node g0004.stanford.edu is frozen!
Process 3022265 on node g0004.stanford.edu is frozen!
```

**Comment by lightsighter** [comment]
Copy-paste bug, try again.

**Comment by elliottslaughter** [comment]
Now failing in:

```
snap_base: /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11938: virtual Legion::Internal::GatherCollective::~GatherCollective(): Assertion `done_event.has_triggered()' failed.
Legion process received signal 6: Aborted
```

Backtrace:

```
(gdb) bt
#0  0x00007fe9c606823f in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x56552e3ac920, rem=rem@entry=0x56552e3ac920)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007fe9c606dec7 in __GI___nanosleep (requested_time=requested_time@entry=0x56552e3ac920, remaining=remaining@entry=0x56552e3ac920) at nanosleep.c:27
#2  0x00007fe9c606ddfe in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#3  0x00007fe9c6ec6afd in Realm::realm_freeze (signal=6) at /scratch2/eslaught/resilience/legion/runtime/realm/runtime_impl.cc:183
#4  <signal handler called>
#5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  0x00007fe9c5fad859 in __GI_abort () at abort.c:79
#7  0x00007fe9c5fad729 in __assert_fail_base (fmt=0x7fe9c6143588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7fe9ca371c80 "done_event.has_triggered()", 
    file=0x7fe9ca3678f8 "/scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc", line=11938, function=<optimized out>) at assert.c:92
#8  0x00007fe9c5fbefd6 in __GI___assert_fail (assertion=0x7fe9ca371c80 "done_event.has_triggered()", file=0x7fe9ca3678f8 "/scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc", 
    line=11938, function=0x7fe9ca371c40 "virtual Legion::Internal::GatherCollective::~GatherCollective()") at assert.c:101
#9  0x00007fe9c99de4bb in Legion::Internal::GatherCollective::~GatherCollective (this=0x7fe96097b340, __in_chrg=<optimized out>)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11938
#10 0x00007fe9c99eb402 in Legion::Internal::CollectiveViewRendezvous::~CollectiveViewRendezvous (this=0x7fe96097b340, __in_chrg=<optimized out>)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:16241
#11 0x00007fe9c99eb422 in Legion::Internal::CollectiveViewRendezvous::~CollectiveViewRendezvous (this=0x7fe96097b340, __in_chrg=<optimized out>)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:16244
#12 0x00007fe9c99f5451 in Legion::Internal::ReplCollectiveViewCreator<Legion::Internal::IndexTask>::deactivate (this=0x7fe958300260, freeop=false)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:407
#13 0x00007fe9c99aee7e in Legion::Internal::ReplIndexTask::deactivate (this=0x7fe958300260, freeop=true) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:883
#14 0x00007fe9c9860ded in Legion::Internal::Operation::commit_operation (this=0x7fe958300410, do_deactivate=true, wait_on=...) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_ops.cc:2226
#15 0x00007fe9c9a82fa2 in Legion::Internal::IndexTask::trigger_task_commit (this=0x7fe958300260) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_tasks.cc:9782
#16 0x00007fe9c9a5ec2f in Legion::Internal::TaskOp::trigger_children_committed (this=0x7fe958300260) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_tasks.cc:1999
#17 0x00007fe9c9a81647 in Legion::Internal::IndexTask::resolve_false (this=0x7fe958300260, speculated=false, launched=false) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_tasks.cc:9427
#18 0x00007fe9c99b165f in Legion::Internal::ReplIndexTask::resolve_false (this=0x7fe958300260, speculated=false, launched=false)
    at /scratch2/eslaught/resilience/legion/runtime/legion/legion_replication.cc:1423
#19 0x00007fe9c9e7d43d in Legion::Internal::Predicated<Legion::Internal::ReplIndexTask>::trigger_ready (this=0x7fe958300260) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_ops.inl:271
#20 0x00007fe9c9710762 in Legion::Internal::InnerContext::process_ready_queue (this=0x7fe960078f80) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_context.cc:8159
#21 0x00007fe9c97202fc in Legion::Internal::InnerContext::handle_ready_queue (args=0x7fe968103950) at /scratch2/eslaught/resilience/legion/runtime/legion/legion_context.cc:11728
#22 0x00007fe9c9d3384a in Legion::Internal::Runtime::legion_runtime_task (args=0x7fe968103950, arglen=12, userdata=0x56552e398d90, userlen=8, p=...)
    at /scratch2/eslaught/resilience/legion/runtime/legion/runtime.cc:31661
#23 0x00007fe9c6e9dba4 in Realm::LocalTaskProcessor::execute_task (this=0x56552df0d390, func_id=4, task_args=...) at /scratch2/eslaught/resilience/legion/runtime/realm/proc_impl.cc:1135
#24 0x00007fe9c6f162d1 in Realm::Task::execute_on_processor (this=0x7fe9681037d0, p=...) at /scratch2/eslaught/resilience/legion/runtime/realm/tasks.cc:302
#25 0x00007fe9c6f1b4d2 in Realm::UserThreadTaskScheduler::execute_task (this=0x56552e244990, task=0x7fe9681037d0) at /scratch2/eslaught/resilience/legion/runtime/realm/tasks.cc:1632
#26 0x00007fe9c6f19275 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x56552e244990) at /scratch2/eslaught/resilience/legion/runtime/realm/tasks.cc:1105
#27 0x00007fe9c6f21d64 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x56552e244990)
    at /scratch2/eslaught/resilience/legion/runtime/realm/threads.inl:97
#28 0x00007fe9c6f30bcc in Realm::UserThread::uthread_entry () at /scratch2/eslaught/resilience/legion/runtime/realm/threads.cc:1355
#29 0x00007fe9c5fe64e0 in ?? () at ../sysdeps/unix/sysv/linux/x86_64/__start_context.S:91 from /lib/x86_64-linux-gnu/libc.so.6
#30 0x0000000000000000 in ?? ()
```

Processes:

```
Process 3030013 on node g0004.stanford.edu is frozen!
```

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by elliottslaughter** [comment]
Fixed, thanks!
