### ISSUE TITLE
Legion Spy crash in checkpointed C++ Pennant

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1422]
The log attached to this issue generates the following crash in Legion Spy:

```
$ python3 legion/tools/legion_spy.py -lpa spy_0.log
Traceback (most recent call last):
  File "/resilience/build/../legion/tools/legion_spy.py", line 14462, in <module>
    main(temp_dir)
  File "/resilience/build/../legion/tools/legion_spy.py", line 14334, in main
    total_matches += state.parse_log_file(file_name)
  File "/resilience/build/../legion/tools/legion_spy.py", line 12957, in parse_log_file
    if parse_legion_spy_line(line, self):
  File "/resilience/build/../legion/tools/legion_spy.py", line 12095, in parse_legion_spy_line
    op.add_requirement(requirement)
  File "/resilience/build/../legion/tools/legion_spy.py", line 6432, in add_requirement
    assert requirement.index not in self.reqs
AssertionError
```

I cannot reproduce this on Sapling, so I need to run locally to generate the logs.

Log file: [spy_0.log](https://github.com/StanfordLegion/legion/files/10901130/spy_0.log)

Legion is control_replication at 5f8da30e8066ca016377ead59c2533b31bdd4510

Note to self: command to generate:

```
$PWD/examples/pennant/pennant -n 4 -f $PWD/../examples/pennant/test/sedovsmall/sedovsmall.pnt -lg:inorder -checkpoint:replay 4 -logfile spy_%.log
```

**Comment by elliottslaughter** [comment]
I rebuilt and regenerated the spy logs. Now it crashes with:

```
Traceback (most recent call last):
  File "/resilience/build/../legion/tools/legion_spy.py", line 14462, in <module>
    main(temp_dir)
  File "/resilience/build/../legion/tools/legion_spy.py", line 14340, in main
    state.post_parse(simplify_graphs, physical_checks or event_graphs)
  File "/resilience/build/../legion/tools/legion_spy.py", line 13061, in post_parse
    if op.is_interfering_index_space_launch():
  File "/resilience/build/../legion/tools/legion_spy.py", line 6991, in is_interfering_index_space_launch
    for req in itervalues(point.reqs):
  File "/resilience/build/../legion/tools/legion_spy.py", line 151, in itervalues
    return obj.values() if sys.version_info > (3,) else obj.viewvalues()
AttributeError: 'NoneType' object has no attribute 'values'
```

New logs: [spy_0.log](https://github.com/StanfordLegion/legion/files/10903649/spy_0.log)

**Comment by lightsighter** [comment]
Try again.

**Comment by elliottslaughter** [comment]
Works now. Thanks.
