### ISSUE TITLE
Freeze in checkpointed C++ Circuit

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1428]
I appear to be seeing a new freeze, I believe since the merge of `optdistcollect`.

Note that I cleaned up my code so that `-lg:safe_ctrlrepl 2` now passes:

Command:

```
$ mpirun -n 2 -oversubscribe -bind-to socket -x REALM_FREEZE_ON_ERROR=1 ./examples/circuit/circuit -lg:eager_alloc_percentage 10 -lg:safe_ctrlrepl 2 -ll:force_kthreads -level legion_spy=4
```

Processes:

```
3837547 pts/0    00:01:14 circuit
3837548 pts/0    00:01:14 circuit
```

One interesting thread I see in the backtrace is:

```
#4  0x00007f740c98fb50 in Realm::KernelThreadTaskScheduler::worker_sleep (this=0x5574c8629e90, switch_to=0x7f739c000ba0) at /scratch2/eslaught/resilience2/legion/runtime/realm/tasks.cc:1414
#5  0x00007f740c98d83f in Realm::ThreadedTaskScheduler::thread_blocking (this=0x5574c8629e90, thread=0x5574c86846a0) at /scratch2/eslaught/resilience2/legion/runtime/realm/tasks.cc:896
#6  0x00007f740c81014e in Realm::Thread::wait_for_condition<Realm::EventTriggeredCondition> (cond=..., poisoned=@0x7f740065339f: false) at /scratch2/eslaught/resilience2/legion/runtime/realm/threads.inl:218
#7  0x00007f740c7fdcb8 in Realm::Event::wait_faultaware (this=0x7f7400653690, poisoned=@0x7f740065339f: false) at /scratch2/eslaught/resilience2/legion/runtime/realm/event_impl.cc:254
#8  0x00007f740c7fd868 in Realm::Event::wait (this=0x7f7400653690) at /scratch2/eslaught/resilience2/legion/runtime/realm/event_impl.cc:206
#9  0x00005574c68ce868 in Legion::Internal::LgEvent::wait (this=0x7f7400653690) at /scratch2/eslaught/resilience2/legion/install/include/legion/legion_types.h:2942
#10 0x00007f740f736d30 in Legion::Internal::FutureImpl::get_buffer (this=0x7f73a4096b40, memory=..., extent_in_bytes=0x7f7400656858, check_extent=true, silence_warnings=false, warning_string=0x0) at /scratch2/eslaught/resilience2/legion/runtime/legion/runtime.cc:828
#11 0x00007f740f736c60 in Legion::Internal::FutureImpl::get_buffer (this=0x7f73a4096b40, proc=..., memkind=Realm::Memory::SYSTEM_MEM, extent_in_bytes=0x7f7400656858, check_extent=true, silence_warnings=false, warning_string=0x0) at /scratch2/eslaught/resilience2/legion/runtime/legion/runtime.cc:817
#12 0x00007f740f28b871 in Legion::Future::get_buffer (this=0x7f7400656a38, memory=Realm::Memory::SYSTEM_MEM, extent_in_bytes=0x7f7400656858, check_size=true, silence_warnings=false, warning_string=0x0) at /scratch2/eslaught/resilience2/legion/runtime/legion/legion.cc:2436
#13 0x00005574c68c4451 in Legion::LegionSerialization::StructHandler<long long, false>::unpack (f=..., silence_warnings=false, warning_string=0x0) at /scratch2/eslaught/resilience2/legion/install/include/legion/legion.inl:235
#14 0x00005574c68c017b in Legion::LegionSerialization::unpack<long long> (f=..., silence_warnings=false, warning_string=0x0) at /scratch2/eslaught/resilience2/legion/install/include/legion/legion.inl:260
#15 0x00005574c68bbef5 in Legion::Future::get_result<long long> (this=0x7f7400656a38, silence_warnings=false, warning_string=0x0) at /scratch2/eslaught/resilience2/legion/install/include/legion/legion.inl:18594
#16 0x00005574c68b84a7 in ResilientLegion::Future::get_result<long long> (this=0x7f7400656a30, silence_warnings=false, warning_string=0x0) at /scratch2/eslaught/resilience2/src/resilience/future.inl:93
#17 0x00005574c68b1e81 in top_level_task (task=0x7f739c003670, regions=std::vector of length 0, capacity 0, ctx=0x7f739c018010, runtime=0x7f7400658390) at /scratch2/eslaught/resilience2/examples/circuit/circuit.cc:154
#18 0x00005574c68bc7c0 in ResilientLegion::Runtime::task_wrapper_void<&(top_level_task(Legion::Task const*, std::vector<Legion::PhysicalRegion, std::allocator<Legion::PhysicalRegion> > const&, Legion::Internal::TaskContext*, ResilientLegion::Runtime*))> (task=0x7f739c003670, regions=std::vector of length 0, capacity 0, ctx=0x7f739c018010, runtime_=0x5574c86225e0) at /scratch2/eslaught/resilience2/src/resilience/resilience.inl:549
#19 0x00005574c68c0f84 in Legion::LegionTaskWrapper::legion_task_wrapper<&ResilientLegion::Runtime::task_wrapper_void<&(top_level_task(Legion::Task const*, std::vector<Legion::PhysicalRegion, std::allocator<Legion::PhysicalRegion> > const&, Legion::Internal::TaskContext*, ResilientLegion::Runtime*))> > (args=0x7f739c0010e0, arglen=8, userdata=0x0, userlen=0, p=...) at /scratch2/eslaught/resilience2/legion/install/include/legion/legion.inl:20396
#20 0x00007f740c912fca in Realm::LocalTaskProcessor::execute_task (this=0x5574c862bc50, func_id=11, task_args=...) at /scratch2/eslaught/resilience2/legion/runtime/realm/proc_impl.cc:1135
#21 0x00007f740c98b6f7 in Realm::Task::execute_on_processor (this=0x7f739c000f60, p=...) at /scratch2/eslaught/resilience2/legion/runtime/realm/tasks.cc:302
```

Command to reproduce if you lose the process:

```
srun -n 1 -N 1 -c 40 -p gpu --exclusive --pty bash --login
cd /scratch2/eslaught/resilience2/build
mpirun -n 2 -oversubscribe -bind-to socket -x REALM_FREEZE_ON_ERROR=1 ./examples/circuit/circuit -lg:eager_alloc_percentage 10 -lg:safe_ctrlrepl 2 -ll:force_kthreads -level legion_spy=4
```

(It's a Legion Spy build, but I have the logger turned off to reduce spew.)

Feel free to rebuild if you want:

```
srun -n 1 -N 1 -c 40 -p gpu --exclusive --pty bash --login
cd /scratch2/eslaught/resilience2/legion/build
make install -j20
cd /scratch2/eslaught/resilience2/build
make clean && make -j20
```

**Comment by lightsighter** [comment]
This was completely unrelated to optimization of the references for distributed collectables. Pull and try again.

**Comment by elliottslaughter** [comment]
Fixed, thanks!
