### ISSUE TITLE
Crash in checkpointed Regent Circuit at 128 nodes

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1433]
I'm seeing a non-deterministic crash in checkpointed Regent Circuit at 128 nodes. This happens in debug mode with about 20% probability. Here are some sample backtraces:

## Run 1

```
circuit.checkpoint: /users/eslaught/resilience/legion/runtime/legion/runtime.cc:20637: Legion::Internal::MessageManager* Legion::Internal::Runtime::find_messenger(Legion::AddressSpaceID): Assertion `sid < LEGION_MAX_NUM_NODES' failed.
circuit.checkpoint: /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11962: virtual Legion::Internal::GatherCollective::~GatherCollective(): Assertion `done_event.has_triggered()' failed.
```

Despite setting `GASNET_BACKTRACE=1`, I do not appear to have gotten a meaningful backtrace from the process. I don't see either of the assert stack frames. It may be that the job scheduler killed the job too quickly to get all the backtraces.

## Run 2

I was able to get this one in an interactive job.

```
circuit.checkpoint: /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3510: void Legion::Internal::CollectiveViewCreator<OP>::construct_collective_mapping(const Legion::Internal::CollectiveViewCreatorBase::RendezvousKey&, std::map<Legion::LogicalRegion, Legion::Internal::CollectiveViewCreatorBase::CollectiveRendezvous>&) [with OP = Legion::Internal::Operation]: Assertion `tid == rit->first.get_tree_id()' failed.
circuit.checkpoint: /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11962: virtual Legion::Internal::GatherCollective::~GatherCollective(): Assertion `done_event.has_triggered()' failed.
```

Backtraces:

```
#8  0x00001555522c9e03 in Legion::Internal::CollectiveViewCreator<Legion::Internal::Operation>::construct_collective_mapping (this=0x154c945c2440, key=..., rendezvous=...)
    at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3510
#9  0x000015555242c987 in Legion::Internal::ReplCollectiveViewCreator<Legion::Internal::IndexDetachOp>::finalize_collective_mapping (this=0x154c945c2440, key=..., rendezvous=...)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:435
#10 0x00001555523d1bae in Legion::Internal::CollectiveViewRendezvous::post_gather (this=0x154c83001840) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:16450
#11 0x00001555523c52a9 in Legion::Internal::GatherCollective::handle_collective_message (this=0x154c83001840, derez=...) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12025
#12 0x0000155552171ad2 in Legion::Internal::ReplicateContext::handle_collective_message (this=0x154c9c47e1a0, derez=...) at /users/eslaught/resilience/legion/runtime/legion/legion_context.cc:20162
#13 0x0000155552452c9e in Legion::Internal::ShardTask::handle_collective_message (this=0x154c9c47aec0, derez=...) at /users/eslaught/resilience/legion/runtime/legion/legion_tasks.cc:8102
#14 0x00001555523c09c0 in Legion::Internal::ShardManager::handle_collective_message (this=0x154c9c478200, derez=...) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:10736
#15 0x00001555523c3986 in Legion::Internal::ShardManager::handle_collective_message (derez=..., runtime=0x161a8a0) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11565
#16 0x00001555526a449d in Legion::Internal::Runtime::handle_control_replicate_collective_message (this=0x161a8a0, derez=...) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:25302
#17 0x0000155552675052 in Legion::Internal::VirtualChannel::handle_messages (this=0x154c9c2c9780, num_messages=1, runtime=0x161a8a0, remote_address_space=100, args=0x154ca946b200 "\200\002", arglen=8732)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:12949
#18 0x00001555526732a4 in Legion::Internal::VirtualChannel::process_message (this=0x154c9c2c9780, args=0x154ca946b1e4, arglen=8752, runtime=0x161a8a0, remote_address_space=100)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:11573
#19 0x00001555526757db in Legion::Internal::MessageManager::receive_message (this=0x154c9c201210, args=0x154ca946b1e0, arglen=8760) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:13240
#20 0x00001555526a6bd2 in Legion::Internal::Runtime::process_message_task (this=0x161a8a0, args=0x154ca946b1dc, arglen=8764) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:25965
#21 0x00001555526bbe3b in Legion::Internal::Runtime::legion_runtime_task (args=0x154ca946b1d0, arglen=8768, userdata=0x160e520, userlen=8, p=...)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:31678
#22 0x000015554f7543c6 in Realm::LocalTaskProcessor::execute_task (this=0x112b420, func_id=4, task_args=...) at /users/eslaught/resilience/legion/runtime/realm/proc_impl.cc:1135
#23 0x000015554f7c1354 in Realm::Task::execute_on_processor (this=0x154ca927fbc0, p=...) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:302
#24 0x000015554f7c5e98 in Realm::UserThreadTaskScheduler::execute_task (this=0xe9ad40, task=0x154ca927fbc0) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1632
#25 0x000015554f7c3f45 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0xe9ad40) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1105
```

Jumping in to print some stuff (I have no idea what's helpful, just printing whatever I see in the code context):

```
(gdb) frame 8
#8  0x00001555522c9e03 in Legion::Internal::CollectiveViewCreator<Legion::Internal::Operation>::construct_collective_mapping (this=0x154c945c2440, key=..., rendezvous=...)
    at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3510
3510	        assert(tid == rit->first.get_tree_id());
(gdb) p tid
$1 = 99
(gdb) p rit->first
$3 = {
  tree_id = 2212274912,
  index_space = {
    id = 5452,
    tid = 2211681872,
    type_tag = 5452
  },
  field_space = {
    id = 99
  }
}
(gdb) p key
$5 = (const Legion::Internal::CollectiveViewCreatorBase::RendezvousKey &) @0x154c8300198c: {
  region_index = 0,
  analysis = 0
}
```

And the other thread:

```
#8  0x00001555523c4f6f in Legion::Internal::GatherCollective::~GatherCollective (this=0x154c83001840, __in_chrg=<optimized out>)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11962
#9  0x00001555523d0e70 in Legion::Internal::CollectiveViewRendezvous::~CollectiveViewRendezvous (this=0x154c83001840, __in_chrg=<optimized out>)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:16265
#10 0x00001555523d0e8c in Legion::Internal::CollectiveViewRendezvous::~CollectiveViewRendezvous (this=0x154c83001840, __in_chrg=<optimized out>)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:16268
#11 0x00001555523de334 in Legion::Internal::ReplCollectiveViewCreator<Legion::Internal::IndexDetachOp>::deactivate (this=0x154c945c2440, freeop=false)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:407
#12 0x00001555523b651e in Legion::Internal::ReplIndexDetachOp::deactivate (this=0x154c945c2440, freeop=true) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:7973
#13 0x00001555522675ac in Legion::Internal::Operation::commit_operation (this=0x154c945c2440, do_deactivate=true, wait_on=...) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:2226
#14 0x00001555522bc8e9 in Legion::Internal::IndexDetachOp::handle_point_commit (this=0x154c945c2440) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:22870
#15 0x00001555522bcf98 in Legion::Internal::PointDetachOp::trigger_commit (this=0x154c945c2f60) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:23041
#16 0x0000155552266ea7 in Legion::Internal::Operation::complete_operation (this=0x154c945c2f60, wait_on=...) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:2109
#17 0x00001555522bb334 in Legion::Internal::DetachOp::trigger_complete (this=0x154c945c2f60) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:22534
#18 0x00001555522bcf5b in Legion::Internal::PointDetachOp::trigger_complete (this=0x154c945c2f60) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:23032
#19 0x0000155552136ea3 in Legion::Internal::InnerContext::process_trigger_completion_queue (this=0x154c9c47e1a0) at /users/eslaught/resilience/legion/runtime/legion/legion_context.cc:8352
#20 0x0000155552145028 in Legion::Internal::InnerContext::handle_trigger_completion_queue (args=0x154ca927cd60) at /users/eslaught/resilience/legion/runtime/legion/legion_context.cc:11786
#21 0x00001555526bbf17 in Legion::Internal::Runtime::legion_runtime_task (args=0x154ca927cd60, arglen=12, userdata=0x161a690, userlen=8, p=...)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:31733
#22 0x000015554f7543c6 in Realm::LocalTaskProcessor::execute_task (this=0x153e9f0, func_id=4, task_args=...) at /users/eslaught/resilience/legion/runtime/realm/proc_impl.cc:1135
#23 0x000015554f7c1354 in Realm::Task::execute_on_processor (this=0x154ca927cbe0, p=...) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:302
#24 0x000015554f7c5e98 in Realm::UserThreadTaskScheduler::execute_task (this=0x153ece0, task=0x154ca927cbe0) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1632
#25 0x000015554f7c3f45 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x153ece0) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1105
```

And printing stuff:

```
(gdb) frame 8
#8  0x00001555523c4f6f in Legion::Internal::GatherCollective::~GatherCollective (this=0x154c83001840, __in_chrg=<optimized out>)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11962
11962	        assert(done_event.has_triggered());
(gdb) p/x done_event
$8 = {
  <Legion::Internal::RtEvent> = {
    <Legion::Internal::LgEvent> = {
      <Realm::Event> = {
        id = 0x8031800086d00009
      }, 
    }, 
  }, 
}
```

## Run 3

Again interactive. Looks similar to run 2.

```
circuit.checkpoint: /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3510: void Legion::Internal::CollectiveViewCreator<OP>::construct_collective_mapping(const Legion::Internal::CollectiveViewCreatorBase::RendezvousKey&, std::map<Legion::LogicalRegion, Legion::Internal::CollectiveViewCreatorBase::CollectiveRendezvous>&) [with OP = Legion::Internal::Operation]: Assertion `tid == rit->first.get_tree_id()' failed.
circuit.checkpoint: /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11962: virtual Legion::Internal::GatherCollective::~GatherCollective(): Assertion `done_event.has_triggered()' failed.
```

I somehow got three frozen process messages despite only two asserts.

```
#0  0x000015554d398400 in nanosleep () from /lib64/libc.so.6
#1  0x000015554d39830a in sleep () from /lib64/libc.so.6
#2  0x000015554f778fde in Realm::realm_freeze (signal=11) at /users/eslaught/resilience/legion/runtime/realm/runtime_impl.cc:183
#3  <signal handler called>
#4  0x00001555522d745a in std::vector<Legion::Internal::CollectiveMapping**, std::allocator<Legion::Internal::CollectiveMapping**> >::size (this=0x58)
    at /opt/gcc/10.3.0/snos/include/g++/bits/stl_vector.h:919
#5  0x000015555226b6dd in Legion::Internal::CollectiveViewCreatorBase::finalize_collective_mapping (runtime=0x161b9b0, mapping=0x154c9d58d8a0, owner=76, results=..., counts=..., views=...)
    at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3256
#6  0x000015555226bd29 in Legion::Internal::CollectiveViewCreatorBase::handle_finalize_collective_mapping (derez=..., runtime=0x161b9b0)
    at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3328
#7  0x00001555526a2be1 in Legion::Internal::Runtime::handle_collective_finalize_mapping (this=0x161b9b0, derez=...) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:24293
#8  0x000015555267448b in Legion::Internal::VirtualChannel::handle_messages (this=0x154c9da1ca60, num_messages=1, runtime=0x161b9b0, remote_address_space=55, args=0x154ca0696c00 "", arglen=182)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:12294
#9  0x00001555526732a4 in Legion::Internal::VirtualChannel::process_message (this=0x154c9da1ca60, args=0x154ca0696be4, arglen=202, runtime=0x161b9b0, remote_address_space=55)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:11573
#10 0x00001555526757db in Legion::Internal::MessageManager::receive_message (this=0x154c9c1dd910, args=0x154ca0696be0, arglen=210) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:13240
#11 0x00001555526a6bd2 in Legion::Internal::Runtime::process_message_task (this=0x161b9b0, args=0x154ca0696bdc, arglen=214) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:25965
#12 0x00001555526bbe3b in Legion::Internal::Runtime::legion_runtime_task (args=0x154ca0696bd0, arglen=218, userdata=0x160f630, userlen=8, p=...)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:31678
#13 0x000015554f7543c6 in Realm::LocalTaskProcessor::execute_task (this=0x112b400, func_id=4, task_args=...) at /users/eslaught/resilience/legion/runtime/realm/proc_impl.cc:1135
#14 0x000015554f7c1354 in Realm::Task::execute_on_processor (this=0x154ca1620f00, p=...) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:302
#15 0x000015554f7c5e98 in Realm::UserThreadTaskScheduler::execute_task (this=0xe9ad20, task=0x154ca1620f00) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1632
#16 0x000015554f7c3f45 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0xe9ad20) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1105
#17 0x000015554f7cb8c0 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0xe9ad20)
    at /users/eslaught/resilience/legion/runtime/realm/threads.inl:97
```

Looks like that vector is bad:

```
(gdb) frame 5
#5  0x000015555226b6dd in Legion::Internal::CollectiveViewCreatorBase::finalize_collective_mapping (runtime=0x161b9b0, mapping=0x154c9d58d8a0, owner=76, results=..., counts=..., views=...)
    at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3256
3256	          local_analyses += local_it->second->target_mappings.size();
(gdb) p local_analyses
$1 = 0
(gdb) p local_it->second->target_mappings.size()

Thread 8 "circuit.checkpo" received signal SIGSEGV, Segmentation fault.
0x00001555522d745a in std::vector<Legion::Internal::CollectiveMapping**, std::allocator<Legion::Internal::CollectiveMapping**> >::size (this=0x58) at /opt/gcc/10.3.0/snos/include/g++/bits/stl_vector.h:919
919	      { return size_type(this->_M_impl._M_finish - this->_M_impl._M_start); }
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(std::vector<Legion::Internal::CollectiveMapping**, std::allocator<Legion::Internal::CollectiveMapping**> >::size() const) will be abandoned.
When the function is done executing, GDB will silently stop.
```

Going back, I see a null pointer:

```
(gdb) frame 7
#7  0x000015555226b6dd in Legion::Internal::CollectiveViewCreatorBase::finalize_collective_mapping (runtime=0x161b9b0, mapping=0x154c9d58d8a0, owner=76, results=..., counts=..., views=...)
    at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3256
3256	          local_analyses += local_it->second->target_mappings.size();
(gdb) p local_it
$2 = {
  _M_current = 0x154c9fb9d890
}
(gdb) p local_it->second
$3 = (Legion::Internal::CollectiveViewCreatorBase::RendezvousResult *) 0x0
```

(And then I guess I crashed the process because my job ended before I got to the other two.)

## Run 4

Here's an example of my original crash:

```
circuit.checkpoint: /users/eslaught/resilience/legion/runtime/legion/runtime.cc:20637: Legion::Internal::MessageManager* Legion::Internal::Runtime::find_messenger(Legion::AddressSpaceID): Assertion `sid < LEGION_MAX_NUM_NODES' failed.
circuit.checkpoint: /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11962: virtual Legion::Internal::GatherCollective::~GatherCollective(): Assertion `done_event.has_triggered()' failed.
```

First backtrace:

```
#8  0x0000155552699cf5 in Legion::Internal::Runtime::find_messenger (this=0x161cb00, sid=43680) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:20637
#9  0x000015555269dbd6 in Legion::Internal::Runtime::send_collective_finalize_mapping (this=0x161cb00, target=43680, rez=...) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:21987
#10 0x000015555226b560 in Legion::Internal::CollectiveViewCreatorBase::finalize_collective_mapping (runtime=0x161cb00, mapping=0x154c96f05dc0, owner=43680, results=..., counts=..., views=...)
    at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3236
#11 0x00001555522ca443 in Legion::Internal::CollectiveViewCreator<Legion::Internal::Operation>::construct_collective_mapping (this=0x154c984de790, key=..., rendezvous=...)
    at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:3572
#12 0x000015555242c987 in Legion::Internal::ReplCollectiveViewCreator<Legion::Internal::IndexDetachOp>::finalize_collective_mapping (this=0x154c984de790, key=..., rendezvous=...)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:435
#13 0x00001555523d1bae in Legion::Internal::CollectiveViewRendezvous::post_gather (this=0x154c95e54460) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:16450
#14 0x00001555523c52a9 in Legion::Internal::GatherCollective::handle_collective_message (this=0x154c95e54460, derez=...) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:12025
#15 0x0000155552171ad2 in Legion::Internal::ReplicateContext::handle_collective_message (this=0x154c9c001200, derez=...) at /users/eslaught/resilience/legion/runtime/legion/legion_context.cc:20162
#16 0x0000155552452c9e in Legion::Internal::ShardTask::handle_collective_message (this=0x154c9c47aec0, derez=...) at /users/eslaught/resilience/legion/runtime/legion/legion_tasks.cc:8102
#17 0x00001555523c09c0 in Legion::Internal::ShardManager::handle_collective_message (this=0x154c9c478200, derez=...) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:10736
#18 0x00001555523c3986 in Legion::Internal::ShardManager::handle_collective_message (derez=..., runtime=0x161cb00) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11565
#19 0x00001555526a449d in Legion::Internal::Runtime::handle_control_replicate_collective_message (this=0x161cb00, derez=...) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:25302
#20 0x0000155552675052 in Legion::Internal::VirtualChannel::handle_messages (this=0x154c9c820500, num_messages=1, runtime=0x161cb00, remote_address_space=9, args=0x154caa00ada0 "\200\002", arglen=8732)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:12949
#21 0x00001555526732a4 in Legion::Internal::VirtualChannel::process_message (this=0x154c9c820500, args=0x154caa00ad84, arglen=8752, runtime=0x161cb00, remote_address_space=9)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:11573
#22 0x00001555526757db in Legion::Internal::MessageManager::receive_message (this=0x154c9cc12c50, args=0x154caa00ad80, arglen=8760) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:13240
#23 0x00001555526a6bd2 in Legion::Internal::Runtime::process_message_task (this=0x161cb00, args=0x154caa00ad7c, arglen=8764) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:25965
#24 0x00001555526bbe3b in Legion::Internal::Runtime::legion_runtime_task (args=0x154caa00ad70, arglen=8768, userdata=0x1610d00, userlen=8, p=...)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:31678
#25 0x000015554f7543c6 in Realm::LocalTaskProcessor::execute_task (this=0x112b420, func_id=4, task_args=...) at /users/eslaught/resilience/legion/runtime/realm/proc_impl.cc:1135
#26 0x000015554f7c1354 in Realm::Task::execute_on_processor (this=0x154ca9e7aff0, p=...) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:302
#27 0x000015554f7c5e98 in Realm::UserThreadTaskScheduler::execute_task (this=0xe9ad40, task=0x154ca9e7aff0) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1632
#28 0x000015554f7c3f45 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0xe9ad40) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1105
```

And printing stuff:

```
(gdb) frame 8
#8  0x0000155552699cf5 in Legion::Internal::Runtime::find_messenger (this=0x161cb00, sid=43680) at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:20637
20637	      assert(sid < LEGION_MAX_NUM_NODES);
(gdb) p sid
$1 = 43680
(gdb) p LEGION_MAX_NUM_NODES
No symbol "LEGION_MAX_NUM_NODES" in current context.
(gdb) p address_space
$2 = 8
```

I definitely do not have 43680 nodes in this job.

And the other thread:

```
#8  0x00001555523c4f6f in Legion::Internal::GatherCollective::~GatherCollective (this=0x154c95e54460, __in_chrg=<optimized out>)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11962
#9  0x00001555523d0e70 in Legion::Internal::CollectiveViewRendezvous::~CollectiveViewRendezvous (this=0x154c95e54460, __in_chrg=<optimized out>)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:16265
#10 0x00001555523d0e8c in Legion::Internal::CollectiveViewRendezvous::~CollectiveViewRendezvous (this=0x154c95e54460, __in_chrg=<optimized out>)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:16268
#11 0x00001555523de334 in Legion::Internal::ReplCollectiveViewCreator<Legion::Internal::IndexDetachOp>::deactivate (this=0x154c984de790, freeop=false)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:407
#12 0x00001555523b651e in Legion::Internal::ReplIndexDetachOp::deactivate (this=0x154c984de790, freeop=true) at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:7973
#13 0x00001555522675ac in Legion::Internal::Operation::commit_operation (this=0x154c984de790, do_deactivate=true, wait_on=...) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:2226
#14 0x00001555522bc8e9 in Legion::Internal::IndexDetachOp::handle_point_commit (this=0x154c984de790) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:22870
#15 0x00001555522bcf98 in Legion::Internal::PointDetachOp::trigger_commit (this=0x154c984e4080) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:23041
#16 0x0000155552266ea7 in Legion::Internal::Operation::complete_operation (this=0x154c984e4080, wait_on=...) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:2109
#17 0x00001555522bb334 in Legion::Internal::DetachOp::trigger_complete (this=0x154c984e4080) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:22534
#18 0x00001555522bcf5b in Legion::Internal::PointDetachOp::trigger_complete (this=0x154c984e4080) at /users/eslaught/resilience/legion/runtime/legion/legion_ops.cc:23032
#19 0x0000155552136ea3 in Legion::Internal::InnerContext::process_trigger_completion_queue (this=0x154c9c001200) at /users/eslaught/resilience/legion/runtime/legion/legion_context.cc:8352
#20 0x0000155552145028 in Legion::Internal::InnerContext::handle_trigger_completion_queue (args=0x154cae173380) at /users/eslaught/resilience/legion/runtime/legion/legion_context.cc:11786
#21 0x00001555526bbf17 in Legion::Internal::Runtime::legion_runtime_task (args=0x154cae173380, arglen=12, userdata=0x1610d90, userlen=8, p=...)
    at /users/eslaught/resilience/legion/runtime/legion/runtime.cc:31733
#22 0x000015554f7543c6 in Realm::LocalTaskProcessor::execute_task (this=0x153e9f0, func_id=4, task_args=...) at /users/eslaught/resilience/legion/runtime/realm/proc_impl.cc:1135
#23 0x000015554f7c1354 in Realm::Task::execute_on_processor (this=0x154cae173200, p=...) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:302
#24 0x000015554f7c5e98 in Realm::UserThreadTaskScheduler::execute_task (this=0x153ece0, task=0x154cae173200) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1632
#25 0x000015554f7c3f45 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x153ece0) at /users/eslaught/resilience/legion/runtime/realm/tasks.cc:1105
```

And printing stuff:

```
(gdb) frame 8
#8  0x00001555523c4f6f in Legion::Internal::GatherCollective::~GatherCollective (this=0x154c95e54460, __in_chrg=<optimized out>)
    at /users/eslaught/resilience/legion/runtime/legion/legion_replication.cc:11962
11962	        assert(done_event.has_triggered());
(gdb) p/x done_event
$3 = {
  <Legion::Internal::RtEvent> = {
    <Legion::Internal::LgEvent> = {
      <Realm::Event> = {
        id = 0x8004000022700013
      }, 
    }, 
  }, 
}
```

I'll leave it there for now, but let me know if there is anything specific you want me to look at.

**Comment by lightsighter** [comment]
Took an educated guess. Pull and try again.

**Comment by elliottslaughter** [comment]
Sorry, looks like all the same failure modes are still there.

Piz Daint has been pretty busy (thus why it took so long to confirm), but if it would help to attempt debugging anything else, please let me know in advance what I should try.

I didn't mention this in the original issue, but I already spent some time attempting to reproduce this several ways on Sapling with no luck there, even with oversubscription (e.g., 192 ranks across 3 nodes).

**Comment by elliottslaughter** [comment]
P.S. It might be best to give me options for both interactive and non-interactive debugging, since I have not been able to reliably get interactive jobs on Piz Daint.

**Comment by lightsighter** [comment]
I'm pretty confident that I know what is going on. I just need to get all the dependences hooked up in the right places and there are several of them. Pull and try again.

**Comment by elliottslaughter** [comment]
Looks like that fixed it. Thanks!
