### ISSUE TITLE
Legion: assertion `mapping_tracker != __null`

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#1441]
My CI, executed on the commit `c86174a1c` of Legion, is failing with the following assertion
```
prometeo_IsentropicMix.exec: /home/gitlab-runner/legion-debug/runtime/legion/legion_ops.cc:2347: bool Legion::Internal::Operation::register_dependence(Legion::Internal::Operation*, Legion::GenerationID): Assertion `mapping_tracker != __null' failed.
```
The backtrace of the assertion is
```
#0  0x00007f3dc58219fd in nanosleep () from /lib64/libc.so.6
#1  0x00007f3dc5821894 in sleep () from /lib64/libc.so.6
#2  0x00007f3dc96539dc in Realm::realm_freeze (signal=6) at /home/gitlab-runner/legion-debug/runtime/realm/runtime_impl.cc:183
#3  <signal handler called>
#4  0x00007f3dc5792387 in raise () from /lib64/libc.so.6
#5  0x00007f3dc5793a78 in abort () from /lib64/libc.so.6
#6  0x00007f3dc578b1a6 in __assert_fail_base () from /lib64/libc.so.6
#7  0x00007f3dc578b252 in __assert_fail () from /lib64/libc.so.6
#8  0x00007f3dc89bcb5c in Legion::Internal::Operation::register_dependence (this=0x7f3d903476c0, target=0x7f3d9038e510, target_gen=171) at /home/gitlab-runner/legion-debug/runtime/legion/legion_ops.cc:2347
#9  0x00007f3dc8b73375 in Legion::Internal::InnerContext::register_implicit_dependences (this=0x7f3d94072fb0, op=0x7f3d903476c0) at /home/gitlab-runner/legion-debug/runtime/legion/legion_context.cc:9366
#10 0x00007f3dc89bc8f4 in Legion::Internal::Operation::begin_dependence_analysis (this=0x7f3d903476c0) at /home/gitlab-runner/legion-debug/runtime/legion/legion_ops.cc:2291
#11 0x00007f3dc89ba8fb in Legion::Internal::Operation::execute_dependence_analysis (this=0x7f3d903476c0) at /home/gitlab-runner/legion-debug/runtime/legion/legion_ops.cc:1640
#12 0x00007f3dc8b6e31d in Legion::Internal::InnerContext::process_dependence_stage (this=0x7f3d94072fb0) at /home/gitlab-runner/legion-debug/runtime/legion/legion_context.cc:8055
#13 0x00007f3dc8b7d10e in Legion::Internal::InnerContext::handle_dependence_stage (args=0x7f3d7422cdd0) at /home/gitlab-runner/legion-debug/runtime/legion/legion_context.cc:11745
#14 0x00007f3dc9076bbf in Legion::Internal::Runtime::legion_runtime_task (args=0x7f3d7422cdd0, arglen=12, userdata=0x1ab23e0, userlen=8, p=...) at /home/gitlab-runner/legion-debug/runtime/legion/runtime.cc:31960
#15 0x00007f3dc99701e0 in Realm::LocalTaskProcessor::execute_task (this=0x1a62c30, func_id=4, task_args=...) at /home/gitlab-runner/legion-debug/runtime/realm/proc_impl.cc:1135
#16 0x00007f3dc97a575e in Realm::Task::execute_on_processor (this=0x7f3d7422cc50, p=...) at /home/gitlab-runner/legion-debug/runtime/realm/tasks.cc:302
#17 0x00007f3dc97a94dc in Realm::KernelThreadTaskScheduler::execute_task (this=0x1a62f70, task=0x7f3d7422cc50) at /home/gitlab-runner/legion-debug/runtime/realm/tasks.cc:1366
#18 0x00007f3dc97a8363 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x1a62f70) at /home/gitlab-runner/legion-debug/runtime/realm/tasks.cc:1105
#19 0x00007f3dc97a8986 in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x1a62f70) at /home/gitlab-runner/legion-debug/runtime/realm/tasks.cc:1217
#20 0x00007f3dc97aff8e in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock> (obj=0x1a62f70) at /home/gitlab-runner/legion-debug/runtime/realm/threads.inl:97
#21 0x00007f3dc9782093 in Realm::KernelThread::pthread_entry (data=0x7f3d8c17d860) at /home/gitlab-runner/legion-debug/runtime/realm/threads.cc:781
#22 0x00007f3dc533fea5 in start_thread () from /lib64/libpthread.so.0
#23 0x00007f3dc585ab0d in clone () from /lib64/libc.so.6
```

The same code used to work on the commit `af4d6f4a0` of Legion.

**Comment by lightsighter** [comment]
I will need a reproducer for this because basic static analysis says it is impossible.

**Comment by lightsighter** [comment]
Even something that reproduces 1 in 100 times is fine if it means I can look at it with a debugger.

**Comment by lightsighter** [comment]
Also you've tried with bounds checks? This is smelling a bit like memory corruption. As I said earlier, some pretty basic static analysis says this is impossible, so it's likely something else is scribbling on the heap where this operation is. Having a debugger will let us look at the object and see if it has been stomped on.

**Comment by mariodirenzo** [comment]
Yes, I am using bound checks in the same execution.
Is there any specific thing that you would look at with the debugger? I can attach one as soon as I can reproduce the issue again.

**Comment by mariodirenzo** [comment]
I haven't been able to reproduce the problem in a while. I'm closing the issue
