### ISSUE TITLE
Assertion `sit->second == local_space` failed

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/legion#1473]
I'm strong scaling HTR on GPUs, and once it hits the 8 node mark, it starts throwing warnings like 

```
LEGION WARNING: Failed to find a refinement for KD tree with 3 dimensions and 64 rectangles.
```

At 16 nodes, it segfaults. I ran in debug mode and it throws this error before any steps are recorded

```
legion/runtime/legion/region_tree.inl:7220: bool Legion::Internal::IndexPartNodeT<DIM, T>::find_local_shard_rects() [with int DIM = 3; T = long long int]: Assertion `sit->second == local_space' failed.
```

```
#0  0x00007f263ce969fd in nanosleep () from /lib64/libc.so.6
#1  0x00007f263ce96894 in sleep () from /lib64/libc.so.6
#2  0x00007f2640307bf4 in Realm::realm_freeze (signal=6) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/realm/runtime_impl.cc:187
#3  <signal handler called>
#4  0x00007f263ce07387 in raise () from /lib64/libc.so.6
#5  0x00007f263ce08a78 in abort () from /lib64/libc.so.6
#6  0x00007f263ce001a6 in __assert_fail_base () from /lib64/libc.so.6
#7  0x00007f263ce00252 in __assert_fail () from /lib64/libc.so.6
#8  0x00007f263ff4c5eb in Legion::Internal::IndexPartNodeT<3, long long>::find_local_shard_rects (this=0x7f25e81f62c0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/legion/region_tree.inl:7220
#9  0x00007f263fb8c70f in Legion::Internal::IndexPartNode::defer_find_local_shard_rects (args=0x7f25dc3c1b50) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/legion/region_tree.cc:10961
#10 0x00007f263fc8c297 in Legion::Internal::Runtime::legion_runtime_task (args=0x7f25dc3c1b50, arglen=12, userdata=0x3732040, userlen=8, p=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/legion/runtime.cc:32293
#11 0x00007f2640619766 in Realm::LocalTaskProcessor::execute_task (this=0x53444d0, func_id=4, task_args=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/realm/proc_impl.cc:1129
#12 0x00007f264045609e in Realm::Task::execute_on_processor (this=0x7f25dc3c19d0, p=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/realm/tasks.cc:302
#13 0x00007f2640459e2a in Realm::KernelThreadTaskScheduler::execute_task (this=0x53447a0, task=0x7f25dc3c19d0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/realm/tasks.cc:1366
#14 0x00007f2640458ca0 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x53447a0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/realm/tasks.cc:1105
#15 0x00007f26404592c2 in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x53447a0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/realm/tasks.cc:1217
#16 0x00007f26404605fe in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock> (obj=0x53447a0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/realm/threads.inl:97
#17 0x00007f26404323a5 in Realm::KernelThread::pthread_entry (data=0x7f25d003bf50) at /home/hpcc/gitlabci/psaap-ci/artifacts/4283405654/legion/runtime/realm/threads.cc:781
#18 0x00007f263c9b4ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f263cecfb0d in clone () from /lib64/libc.so.6
```

@mariodirenzo

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by cmelone** [comment]
I reran this config and it is now throwing the same error we're investigating in #1420

**Comment by lightsighter** [comment]
Then please close this issue.
