### ISSUE TITLE
Realm: Assertion ta >= a_zero failed

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1495]
I'm seeing the following assertion when I run legion applications:

```
legion_python: /home/seshu/dev/legion/runtime/realm/timers.inl:133: uint64_t Realm::Clock::TimescaleConverter::convert_forward_absolute(uint64_t): Assertion `ta >= a_zero' failed.
```

Here is a stack trace:
```
#0  0x00007fd88d0e59e5 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, 
    req=req@entry=0x55d54bf2f2e0, rem=rem@entry=0x55d54bf2f2e0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
#1  0x00007fd88d0ea5e7 in __GI___nanosleep (req=req@entry=0x55d54bf2f2e0, rem=rem@entry=0x55d54bf2f2e0)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00007fd88d0ea51e in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#3  0x00007fd88d71b3ed in Realm::realm_freeze (signal=6) at /home/seshu/dev/legion/runtime/realm/runtime_impl.cc:187
#4  <signal handler called>
#5  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
#6  0x00007fd88d09f2d3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#7  0x00007fd88d04fa08 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#8  0x00007fd88d038538 in __GI_abort () at abort.c:79
#9  0x00007fd88d03845c in __assert_fail_base (fmt=0x7fd88d1b4b08 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7fd890e1b516 "ta >= a_zero", 
    file=file@entry=0x7fd890e1b470 "/home/seshu/dev/legion/runtime/realm/timers.inl", line=line@entry=133, 
    function=function@entry=0x7fd890e1b4c8 "uint64_t Realm::Clock::TimescaleConverter::convert_forward_absolute(uint64_t)") at assert.c:92
#10 0x00007fd88d0483d6 in __assert_fail (assertion=0x7fd890e1b516 "ta >= a_zero", 
    file=0x7fd890e1b470 "/home/seshu/dev/legion/runtime/realm/timers.inl", line=133, 
    function=0x7fd890e1b4c8 "uint64_t Realm::Clock::TimescaleConverter::convert_forward_absolute(uint64_t)")
    at assert.c:101
#11 0x00007fd88ff56cae in Realm::Clock::TimescaleConverter::convert_forward_absolute (
    this=0x7fd88e71ad40 <Realm::Clock::native_to_nanoseconds>, ta=222981927203488)
    at /home/seshu/dev/legion/runtime/realm/timers.inl:133
#12 0x00007fd88ff56bde in Realm::Clock::current_time_in_nanoseconds (absolute=false)
    at /home/seshu/dev/legion/runtime/realm/timers.inl:67
#13 0x00007fd88d8a4815 in Realm::Doorbell::wait_slow (this=0x7fd88722d770)
    at /home/seshu/dev/legion/runtime/realm/mutex.cc:282
#14 0x00007fd88d76a845 in Realm::Doorbell::wait (this=0x7fd88722d770)
    at /home/seshu/dev/legion/runtime/realm/mutex.inl:81
#15 0x00007fd88d8d6d4f in Realm::ThreadedTaskScheduler::WorkCounter::wait_for_work (this=0x55d54be0c910, 
    old_counter=1) at /home/seshu/dev/legion/runtime/realm/tasks.cc:665
#16 0x00007fd88d8d9388 in Realm::ThreadedTaskScheduler::wait_for_work (this=0x55d54be0c750, old_work_counter=1)
    at /home/seshu/dev/legion/runtime/realm/tasks.cc:1240
#17 0x00007fd88d8db2e8 in Realm::UserThreadTaskScheduler::wait_for_work (this=0x55d54be0c750, old_work_counter=1)
    at /home/seshu/dev/legion/runtime/realm/tasks.cc:1741
#18 0x00007fd88d8d9145 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x55d54be0c750)
    at /home/seshu/dev/legion/runtime/realm/tasks.cc:1206
#19 0x00007fd88d8e1e48 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x55d54be0c750) at /home/seshu/dev/legion/runtime/realm/threads.inl:97
#20 0x00007fd88d8af6f8 in Realm::UserThread::uthread_entry () at /home/seshu/dev/legion/runtime/realm/threads.cc:1355
#21 0x00007fd88d0662d0 in ?? () at ../sysdeps/unix/sysv/linux/x86_64/__start_context.S:90 from /usr/lib/libc.so.6
#22 0x0000000000000000 in ?? ()
```

**Comment by streichler** [comment]
which system are you on, and does it happen reliably?

**Comment by syamajala** [comment]
This is on my laptop. I am trying to play with jupyter notebooks and pygion, but I hit it just running the partitioning c++ example from the tutorials as well. 

It happens reliably.

**Comment by streichler** [comment]
x86 cpu?  If so, then we're getting confused because the cpu timestamp counter is going backwards, which isn't supposed to happen.  Does it work with `-ll:cputsc 0`?

**Comment by syamajala** [comment]
Yes x86. Its Ryzen 7 6850H. Adding `-ll:cputsc 0` works.

**Comment by streichler** [comment]
can you paste the output of `lscpu` on the laptop?

**Comment by syamajala** [comment]
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 PRO 6850H with Radeon Graphics
CPU family:                      25
Model:                           68
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        1
Frequency boost:                 enabled
CPU(s) scaling MHz:              47%
CPU max MHz:                     4784.3750
CPU min MHz:                     1600.0000
BogoMIPS:                        6390.07
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca
Virtualization:                  AMD-V
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
```
