### ISSUE TITLE
rust legion prof crash

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#1507]
I see the following crash on the attached profile. The python profiler succeeds on it.
[legate_0.gz](https://github.com/StanfordLegion/legion/files/12030597/legate_0.gz) (it's not actually a gz, it's a .prof, i had to rename it to let github accept the file upload).

```
➜  TorchSWE git:(cunumeric-no-mpi4py) ✗ RUST_BACKTRACE=1 /Users/rohany/Documents/nvidia/legate.core/_skbuild/macosx-13.0-x86_64-3.11/cmake-build/./cargo/build/x86_64-apple-darwin/release/legion_prof --view legate_*.prof
Reading log file "legate_0.prof"...
Matched 102161 objects
No Legion Spy data, skipping postprocess step
Sorting time ranges
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/backend/viewer.rs:810:76
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: <legion_prof::backend::viewer::StateDataSource as legion_prof_viewer::data::DataSource>::fetch_info
   4: legion_prof_viewer::app::Window::new
   5: core::ops::function::FnOnce::call_once{{vtable.shim}}
   6: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
   7: <eframe::native::run::glow_integration::GlowWinitApp as eframe::native::run::WinitApp>::on_event
   8: eframe::native::run::run_and_return::{{closure}}
   9: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
  10: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
  11: winit::platform_impl::platform::app_state::AppState::launched
  12: winit::platform_impl::platform::app_delegate::ApplicationDelegate::did_finish_launching
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
  32: eframe::native::run::run_and_return
  33: std::thread::local::LocalKey<T>::with
  34: eframe::native::run::glow_integration::run_glow
  35: eframe::run_native
  36: legion_prof_viewer::app::start
  37: legion_prof::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-07-12T17:12:10.798155Z  WARN egui_glow::painter: You forgot to call destroy() on the egui glow painter. Resources will leak!
```

**Comment by elliottslaughter** [comment]
You must be on a really old commit because the most recent version of `viewer.rs` contains only 11 lines:

https://gitlab.com/StanfordLegion/legion/-/blob/master/tools/legion_prof_rs/src/backend/viewer.rs

Can you update to the newest control_replication, and either cherry-pick https://gitlab.com/StanfordLegion/legion/-/merge_requests/860 (or wait for it to merge), and see if it still reproduces?

**Comment by rohany** [comment]
It's working for me now. Sorry for not including the Legion version in my issue, that's a silly mistake on my part.
