### ISSUE TITLE
Assertion `done_event.has_triggered()` failed

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/legion#1519]
Running HTR on 64 nodes with latest `control_replication`.

Error:

```
legion/legion_replication.cc:11785: virtual Legion::Internal::GatherCollective::~GatherCollective(): Assertion `done_event.has_triggered()' failed.
```

Backtrace:

```
#0  0x00007f026f3959fd in nanosleep () from /lib64/libc.so.6
#1  0x00007f026f395894 in sleep () from /lib64/libc.so.6
#2  0x00007f0272778172 in Realm::realm_freeze (signal=6) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/runtime_impl.cc:187
#3  <signal handler called>
#4  0x00007f026f306387 in raise () from /lib64/libc.so.6
#5  0x00007f026f307a78 in abort () from /lib64/libc.so.6
#6  0x00007f026f2ff1a6 in __assert_fail_base () from /lib64/libc.so.6
#7  0x00007f026f2ff252 in __assert_fail () from /lib64/libc.so.6
#8  0x00007f0271fc0921 in Legion::Internal::GatherCollective::~GatherCollective (this=0x7f022e7d06f0, __in_chrg=<optimized out>) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_replication.cc:11785
#9  0x00007f0271fc2516 in Legion::Internal::FutureReductionCollective::~FutureReductionCollective (this=0x7f022e7d06f0, __in_chrg=<optimized out>) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_replication.cc:12778
#10 0x00007f0271fc2536 in Legion::Internal::FutureReductionCollective::~FutureReductionCollective (this=0x7f022e7d06f0, __in_chrg=<optimized out>) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_replication.cc:12784
#11 0x00007f0271f94473 in Legion::Internal::ReplIndexTask::deactivate (this=0x7f022e7fb710, freeop=true) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_replication.cc:907
#12 0x00007f0271aa2619 in Legion::Internal::Operation::commit_operation (this=0x7f022e7fb8c0, do_deactivate=true, wait_on=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_ops.cc:2226
#13 0x00007f0271bdd2e1 in Legion::Internal::IndexTask::trigger_task_commit (this=0x7f022e7fb710) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:9808
#14 0x00007f0271bb62e4 in Legion::Internal::TaskOp::trigger_commit (this=0x7f022e7fb710) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:907
#15 0x00007f0271aa1f22 in Legion::Internal::Operation::complete_operation (this=0x7f022e7fb8c0, wait_on=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_ops.cc:2109
#16 0x00007f0271c48f29 in Legion::Internal::InnerContext::process_deferred_completion_queue (this=0x7f0236744b10) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_context.cc:8317
#17 0x00007f0271c56702 in Legion::Internal::InnerContext::handle_deferred_completion_queue (args=0x7f01dc0cf430) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_context.cc:11748
#18 0x00007f027214f751 in Legion::Internal::Runtime::legion_runtime_task (args=0x7f01dc0cf430, arglen=12, userdata=0x4134be0, userlen=8, p=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/runtime.cc:32012
#19 0x00007f0272a92a88 in Realm::LocalTaskProcessor::execute_task (this=0x2d70d90, func_id=4, task_args=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/proc_impl.cc:1175
#20 0x00007f02728cdfae in Realm::Task::execute_on_processor (this=0x7f01dc0cf2b0, p=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/tasks.cc:326
#21 0x00007f02728d1ec8 in Realm::KernelThreadTaskScheduler::execute_task (this=0x2d71160, task=0x7f01dc0cf2b0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/tasks.cc:1421
#22 0x00007f02728d0d3f in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x2d71160) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/tasks.cc:1160
#23 0x00007f02728d1362 in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x2d71160) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/tasks.cc:1272
#24 0x00007f02728d867c in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock> (obj=0x2d71160) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/threads.inl:97
#25 0x00007f02728a97fb in Realm::KernelThread::pthread_entry (data=0x7f01f807d9d0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/threads.cc:781
#26 0x00007f026eeb3ea5 in start_thread () from /lib64/libpthread.so.0
#27 0x00007f026f3ceb0d in clone () from /lib64/libc.so.6
```

We have disabled collective instances using `check_collective_regions.clear()`

@mariodirenzo

**Comment by cmelone** [comment]
New error:

```
legion/runtime/legion/legion_replication.cc:12759: Legion::Internal::RtEvent Legion::Internal::FutureBroadcastCollective::async_broadcast(Legion::Internal::FutureInstance*, Legion::Internal::ApEvent, Legion::Internal::RtEvent): Assertion `post.exists()' failed.
```

```
#0  0x00007faa7d2619fd in nanosleep () from /lib64/libc.so.6
#1  0x00007faa7d261894 in sleep () from /lib64/libc.so.6
#2  0x00007faa806442ba in Realm::realm_freeze (signal=6) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/runtime_impl.cc:187
#3  <signal handler called>
#4  0x00007faa7d1d2387 in raise () from /lib64/libc.so.6
#5  0x00007faa7d1d3a78 in abort () from /lib64/libc.so.6
#6  0x00007faa7d1cb1a6 in __assert_fail_base () from /lib64/libc.so.6
#7  0x00007faa7d1cb252 in __assert_fail () from /lib64/libc.so.6
#8  0x00007faa7fe8e441 in Legion::Internal::FutureBroadcastCollective::async_broadcast (this=0x7faa3a76c920, inst=0x7faa447836c0, precondition=..., post=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_replication.cc:12759
#9  0x00007faa7fe6260c in Legion::Internal::ReplIndexTask::finish_index_task_reduction (this=0x7faa3a67dad0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_replication.cc:1373
#10 0x00007faa7faaadfa in Legion::Internal::IndexTask::return_slice_complete (this=0x7faa3a67dad0, points=1, slice_done=..., to_merge=..., metadata=0x0, metasize=0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:10220
#11 0x00007faa7fab1ca5 in Legion::Internal::SliceTask::trigger_slice_complete (this=0x7faa245a4b50) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:12014
#12 0x00007faa7fab017e in Legion::Internal::SliceTask::trigger_task_complete (this=0x7faa245a4b50) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:11629
#13 0x00007faa7fa871ed in Legion::Internal::TaskOp::trigger_children_complete (this=0x7faa245a4b50) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:1964
#14 0x00007faa7fab090d in Legion::Internal::SliceTask::record_point_complete (this=0x7faa245a4b50, child_complete=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:11766
#15 0x00007faa7fa9ecb2 in Legion::Internal::PointTask::trigger_task_complete (this=0x7faa245a5750) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:7328
#16 0x00007faa7fa871ed in Legion::Internal::TaskOp::trigger_children_complete (this=0x7faa245a5750) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:1964
#17 0x00007faa7fa96d49 in Legion::Internal::SingleTask::trigger_children_complete (this=0x7faa245a5750, all_children_complete=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_tasks.cc:5106
#18 0x00007faa7fb5ed1b in Legion::Internal::LeafContext::post_end_task (this=0x7faa4479e860, instance=0x7faa32500d20, metadata=0x0, metasize=0, callback_functor=0x0, own_callback_functor=false) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_context.cc:24161
#19 0x00007faa7fb16089 in Legion::Internal::InnerContext::process_post_end_tasks (this=0x7faa4a50c9b0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_context.cc:8567
#20 0x00007faa7fb22904 in Legion::Internal::InnerContext::handle_post_end_task (args=0x7faa3e502570) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/legion_context.cc:11778
#21 0x00007faa8001b821 in Legion::Internal::Runtime::legion_runtime_task (args=0x7faa3e502570, arglen=12, userdata=0x37fe040, userlen=8, p=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/legion/runtime.cc:31982
#22 0x00007faa8095ebd0 in Realm::LocalTaskProcessor::execute_task (this=0x243d6a0, func_id=4, task_args=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/proc_impl.cc:1175
#23 0x00007faa8079a0f6 in Realm::Task::execute_on_processor (this=0x7faa3e5023f0, p=...) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/tasks.cc:326
#24 0x00007faa8079e010 in Realm::KernelThreadTaskScheduler::execute_task (this=0x243da70, task=0x7faa3e5023f0) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/tasks.cc:1421
#25 0x00007faa8079ce87 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x243da70) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/tasks.cc:1160
#26 0x00007faa8079d4aa in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x243da70) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/tasks.cc:1272
#27 0x00007faa807a47c4 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock> (obj=0x243da70) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/threads.inl:97
#28 0x00007faa80775943 in Realm::KernelThread::pthread_entry (data=0x7faa34800440) at /home/hpcc/gitlabci/psaap-ci/artifacts/4818828841/legion/runtime/realm/threads.cc:781
#29 0x00007faa7cd7fea5 in start_thread () from /lib64/libpthread.so.0
#30 0x00007faa7d29ab0d in clone () from /lib64/libc.so.6
```

**Comment by lightsighter** [comment]
It's just an overzealous assertion, I already pushed a fix.

**Comment by cmelone** [comment]
fixed, thanks Mike!
