### ISSUE TITLE
Legion: shardrefine seg fault

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1520]
I am hitting a seg fault with the nscbc (non-subranked) branch of S3D using the shardrefine branch of Legion. Here is a stack trace:

```
#0  0x00001555528f4238 in nanosleep () from /lib64/libc.so.6
#1  0x00001555528f413e in sleep () from /lib64/libc.so.6
#2  0x0000155548ce85ae in Realm::realm_freeze (signal=11) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/realm/runtime_impl.cc:187
#3  <signal handler called>
#4  std::__atomic_base<int>::load (__m=std::memory_order_seq_cst, this=0x138) at /cm/local/apps/gcc/9.2.0/include/c++/9.2.0/bits/atomic_base.h:419
#5  Legion::Internal::DistributedCollectable::add_base_resource_ref (this=0x0, source=Legion::Internal::REGION_TREE_REF, cnt=1) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/legion/garbage_collection.h:665
#6  0x000015554be1c093 in Legion::Internal::IndexSpaceNode::get_child (this=0x154be81c0240, c=0, defer=0x154be4ffec78, can_fail=true) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/legion/region_tree.cc:8081
#7  0x000015554be1e4f8 in Legion::Internal::IndexSpaceNode::handle_node_child_request (forest=0xaaefe50, derez=..., source=6) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/legion/region_tree.cc:8646
#8  0x000015554bef902b in Legion::Internal::Runtime::handle_index_space_child_request (this=0xaae8440, derez=..., source=6) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/legion/runtime.cc:24026
#9  0x000015554becaf16 in Legion::Internal::VirtualChannel::handle_messages (this=0x154be807b290, num_messages=1, runtime=0xaae8440, remote_address_space=6, args=0x154bf005bba0 "", arglen=52) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/legion/runtime.cc:11956
#10 0x000015554beca664 in Legion::Internal::VirtualChannel::process_message (this=0x154be807b290, args=0x154bf005bb84, arglen=72, runtime=0xaae8440, remote_address_space=6) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/legion/runtime.cc:11736
#11 0x000015554beccd0a in Legion::Internal::MessageManager::receive_message (this=0x154be807af00, args=0x154bf005bb80, arglen=80) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/legion/runtime.cc:13482
#12 0x000015554befe5e4 in Legion::Internal::Runtime::process_message_task (this=0xaae8440, args=0x154bf005bb7c, arglen=84) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/legion/runtime.cc:26554
#13 0x000015554bf13f4b in Legion::Internal::Runtime::legion_runtime_task (args=0x154bf005bb70, arglen=88, userdata=0xab02020, userlen=8, p=...) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/legion/runtime.cc:32341
#14 0x0000155548cc1f02 in Realm::LocalTaskProcessor::execute_task (this=0xaa451f0, func_id=4, task_args=...) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/realm/proc_impl.cc:1175
#15 0x0000155548d33746 in Realm::Task::execute_on_processor (this=0x154e7c97f1a0, p=...) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/realm/tasks.cc:326
#16 0x0000155548d3846a in Realm::UserThreadTaskScheduler::execute_task (this=0x509d980, task=0x154e7c97f1a0) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/realm/tasks.cc:1687
#17 0x0000155548d364f1 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x509d980) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/realm/tasks.cc:1160
#18 0x0000155548d3dee2 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x509d980) at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/realm/threads.inl:97
#19 0x0000155548d4b789 in Realm::UserThread::uthread_entry () at /lustre/scratch/vsyamaj/legion_s3d_nscbc/legion/runtime/realm/threads.cc:1355
#20 0x00001555528792e0 in ?? () from /lib64/libc.so.6
#21 0x0000000000000000 in ?? ()
```

Will try to reproduce on sapling.

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by syamajala** [comment]
It works now.

**Comment by syamajala** [comment]
I guess there is actually a shutdown hang, but I will open another bug report for that.
