### ISSUE TITLE
Legion Prof Rust Crash

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#1544]
I observe the following crash when running the Rust version of Legion Prof from the `control_replication` branch:

```
mebauer@terabithia shardrefine % RUST_BACKTRACE=1 legion_prof --view *prof
Reading log file "legate_0.prof"...
Reading log file "legate_9.prof"...
Reading log file "legate_2.prof"...
Reading log file "legate_12.prof"...
Reading log file "legate_14.prof"...
Reading log file "legate_1.prof"...
Reading log file "legate_10.prof"...
Reading log file "legate_8.prof"...
Reading log file "legate_11.prof"...
Reading log file "legate_6.prof"...
Reading log file "legate_15.prof"...
Reading log file "legate_4.prof"...
Reading log file "legate_13.prof"...
Reading log file "legate_3.prof"...
Reading log file "legate_5.prof"...
Reading log file "legate_7.prof"...
Matched 1527770 objects
Matched 1372321 objects
Matched 1339318 objects
Matched 1341817 objects
Matched 1288313 objects
Matched 1291212 objects
Matched 1187666 objects
Matched 1193816 objects
Matched 1290407 objects
Matched 1314365 objects
Matched 1236463 objects
Matched 1244229 objects
Matched 1263611 objects
Matched 1281425 objects
Matched 1337525 objects
Matched 1343200 objects
No Legion Spy data, skipping postprocess step
Sorting time ranges
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING: A significant number of long latency messages were detected during this run meaning that the network was likely congested and could be causing a significant performance degredation. We detected 41919 messages that took longer than 1000.00us to run, representing 10.19% of 411482 total messages. The longest latency message required 272676.69us to execute. Please report this case to the Legion developers along with an accompanying Legion Prof profile so we can better understand why the network is so congested.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/backend/data_source.rs:370:76
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: legion_prof::backend::data_source::StateDataSource::new
   4: legion_prof::backend::viewer::start
   5: legion_prof::main
   ```

The log files to reproduce the issue are too big to save here, so they are in `/home/mebauer/profilerfail` on sapling2.

**Comment by elliottslaughter** [comment]
Fix is in https://gitlab.com/StanfordLegion/legion/-/merge_requests/917 . Just flipped gather and scatter in the code.

**Comment by lightsighter** [comment]
Looks good, go ahead and close the issue once it merges.

**Comment by elliottslaughter** [comment]
Merged to master, feel free to merge up to control replication.
