### ISSUE TITLE
`shardrefine`: segmentation fault

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/legion#1548]
16 ranks, 4 ranks per node and 16 ranks, 1 rank per node.

backtrace:

```
#0  0x00007fcd167d09fd in nanosleep () from /lib64/libc.so.6
#1  0x00007fcd167d0894 in sleep () from /lib64/libc.so.6
#2  0x00007fcd18143ad2 in Realm::realm_freeze (signal=<optimized out>) at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/realm/runtime_impl.cc:200
#3  <signal handler called>
#4  0x0000000000000000 in ?? ()
#5  0x00007fcd17c6cc3d in Legion::Internal::ProjectionTreeExchange::post_complete_exchange (this=0x7fca7a24b830)
    at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/legion/legion_replication.cc:17025
#6  0x00007fcd17c7e863 in Legion::Internal::AllGatherCollective<false>::complete_exchange (this=0x7fca7a24b830)
    at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/legion/legion_replication.cc:12861
#7  0x00007fcd17d46530 in Legion::Internal::VirtualChannel::handle_messages (this=this@entry=0x7fcc53664980, num_messages=num_messages@entry=1, runtime=runtime@entry=0x2f47460,
    remote_address_space=remote_address_space@entry=5, args=0x7fcc6226ea20 "0\001", args@entry=0x7fcc6226ea0c "1\001", arglen=<optimized out>, arglen@entry=204)
    at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/legion/runtime.cc:13379
#8  0x00007fcd17d466d9 in Legion::Internal::VirtualChannel::process_message(void const*, unsigned long, Legion::Internal::Runtime*, unsigned int) ()
    at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/legion/runtime.cc:11745
#9  0x00007fcd17d46a98 in Legion::Internal::MessageManager::receive_message (this=<optimized out>, args=args@entry=0x7fcc6226ea00, arglen=212, arglen@entry=216)
    at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/legion/runtime.cc:13527
#10 0x00007fcd17d46ac9 in Legion::Internal::Runtime::process_message_task (this=this@entry=0x2f47460, args=args@entry=0x7fcc6226e9fc, arglen=216, arglen@entry=220)
    at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/legion/runtime.cc:26652
#11 0x00007fcd17d46b70 in Legion::Internal::Runtime::legion_runtime_task (args=0x7fcc6226e9f0, arglen=220, userdata=<optimized out>, userlen=<optimized out>, p=...)
    at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/legion/runtime.cc:32339
#12 0x00007fcd18349d91 in Realm::LocalTaskProcessor::execute_task(unsigned int, Realm::ByteArrayRef const&) ()
    at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/realm/bytearray.inl:150
#13 0x00007fcd1823cb53 in Realm::Task::execute_on_processor(Realm::Processor) () at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/realm/runtime_impl.h:498
#14 0x00007fcd1823cbe6 in Realm::UserThreadTaskScheduler::execute_task (this=<optimized out>, task=<optimized out>)
    at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/realm/tasks.cc:1687
#15 0x00007fcd1823b24c in Realm::ThreadedTaskScheduler::scheduler_loop() () at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/realm/tasks.cc:1158
#16 0x00007fcd1822245f in Realm::UserThread::uthread_entry() () at /home/hpcc/gitlabci/shardrefine/legion-cpu/runtime/realm/threads.cc:1355
#17 0x00007fcd16753190 in ?? () from /lib64/libc.so.6
#18 0x0000000000000000 in ?? ()
```

cc: @lightsighter @mariodirenzo

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by cmelone** [comment]
thanks!
