### ISSUE TITLE
Legion Prof: tile invariant failure

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1673]
Here's a reproducer for a failure mode we've been seeing in CI for a while.

[gcc9_cxx17_release_mpi_prof_regent.zip](https://github.com/StanfordLegion/legion/files/14826000/gcc9_cxx17_release_mpi_prof_regent.zip)

From this job: https://gitlab.com/StanfordLegion/legion/-/jobs/6519084355

Replicates locally:

```console
$ cargo run --all-features -- --archive gcc9_cxx17_release_mpi_prof_regent/test_output/test_prof_pennant_stripmine_bhlro24n/prof_*.gz
    Finished dev [optimized + debuginfo] target(s) in 1.68s
     Running `target/debug/legion_prof --archive gcc9_cxx17_release_mpi_prof_regent/test_output/test_prof_pennant_stripmine_bhlro24n/prof_0.gz gcc9_cxx17_release_mpi_prof_regent/test_output/test_prof_pennant_stripmine_bhlro24n/prof_1.gz`
Reading log file "gcc9_cxx17_release_mpi_prof_regent/test_output/test_prof_pennant_stripmine_bhlro24n/prof_1.gz"...
Reading log file "gcc9_cxx17_release_mpi_prof_regent/test_output/test_prof_pennant_stripmine_bhlro24n/prof_0.gz"...
Matched 13013 objects
Matched 9931 objects
No Legion Spy data, skipping postprocess step
Sorting time ranges
Created output directory "legion_prof.5"
Writing level 0 with 1 tiles
Writing level 1 with 4 tiles
Writing level 2 with 16 tiles
thread '<unnamed>' panicked at src/backend/data_source.rs:806:17:
assertion failed: point_interval.overlaps(tile_id.0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/backend/data_source.rs:806:17:
assertion failed: point_interval.overlaps(tile_id.0)
```

Legion version 570c11f23d3e36c1cdd8df7854787fc194207539

**Comment by elliottslaughter** [comment]
Fixed by https://gitlab.com/StanfordLegion/legion/-/merge_requests/1203
