### ISSUE TITLE
Potential scalability hazard in Realm GASNet-EX layer

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1710]
This was identified by @timattox at HPE.

The concern is code like the following in Realm. `targets` is `Realm::NodeSet` which is implemeneted as a bitset. Therefore, if you were to hit this code with `targets` containing all of (or a substantial fraction of) the nodes in a run, you would get all of the ranks iterating nodes in the same order everywhere, possibly resulting in more network contention that you might otherwise induce even for the same communication pattern.

https://github.com/StanfordLegion/legion/blob/d4cef06c68574f1089e5cb7d1eebe4a6b16b9bac/runtime/realm/gasnetex/gasnetex_module.cc#L310

It's not currently clear how often or if we hit this code, and whether we use this code in a manner that would induce the problematic communication pattern.

One potential solution, if this ends up being a problem, is to start iteration at `rank+1` and wrap around at the end, so that the communication is less correlated in time. Of course this does not modify the communication pattern and if we are using this to send messages from all nodes to all nodes, that would also be something we'd want to address.

CC @abbotts

**Comment by eddy16112** [comment]
It reminders me the all to all algorithm used in MPI https://github.com/open-mpi/ompi/blob/main/ompi/mca/coll/base/coll_base_alltoall.c#L209-L213. To avoid every node sends messages to every node at the same time, MPI tries to shift the order. I will think about it and see if we can apply the same idea to Realm.

**Comment by elliottslaughter** [comment]
That's true, but I think it's worth thinking about *if* this code gets used and *where* before we jump to conclusions.

What are the actual scenarios in a typical Legion application where we go through the code above?

**Comment by eddy16112** [comment]
It is used by active message https://github.com/StanfordLegion/legion/blob/d4cef06c68574f1089e5cb7d1eebe4a6b16b9bac/runtime/realm/gasnetex/gasnetex_module.cc#L711

I need to check if we use all to all active messages.

**Comment by eddy16112** [comment]
I have seen 1-to-all or 1-to-many active messages in triggering events, destroying instances and etc., but it is hard to tell if all-to-all is used (all-to-all only happens when all ranks are sending 1-to-all active messages at the same time) in a asynchronous runtime. If we do the shifting all the time, it may not be a good idea.

**Comment by lightsighter** [comment]
> What are the actual scenarios in a typical Legion application where we go through the code above?

I don't think there are actual scenarios where Legion ever go through the code above. I think multicast from 1-to-many (never all) will be used for event triggering in a few cases but not really much of anywhere else. When that does it occur it will be asynchronous between different nodes and only broadcasting to a subset of nodes so highly unlikely to cause a scalability issue. I would make this a very low priority to investigate and only consider changing the code after extensive profiling.

> it is hard to tell if all-to-all is used

I think all-to-all is only used at the beginning when Realm (not Legion) does the machine model broadcast.  That might be the one and only place where this is worth investigating.

**Comment by eddy16112** [comment]
@lightsighter machine module broadcast does not use all-to-all any more, now we use the allgather provided by the network library, we might use all-to-all for creating cuda ipc if shared peers is not detected. 

I have seen some many/few-to-many/all cases in Legion, here is an example when I run circuit with 4 ranks, do you know if it is a many-to-many/all or few-to-many/all case?
```
#0  Realm::GASNetEXMessageImpl::commit (this=0x7f3b5ad84510, act_payload_size=0) at /scratch2/wwu/legion-master/runtime/realm/gasnetex/gasnetex_module.cc:310
#1  0x000055bbc942b92f in Realm::ActiveMessage<Realm::EventUpdateMessage, 256ul>::commit (this=0x7f3b5ad844f0) at /scratch2/wwu/legion-master/runtime/realm/activemsg.inl:448
#2  0x000055bbc9420617 in Realm::GenEventImpl::trigger (this=0x7f3b58207d20, gen_triggered=74, trigger_node=2, poisoned=false, work_until=...)
    at /scratch2/wwu/legion-master/runtime/realm/event_impl.cc:1829
#3  0x000055bbc92cd19b in Realm::GenEventImpl::trigger (e=..., poisoned=false) at /scratch2/wwu/legion-master/runtime/realm/event_impl.inl:65
#4  0x000055bbc9419c99 in Realm::UserEvent::trigger (this=0x7f3b5ad84a50, wait_on=..., ignore_faults=false) at /scratch2/wwu/legion-master/runtime/realm/event_impl.cc:408
#5  0x000055bbc86e6e6d in Legion::Internal::Runtime::trigger_event (to_trigger=..., precondition=...) at /scratch2/wwu/legion-master/runtime/legion/runtime.h:4043
#6  0x000055bbc8a82c78 in Legion::Internal::RegionTreeForest::physical_perform_registration (this=0x55bbcc9e9de0, analysis=0x7f3b5aad80c0, targets=..., trace_info=..., 
    map_applied_events=std::set with 0 elements) at /scratch2/wwu/legion-master/runtime/legion/region_tree.cc:1976
#7  0x000055bbc8a83469 in Legion::Internal::RegionTreeForest::handle_defer_registration (this=0x55bbcc9e9de0, args=0x7f3b5aaad450)
    at /scratch2/wwu/legion-master/runtime/legion/region_tree.cc:2091
#8  0x000055bbc8b96ae5 in Legion::Internal::Runtime::legion_runtime_task (args=0x7f3b5aaad450, arglen=76, userdata=0x55bbf00bc5c0, userlen=8, p=...)
    at /scratch2/wwu/legion-master/runtime/legion/runtime.cc:24421
#9  0x000055bbc944a46c in Realm::LocalTaskProcessor::execute_task (this=0x55bbcc720010, func_id=4, task_args=...) at /scratch2/wwu/legion-master/runtime/realm/proc_impl.cc:1176
#10 0x000055bbc9b3542a in Realm::Task::execute_on_processor (this=0x7f3b5aade780, p=...) at /scratch2/wwu/legion-master/runtime/realm/tasks.cc:326
#11 0x000055bbc9b3a78a in Realm::UserThreadTaskScheduler::execute_task (this=0x55bbcc44dec0, task=0x7f3b5aade780) at /scratch2/wwu/legion-master/runtime/realm/tasks.cc:1687
#12 0x000055bbc9b38532 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x55bbcc44dec0) at /scratch2/wwu/legion-master/runtime/realm/tasks.cc:1160
#13 0x000055bbc9b40d90 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x55bbcc44dec0)
```

**Comment by lightsighter** [comment]
That just says you're in the multicast. It doesn't say how many nodes are being sent to. It might look like one-to-all on small node counts, but I bet that as you scale up the pattern becomes sparse.

**Comment by apryakhin** [comment]
The Realm barrier owner performs a 1-to-many multicast to notify the remote waiters. The remote subscribers list is NOT created via the NodeSet, though. It’s possible to consider scenarios where multiple barriers have identical subscriber lists. In practice, triggering will likely be asynchronous.

Another place where we are certainly using the pattern mentioned by @elliottslaughter is when tracking the sparsity map references across the system. We perform a 1-to-many operation from the owner to notify others to garbage collect. It’s not being used at the moment as we are making progress on completing this feature, but I am probably going to take a moment and evaluate how much of a problem it poses there and whether it needs to be addressed.

**Comment by lightsighter** [comment]
I think the crucial thing to realize about the issue raised is that the pattern above is only bad if multiple nodes are doing it *at the same time*. If just one node is doing it or even a few then it's not really going to be a scalability problem. All (or most of) the nodes have to be sending to one node and swamp the target node, then they all send to the next target node and swamp that one, etc. We don't get that pattern often in Realm and even if we did the likelihood of it all happening at the same time during asynchronous execution is unlikely.

**Comment by elliottslaughter** [comment]
> It’s possible to consider scenarios where multiple barriers have identical subscriber lists.

@lightsighter can correct me if I'm wrong but I believe Legion only uses all-to-all barriers for a small set of things during initialization. For the bulk of most applications, Legion builds its own reduction and broadcast trees. Therefore, for the patterns Legion uses, there will be *one barrier at a time*, and we may hammer one node in the process, but with a all-to-one followed by one-to-all, rather than a true all-to-all, and therefore not the pattern described in this issue.

> tracking the sparsity map references across the system. We perform a 1-to-many operation from the owner to notify others to garbage collect.

The applications which I imagine would hit this case would have other issues: namely, if every node requires the sparsity map for an index space that presumably means the application itself is doing all-to-all communication. (So think dense Circuit style communication.) We know this is non-scalable today and we'd have a lot of work to do to make it scalable, so I'd consider fixing this low priority.

**Comment by lightsighter** [comment]
> can correct me if I'm wrong but I believe Legion only uses all-to-all barriers for a small set of things during initialization

I don't think we do that at all anymore in Legion. All those patterns should be gone now I believe. There are some Realm barriers that span the entire machine at times, but @apryakhin is working on a "scalable" Realm barrier implementation so we don't get all-to-one or one-to-all patterns with those anymore.

> The applications which I imagine would hit this case would have other issues: namely, if every node requires the sparsity map for an index space that presumably means the application itself is doing all-to-all communication. (So think dense Circuit style communication.) We know this is non-scalable today and we'd have a lot of work to do to make it scalable, so I'd consider fixing this low priority.

Agreed. I think in 99% of cases sparsity maps will only be shared between a small subset of nodes, so the sparsity map reference clean up will be not be a scalability issue.
