### ISSUE TITLE
Fuzzer: assertion in multi-node DCR

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1735]
Failure mode:

``fuzzer: .../legion/runtime/legion/legion_replication.cc:431: void Legion::Internal::ReplCollectiveVersioning<OP>::create_collective_rendezvous(unsigned int) [with OP = Legion::Internal::CollectiveViewCreator<Legion::Internal::DependentPartitionOp>]: Assertion `collective_versioning_rendezvous.find(requirement_index) == collective_versioning_rendezvous.end()' failed.``

Backtrace:

```
#9  0x00007f2e89216f60 in Legion::Internal::ReplCollectiveVersioning<Legion::Internal::CollectiveViewCreator<Legion::Internal::DependentPartitionOp> >::create_collective_rendezvous (this=this@entry=0x7f2e0c00d420, 
    requirement_index=<optimized out>, requirement_index@entry=0) at /usr/include/c++/9/bits/move.h:74
#10 0x00007f2e8921712c in Legion::Internal::ReplCollectiveViewCreator<Legion::Internal::CollectiveViewCreator<Legion::Internal::DependentPartitionOp> >::create_collective_rendezvous (this=this@entry=0x7f2e0c00d420, tid=<optimized out>, 
    requirement_index=requirement_index@entry=0, analysis_index=analysis_index@entry=0)
    at /usr/include/c++/9/bits/stl_tree.h:348
#11 0x00007f2e891f3122 in Legion::Internal::ReplDependentPartitionOp::trigger_dependence_analysis (this=0x7f2e0c00d420)
    at /scratch/eslaught/fuzzer-experiment-5/legion/runtime/legion.h:253
#12 0x00007f2e890fc0b4 in Legion::Internal::Operation::execute_dependence_analysis (this=<optimized out>)
    at /scratch/eslaught/fuzzer-experiment-5/legion/runtime/legion/legion_ops.cc:1666
#13 0x00007f2e89013b3b in Legion::Internal::InnerContext::process_dependence_stage (this=0x7f2e0a787e00)
    at /scratch/eslaught/fuzzer-experiment-5/legion/runtime/legion/legion_context.cc:8471
#14 0x00007f2e8942c528 in Legion::Internal::Runtime::legion_runtime_task (args=0x7f2e0a7a9550, arglen=12, 
    userdata=<optimized out>, userlen=<optimized out>, p=...)
    at /scratch/eslaught/fuzzer-experiment-5/legion/runtime/legion/runtime.cc:32372
#15 0x00007f2e88078865 in Realm::LocalTaskProcessor::execute_task (this=0x55b66d943010, func_id=4, task_args=...)
    at /scratch/eslaught/fuzzer-experiment-5/legion/runtime/realm/bytearray.inl:150
#16 0x00007f2e880ca953 in Realm::Task::execute_on_processor (this=0x7f2e0a7a93d0, p=...)
    at /scratch/eslaught/fuzzer-experiment-5/legion/runtime/realm/bytearray.inl:39
#17 0x00007f2e880caa0a in Realm::UserThreadTaskScheduler::execute_task (this=<optimized out>, task=<optimized out>)
    at /scratch/eslaught/fuzzer-experiment-5/legion/runtime/realm/tasks.cc:1687
#18 0x00007f2e880c8e94 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x55b66db4d550)
    at /scratch/eslaught/fuzzer-experiment-5/legion/runtime/realm/tasks.cc:1158
```

Command line:

```
cd /scratch/eslaught/fuzzer-experiment-5
salloc -n 1 -N 1 -c 40 -p all --exclusive
REALM_FREEZE_ON_ERROR=1 srun -n 2 -c 20 ./build_debug_multi/src/fuzzer -fuzz:ops 2 -fuzz:replicate 1 -lg:prof 1 -lg:prof_logfile prof_%.gz
```

Note that I'm adding `-lg:prof` because it increases the probability of reproduction in manual runs. So far I have only reproduced without `-lg:prof` in my automated runs where I massively oversubscribe the machine, which is just more of a pain to run.

Note that I have validated this run with `-lg:safe_ctrlrepl 1` and `2`.

Rebuild instructions:

```
srun -n 1 -N 1 -c 40 -p all --exclusive --pty bash --login
cd /scratch/eslaught/fuzzer-experiment-5/legion/build_debug_multi
make install -j20
cd ../../build_debug_multi
make clean && make -j20
```

Fuzzer version: https://github.com/StanfordLegion/fuzzer/commit/3ef4c19266907eee6c5df86d9dc25b79b47f2d4b

Legion version: d741d2f53bca565b3bc5701ba0a939305e319c76

**Comment by lightsighter** [comment]
Should be fixed with: https://gitlab.com/StanfordLegion/legion/-/merge_requests/1420

**Comment by lightsighter** [comment]
Merged
