### ISSUE TITLE
Fuzzer: multiple failure modes with DCR

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1743]
I'm seeing multiple failure modes when I run with DCR now.

## Failure mode 1: AllGatherCollective::unpack_stage

``fuzzer: /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:13201: void Legion::Internal::AllGatherCollective<<anonymous> >::unpack_stage(int, Legion::Deserializer&) [with bool INORDER = false]: Assertion `stage < int(stage_notifications.size())' failed.``

Backtrace:

```
#9  0x00007fa61c6404cb in Legion::Internal::AllGatherCollective<false>::unpack_stage (this=0x7fa59330ec50, stage=stage@entry=28311553, derez=...)
    at /usr/include/c++/9/bits/stl_vector.h:915
#10 0x00007fa61c64ddc7 in Legion::Internal::AllGatherCollective<false>::handle_collective_message (this=0x7fa59330ec50, derez=...)
    at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
#11 0x00007fa61c47c420 in Legion::Internal::ReplicateContext::register_collective (this=<optimized out>, 
    collective=collective@entry=0x7fa59330ec50) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_context.cc:21526
#12 0x00007fa61c64d696 in Legion::Internal::AllGatherCollective<false>::perform_collective_async (this=0x7fa59330ec50, pre=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/realm/event.inl:49
#13 0x00007fa61c640571 in Legion::Internal::AllReduceCollective<Legion::SumReduction<bool>, false>::sync_all_reduce (
    this=this@entry=0x7fa59330ec50, val=val@entry=false)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:13879
#14 0x00007fa61c4d0dbf in Legion::Internal::ReplicateContext::has_interfering_shards (this=0x7fa592704bd0, one=<optimized out>, two=0x7fa59a9d2c80)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_context.cc:20103
#15 0x00007fa61c39d238 in Legion::Internal::LogicalState::has_interfering_shards (this=this@entry=0x7fa59002b210, analysis=..., 
    one=<optimized out>, two=<optimized out>) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_analysis.cc:4878
#16 0x00007fa61c7ce211 in Legion::Internal::RegionTreeNode::perform_dependence_checks<true> (this=this@entry=0x7fa596930e10, root=..., user=..., 
    prev_users=..., check_mask=..., open_below=..., arrived=<optimized out>, proj_info=..., state=..., logical_analysis=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_analysis.h:799
#17 0x00007fa61c78c6b3 in Legion::Internal::RegionTreeNode::register_logical_user (this=0x7fa596930e10, privilege_root=..., user=..., path=..., 
    trace_info=..., proj_info=..., user_mask=..., unopened_field_mask=..., refinement_mask=..., logical_analysis=..., refinements=..., 
    root_node=<optimized out>) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/region_tree.cc:15948
#18 0x00007fa61c78ca9a in Legion::Internal::RegionTreeNode::register_logical_user (this=0x7fa5967035e0, privilege_root=..., user=..., path=..., 
    trace_info=..., proj_info=..., user_mask=..., unopened_field_mask=..., refinement_mask=..., logical_analysis=..., refinements=..., 
    root_node=<optimized out>) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/region_tree.cc:16030
#19 0x00007fa61c7b9165 in Legion::Internal::RegionTreeForest::perform_dependence_analysis (this=0x556e3b85ad90, op=op@entry=0x7fa596c1f110, 
    idx=idx@entry=0, req=..., proj_info=..., logical_analysis=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/region_tree.cc:1644
#20 0x00007fa61c5343d9 in Legion::Internal::Operation::analyze_region_requirements (this=this@entry=0x7fa596c1f110, launch_space=<optimized out>, 
    func=0x7fa598004d60, shard_space=...) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_ops.cc:1342
#21 0x00007fa61c62e145 in Legion::Internal::ReplIndexTask::trigger_dependence_analysis (this=0x7fa596c1ef60)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:1396
#22 0x00007fa61c5373b4 in Legion::Internal::Operation::execute_dependence_analysis (this=<optimized out>)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_ops.cc:1666
#23 0x00007fa61c44ee7b in Legion::Internal::InnerContext::process_dependence_stage (this=0x7fa592704bd0)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_context.cc:8471
#24 0x00007fa61c867998 in Legion::Internal::Runtime::legion_runtime_task (args=0x7fa596c0dbe0, arglen=12, userdata=<optimized out>, 
    userlen=<optimized out>, p=...) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/runtime.cc:32408
#25 0x00007fa61b4b0db5 in Realm::LocalTaskProcessor::execute_task (this=0x556e3b5d7010, func_id=4, task_args=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/realm/bytearray.inl:150
#26 0x00007fa61b502c63 in Realm::Task::execute_on_processor (this=0x7fa596c0da60, p=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/realm/bytearray.inl:39
```

## Failure mode 2: Deserializer::deserialize

``fuzzer: /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_utilities.h:1100: void Legion::Deserializer::deserialize(T&) [with 
T = long unsigned int]: Assertion `(index+sizeof(T)) <= total_bytes' failed.``

Backtrace:

```
#9  0x00007fe16ecba7a0 in Legion::Deserializer::deserialize<unsigned long> (element=<optimized out>, this=<optimized out>)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion.inl:17958
#10 Legion::Internal::ProjectionTreeExchange::unpack_collective_stage (this=0x7fe0dead5260, derez=..., stage=<optimized out>)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:17397
#11 0x00007fe16ecc8408 in Legion::Internal::AllGatherCollective<false>::unpack_stage (this=0x7fe0dead5260, stage=stage@entry=26214401, derez=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:13169
#12 0x00007fe16ecd5dc7 in Legion::Internal::AllGatherCollective<false>::handle_collective_message (this=0x7fe0dead5260, derez=...)
    at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
#13 0x00007fe16eb04420 in Legion::Internal::ReplicateContext::register_collective (this=<optimized out>, 
    collective=collective@entry=0x7fe0dead5260) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_context.cc:21526
#14 0x00007fe16ecd5696 in Legion::Internal::AllGatherCollective<false>::perform_collective_async (this=0x7fe0dead5260, pre=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/realm/event.inl:49
#15 0x00007fe16e9ad5bf in Legion::Internal::ProjectionSummary::ProjectionSummary (this=0x7fe0deabd060, proj_info=..., node=<optimized out>, op=
    0x7fe0e6963950, index=0, req=..., state=0x7fe0f004a760, context=0x7fe0f27891d0)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_analysis.cc:3331
#16 0x00007fe16eb1d99c in Legion::Internal::ReplicateContext::construct_projection_summary (this=0x7fe0f27891d0, op=0x7fe0e6963950, index=0, 
    req=..., state=0x7fe0f004a760, proj_info=...) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_context.cc:20088
#17 0x00007fe16ea25084 in Legion::Internal::LogicalState::find_or_create_projection_summary (this=0x7fe0f004a760, op=op@entry=0x7fe0e6963950, 
    index=index@entry=0, req=..., analysis=..., proj_info=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_analysis.cc:4798
#18 0x00007fe16edf85f6 in Legion::Internal::RegionTreeNode::compute_projection_summary (this=0x7fe0e69301d0, op=op@entry=0x7fe0e6963950, 
    index=index@entry=0, req=..., analysis=..., proj_info=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/region_tree.cc:15906
#19 0x00007fe16ee40ea3 in Legion::Internal::RegionTreeForest::perform_dependence_analysis (this=0x55877b479f90, op=op@entry=0x7fe0e6963950, 
    idx=idx@entry=0, req=..., proj_info=..., logical_analysis=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/region_tree.cc:1611
#20 0x00007fe16ebbc3d9 in Legion::Internal::Operation::analyze_region_requirements (this=this@entry=0x7fe0e6963950, launch_space=<optimized out>, 
    func=0x7fe0f278eac0, shard_space=...) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_ops.cc:1342
#21 0x00007fe16ecb6145 in Legion::Internal::ReplIndexTask::trigger_dependence_analysis (this=0x7fe0e69637a0)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:1396
#22 0x00007fe16ebbf3b4 in Legion::Internal::Operation::execute_dependence_analysis (this=<optimized out>)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_ops.cc:1666
#23 0x00007fe16ead6e7b in Legion::Internal::InnerContext::process_dependence_stage (this=0x7fe0f27891d0)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_context.cc:8471
#24 0x00007fe16eeef998 in Legion::Internal::Runtime::legion_runtime_task (args=0x7fe0e6cf2050, arglen=12, userdata=<optimized out>, 
    userlen=<optimized out>, p=...) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/runtime.cc:32408
#25 0x00007fe16db38db5 in Realm::LocalTaskProcessor::execute_task (this=0x55877b4755e0, func_id=4, task_args=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/realm/bytearray.inl:150
#26 0x00007fe16db8ac63 in Realm::Task::execute_on_processor (this=0x7fe0e6cf1ed0, p=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/realm/bytearray.inl:39
```

## Instructions

To replicate:

```
cd /scratch/eslaught/fuzzer-experiment-5-fix-2
salloc -n 1 -N 1 -c 40 -p all --exclusive
for i in $(seq 0 40); do REALM_FREEZE_ON_ERROR=1 REALM_SYNTHETIC_CORE_MAP= srun -n 2 --ntasks-per-node 2 --overlap ./build_debug_multi/src/fuzzer -fuzz:seed 21469996280076 -fuzz:ops 1000 -ll:util 2 -ll:cpu 3 -fuzz:replicate 1 -level 4 & done
```

The failures are non-deterministic so you need to run in a loop as above to reproduce them.

To rebuild:

```
srun -n 1 -N 1 -c 40 -p all --exclusive --pty bash --login
cd /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/build_debug_multi
make install -j20
cd ../../build_debug_multi
make clean && make -j20
```

## Version information

Legion: dcdcf4a90ee7e860319cb55c07ab5b8d9905e6d6

Fuzzer: https://github.com/StanfordLegion/fuzzer/commit/3ef4c19266907eee6c5df86d9dc25b79b47f2d4b

**Comment by elliottslaughter** [comment]
For posterity, I rebuilt with a full debug build, so backtraces in the build should be more complete. E.g. for the first failure mode:

```
#9  0x00007f693b03b480 in Legion::Internal::AllGatherCollective<false>::unpack_stage (this=0x7f68aafb1ce0, stage=28311553, derez=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:13201                                        
#10 0x00007f693b03a55f in Legion::Internal::AllGatherCollective<false>::handle_collective_message (this=0x7f68aafb1ce0, derez=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:12937                                        
#11 0x00007f693ad9c50a in Legion::Internal::ReplicateContext::register_collective (this=0x7f68a8001270, collective=0x7f68aafb1ce0)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_context.cc:21526                              
#12 0x00007f693b03a37d in Legion::Internal::AllGatherCollective<false>::perform_collective_async (this=0x7f68aafb1ce0, pre=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:12875
#13 0x00007f693b03bb34 in Legion::Internal::AllReduceCollective<Legion::SumReduction<bool>, false>::async_all_reduce (this=0x7f68aafb1ce0, 
    val=false) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:13866
#14 0x00007f693b03bb93 in Legion::Internal::AllReduceCollective<Legion::SumReduction<bool>, false>::sync_all_reduce (this=0x7f68aafb1ce0, 
    val=false) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:13883
#15 0x00007f693ad9569d in Legion::Internal::ReplicateContext::has_interfering_shards (this=0x7f68a8001270, one=0x7f68bc0202d0, 
    two=0x7f68be7f72f0) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_context.cc:20103
#16 0x00007f693ab4cb4d in Legion::Internal::LogicalState::has_interfering_shards (this=0x7f68bc03f9f0, analysis=..., one=0x7f68bc0202d0, 
    two=0x7f68be7f72f0) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_analysis.cc:4878
#17 0x00007f693b298738 in Legion::Internal::RegionTreeNode::perform_dependence_checks<true> (this=0x7f68ba92fe60, root=..., user=..., 
    prev_users=..., check_mask=..., open_below=..., arrived=true, proj_info=..., state=..., logical_analysis=...)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/region_tree.cc:16602
#18 0x00007f693b28bf3d in Legion::Internal::RegionTreeNode::register_logical_user (this=0x7f68ba92fe60, privilege_root=..., user=..., 
    path=..., trace_info=..., proj_info=..., user_mask=..., unopened_field_mask=..., refinement_mask=..., logical_analysis=..., 
    refinements=..., root_node=false) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/region_tree.cc:15952
#19 0x00007f693b28c399 in Legion::Internal::RegionTreeNode::register_logical_user (this=0x7f68ba7037c0, privilege_root=..., user=..., 
    path=..., trace_info=..., proj_info=..., user_mask=..., unopened_field_mask=..., refinement_mask=..., logical_analysis=..., 
    refinements=..., root_node=true) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/region_tree.cc:16030
#20 0x00007f693b249e24 in Legion::Internal::RegionTreeForest::perform_dependence_analysis (this=0x558b21c11090, op=0x7f68ba988600, idx=0, 
    req=..., proj_info=..., logical_analysis=...) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/region_tree.cc:1644
#21 0x00007f693aea67f4 in Legion::Internal::Operation::analyze_region_requirements (this=0x7f68ba988600, launch_space=0x7f68ba97d6b0, func=
    0x7f68be989a30, shard_space=...) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_ops.cc:1342
#22 0x00007f693aff66ad in Legion::Internal::ReplIndexTask::trigger_dependence_analysis (this=0x7f68ba988450)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_replication.cc:1396
#23 0x00007f693b4a351b in Legion::Internal::Predicated<Legion::Internal::ReplIndexTask>::trigger_dependence_analysis (this=0x7f68ba988450)
    at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/legion_ops.inl:97
#24 0x00007f693aea7a2d in Legion::Internal::Operation::execute_dependence_analysis (this=0x7f68ba988600) at /scratch/eslaught/fuzzer-experim
ent-5-fix-2/legion/runtime/legion/legion_ops.cc:1666
#25 0x00007f693ad589fe in Legion::Internal::InnerContext::process_dependence_stage (this=0x7f68a8001270) at /scratch/eslaught/fuzzer-experim
ent-5-fix-2/legion/runtime/legion/legion_context.cc:8471
#26 0x00007f693ad67340 in Legion::Internal::InnerContext::handle_dependence_stage (args=0x7f68bac4c760) at /scratch/eslaught/fuzzer-experime
nt-5-fix-2/legion/runtime/legion/legion_context.cc:11969
#27 0x00007f693b374b92 in Legion::Internal::Runtime::legion_runtime_task (args=0x7f68bac4c760, arglen=12, userdata=0x558b2412df80, userlen=8
, p=...) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legion/runtime/legion/runtime.cc:32408
#28 0x00007f6938206162 in Realm::LocalTaskProcessor::execute_task (this=0x558b20a4cfc0, func_id=4, task_args=...) at /scratch/eslaught/fuzze
r-experiment-5-fix-2/legion/runtime/realm/proc_impl.cc:1176
#29 0x00007f693828318e in Realm::Task::execute_on_processor (this=0x7f68bac4c5e0, p=...) at /scratch/eslaught/fuzzer-experiment-5-fix-2/legi
on/runtime/realm/tasks.cc:326
```

**Comment by lightsighter** [comment]
Unfortunately, the backtraces are not interesting. The problem is happening long before this. I can actually see it when I play with it with `-DDEBUG_LEGION_COLLECTIVES`, but because of the build problems I haven't been able to debug it.

**Comment by elliottslaughter** [comment]
This one is in `/scratch/eslaught/fuzzer-experiment-5-fix-2/legion`.

**Comment by lightsighter** [comment]
This is the fix. It should probably go in the release:

https://gitlab.com/StanfordLegion/legion/-/merge_requests/1466

**Comment by lightsighter** [comment]
Merged.
