### ISSUE TITLE
Crash in resilient Circuit on multiple nodes

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1751]
Similar to #1750 this is a recent version of master (`regent-resilience` based on 4284cf6dc654fa2d42faf71a4f3d60c517c34277).

Failure:

``circuit: /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_replication.cc:407: void Legion::Internal::ReplCollectiveVersioning<OP>::finalize_collective_versioning_analysis(unsigned int, unsigned int, Legion::Internal::LegionMap<Legion::LogicalRegion, typename OP::RegionVersioning>&) [with OP = Legion::Internal::CollectiveViewCreator<Legion::Internal::AttachOp>; Legion::Internal::LegionMap<Legion::LogicalRegion, typename OP::RegionVersioning> = std::map<Legion::LogicalRegion, Legion::Internal::CollectiveVersioningBase::RegionVersioning, std::less<Legion::LogicalRegion>, Legion::Internal::LegionAllocator<std::pair<const Legion::LogicalRegion, Legion::Internal::CollectiveVersioningBase::RegionVersioning>, Legion::Internal::UNTRACKED_ALLOC> >; typename OP::RegionVersioning = Legion::Internal::CollectiveVersioningBase::RegionVersioning]: Assertion `finder != collective_versioning_rendezvous.end()' failed.``

Backtrace:

```
#9  0x00007f377a7870d5 in Legion::Internal::ReplCollectiveVersioning<Legion::Internal::CollectiveViewCreator<Legion::Internal::AttachOp> >::finalize_collective_versioning_analysis (this=0x7f36fa947860, index=0, parent_req_index=5, Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
to_perform=std::map with 1 element)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_replication.cc:407
#10 0x00007f377a5f07f0 in Legion::Internal::CollectiveVersioning<Legion::Internal::AttachOp>::rendezvous_collective_versioning_analysis (
    this=0x7f36fa947860, index=0, handle=..., tracker=0x7f36f40cf840, space=0, mask=..., parent_req_index=5)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_ops.cc:3636
#11 0x00007f377a6f1d8d in Legion::Internal::ReplAttachOp::perform_collective_versioning_analysis (this=0x7f36fa947860, index=0, 
    handle=..., tracker=0x7f36f40cf840, mask=..., parent_req_index=5)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_replication.cc:6877
#12 0x00007f377a29bc14 in Legion::Internal::VersionManager::perform_versioning_analysis (this=0x7f36f40cf840, outermost=0x7f36f67815b0, 
    version_info=0x7f36fa947b80, region_node=0x7f36fa93ece0, version_mask=..., op=0x7f36fa947860, index=0, parent_req_index=5, 
    Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
ready_events=std::set with 1 element, output_region_ready=0x0, collective_rendezvous=true)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_analysis.cc:23760
#13 0x00007f377a977879 in Legion::Internal::RegionNode::perform_versioning_analysis (this=0x7f36fa93ece0, ctx=1, 
    parent_ctx=0x7f36f67815b0, version_info=0x7f36fa947b80, mask=..., op=0x7f36fa947860, index=0, parent_req_index=5, Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 

    applied=std::set with 1 element, output_region_ready=0x0, collective_rendezvous=true)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/region_tree.cc:17221
#14 0x00007f377a931171 in Legion::Internal::RegionTreeForest::perform_versioning_analysis (this=0x56049ddcc710, op=0x7f36fa947860, 
    index=0, req=..., version_info=..., Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
ready_events=std::set with 1 element, output_region_ready=0x0, collective_rendezvous=true)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/region_tree.cc:1698
#15 0x00007f377a6f0b4d in Legion::Internal::ReplAttachOp::trigger_ready (this=0x7f36fa947860)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_replication.cc:6598
#16 0x00007f377a43cac7 in Legion::Internal::InnerContext::process_ready_queue (this=0x7f36f67815b0)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_context.cc:8647
#17 0x00007f377a44b12c in Legion::Internal::InnerContext::handle_ready_queue (args=0x7f36fa946030)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_context.cc:11977
#18 0x00007f377aa5ba1d in Legion::Internal::Runtime::legion_runtime_task (args=0x7f36fa946030, arglen=12, userdata=0x5604a149dc40, 
    userlen=8, p=...) at /scratch/eslaught/resilience-test-network/legion/runtime/legion/runtime.cc:32370
#19 0x00007f37778e33fe in Realm::LocalTaskProcessor::execute_task (this=0x56049dce2b60, func_id=4, task_args=...) at /scratch/eslaught/resilience-test-network/legion/runtime/realm/proc_impl.cc:1176
#20 0x00007f37779601ea in Realm::Task::execute_on_processor (this=0x7f36fa945eb0, p=...) at /scratch/eslaught/resilience-test-network/legion/runtime/realm/tasks.cc:326
```

Note that if you repro this is in the same directory as #1750.

To reproduce:

```
cd /scratch/eslaught/resilience-test-network
source experiment/sapling/env.sh
salloc -n 1 -N 1 -c 40 -p cpu --exclusive
i=0; while REALM_FREEZE_ON_ERROR=1 srun -n 2 -c 20 ./build/examples/circuit/circuit -lg:safe_ctrlrepl 1 -lg:inorder -level resilience=4; do let i++; echo $i; done
```

To rebuild:

```
cd /scratch/eslaught/resilience-test-network
source experiment/sapling/env.sh
srun -n 1 -N 1 -c 4 -p cpu --exclusive --pty bash --login
cd legion/build
make install -j20
cd ../../build
make clean && make -j20
```

**Comment by lightsighter** [comment]
Merged.
