### ISSUE TITLE
Crash in set_garbage_collection_priority in resilience test

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1752]
This is replicating a failure I've seen in the resilience CI, e.g. here: https://github.com/StanfordLegion/resilience/actions/runs/10647296358/job/29515103267

Appears to be a segfault. Backtrace on Sapling:

```
#5  0x00007fe3968bdcd8 in Legion::Mapping::MapperRuntime::set_garbage_collection_priority (this=0x5590e75013c0, 
    ctx=0x7fe30af8b710, instance=..., priority=-2147483647)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_mapping.cc:1445
#6  0x00005590e65eb820 in ResilientLegion::Mapping::ResilientMapper::map_copy(Legion::Internal::MappingCallInfo*, Legion::Copy const&, Legion::Mapping::Mapper::MapCopyInput const&, Legion::Mapping::Mapper::MapCopyOutput&) ()
#7  0x00007fe396c579fc in Legion::Internal::MapperManager::invoke_map_copy (this=0x5590eac5cfe0, op=0x7fe3129242c0, 
    input=..., output=...) at /scratch/eslaught/resilience-test-network/legion/runtime/legion/mapper_manager.cc:341
#8  0x00007fe3968e64f1 in Legion::Internal::CopyOp::trigger_mapping (this=0x7fe3129242c0)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/legion_ops.cc:6767
#9  0x00007fe396d93844 in Legion::Internal::Runtime::legion_runtime_task (args=0x7fe31291eb90, arglen=12, 
    userdata=0x5590eabd57c0, userlen=8, p=...)
    at /scratch/eslaught/resilience-test-network/legion/runtime/legion/runtime.cc:32434
#10 0x00007fe393c234dc in Realm::LocalTaskProcessor::execute_task (this=0x5590e741e5c0, func_id=4, task_args=...)
    at /scratch/eslaught/resilience-test-network/legion/runtime/realm/proc_impl.cc:1176
#11 0x00007fe393ca02c8 in Realm::Task::execute_on_processor (this=0x7fe31291ea10, p=...)
    at /scratch/eslaught/resilience-test-network/legion/runtime/realm/tasks.cc:326
#12 0x00007fe393ca5642 in Realm::UserThreadTaskScheduler::execute_task (this=0x5590e74f9790, task=0x7fe31291ea10)
    at /scratch/eslaught/resilience-test-network/legion/runtime/realm/tasks.cc:1687
```

Note I'm going to share the build with #1753, so watch out when you rebuild it:

To reproduce:

```
cd /scratch/eslaught/resilience-test-network
source experiment/sapling/env.sh
salloc -n 1 -N 1 -c 40 -p all --exclusive
for i in $(seq 0 40); do REALM_SYNTHETIC_CORE_MAP= REALM_FREEZE_ON_ERROR=1 srun -n 2 -N 1 --cpu-bind none --overlap ./build/tests/region_destroy -lg:safe_ctrlrepl 1 -level resilience=4 & done
```

Reproduction ratio seems to be about 10%.

To rebuild:

```
cd /scratch/eslaught/resilience-test-network
source experiment/sapling/env.sh
srun -n 1 -N 1 -c 40 -p all --exclusive --pty bash --login
./experiment/setup.sh
```

**Comment by lightsighter** [comment]
Is this a debug build?

**Comment by lightsighter** [comment]
Fixed with:
https://gitlab.com/StanfordLegion/legion/-/commit/d96954f9afebce9167a17e17f53725f51d1dc526

Not sure why you are setting a garbage collection priority on a no-instance, but Legion will now happily ignore this case.
