### ISSUE TITLE
[BUG] `Realm::RuntimeImpl::network_init()` leaks `argv`

### ISSUE THREAD

**Issue by Jacobfaib** [StanfordLegion/legion#1754]
```
Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x102aee510 in malloc (/opt/homebrew/Cellar/llvm/18.1.8/lib/clang/18/lib/darwin/libclang_rt.asan_osx_dynamic.dylib:arm64+0x52510)
    #1 0x1331ae49c in Realm::RuntimeImpl::network_init(int*, char***) /path/to/runtime/realm/runtime_impl.cc:1330:46
```
```c++
int new_argc = local_argc + starts.size();
const char **new_argv = (const char **)(malloc((new_argc + 1) * sizeof(char *))); // <--- never free'd
// ...
```

**Comment by muraj** [comment]
This one is a bit more difficult to deal with.  Unfortunately, for some reason, we set the passed in argc and argv to the newly allocated local_argc and local_argv.  So the caller actually depends on the newly allocated argv and of course it assumes it doesn't need to release it, which leaks.

This is yet another reason why I highly dislike relying on command line arguments for configuring Realm, and I am hoping the path for unifying the processors (and eventually the memories) will reduce and eventually eliminate the need to specify command line arguments to realm at all.  Until then, this leak will likely have to persist...

**Comment by eddy16112** [comment]
As long as we do not use `REALM_DEFAULT_ARGS`, we should not have leaks.

**Comment by Jacobfaib** [comment]
Legate exclusively uses `REALM_DEFAULT_ARGS` instead of `argc` and `argv`. IIRC we do forward them along (in case the user has put something in there), but we do not populate them.
