### ISSUE TITLE
Quickstart for Ubuntu

### ISSUE THREAD

**Issue by pedronahum** [StanfordLegion/legion#361]
Hi,

It looks like a dependency is missing in the quickstart for Ubuntu. I managed to get it to work after running the following code:

sudo apt-get install libncurses5-dev libncursesw5-dev

**Comment by streichler** [comment]
@pedronahum Thanks for letting us know.  Do you happen to still have a copy of the error messages you get without libcurses installed?

**Comment by pedronahum** [comment]
Hi @streichler,

I managed to reproduce the error, please see below. And please let me know if you would like me to run other tests. 

```
mkdir -p build/llvm_objects/luajit
g++ -o /dev/null build/tkind.o build/tcompiler.o build/tllvmutil.o build/tcwrapper.o build/tinline.o build/terra.o build/lparser.o build/lstring.o build/lobject.o build/lzio.o build/llex.o build/lctype.o build/treadnumber.o build/tcuda.o build/tdebug.o build/tinternalizedfiles.o build/lj_strscan.o build/main.o build/linenoise.o build/lib/libluajit-5.1.a -L/usr/lib/llvm-3.5/lib  -L/usr/lib/llvm-3.5/lib -lclangFrontend -lclangDriver -lclangSerialization -lclangCodeGen -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangAST -lclangLex -lclangBasic -lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMipo -lLLVMVectorize -lLLVMBitWriter -lLLVMIRReader -lLLVMAsmParser -lLLVMR600CodeGen -lLLVMR600Desc -lLLVMR600Info -lLLVMR600AsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMHexagonCodeGen -lLLVMHexagonAsmPrinter -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMTableGen -lLLVMDebugInfo -lLLVMOption -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMJIT -lLLVMLineEditor -lLLVMMCAnalysis -lLLVMMCDisassembler -lLLVMInstrumentation -lLLVMInterpreter -lLLVMCodeGen -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMProfileData -lLLVMMCJIT -lLLVMTarget -lLLVMRuntimeDyld -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMExecutionEngine -lLLVMMC -lLLVMCore -lLLVMSupport -lcurses  -lz -ldl -pthread -g -Wl,-t | egrep "lib(LLVM|clang)"  > build/llvm_objects/llvm_list
/usr/bin/ld: cannot find -lcurses
collect2: error: ld returned 1 exit status
# extract needed LLVM objects based on a dummy linker invocation
< build/llvm_objects/llvm_list build/bin/luajit-2.0.5 src/unpacklibraries.lua build/llvm_objects
# include all luajit objects, since the entire lua interface is used in terra 
mkdir -p release/lib
rm -f release/lib/libterra.a
ar -cq release/lib/libterra.a build/tkind.o build/tcompiler.o build/tllvmutil.o build/tcwrapper.o build/tinline.o build/terra.o build/lparser.o build/lstring.o build/lobject.o build/lzio.o build/llex.o build/lctype.o build/treadnumber.o build/tcuda.o build/tdebug.o build/tinternalizedfiles.o build/lj_strscan.o build/llvm_objects/*/*.o build/lua_objects/*.o
ranlib release/lib/libterra.a
mkdir -p release/bin release/lib
g++ -shared -fPIC -Wl,-export-dynamic -Wl,--whole-archive release/lib/libterra.a -Wl,--no-whole-archive -lcurses  -lz -ldl -pthread -o release/lib/terra.so  
g++ build/main.o build/linenoise.o -o release/bin/terra -g -Wl,-export-dynamic -Wl,--whole-archive release/lib/libterra.a -Wl,--no-whole-archive  -lcurses  -lz -ldl -pthread
/usr/bin/ld: cannot find -lcurses
collect2: error: ld returned 1 exit status
Makefile:237: recipe for target 'release/bin/terra' failed
make: *** [release/bin/terra] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lcurses
collect2: error: ld returned 1 exit status
Makefile:234: recipe for target 'release/lib/terra.so' failed
make: *** [release/lib/terra.so] Error 1
Traceback (most recent call last):
  File "./install.py", line 394, in <module>
    driver()
  File "./install.py", line 391, in driver
    install(**vars(args))
  File "./install.py", line 304, in install
    install_terra(terra_dir, external_terra_dir, thread_count, llvm)
  File "./install.py", line 149, in install_terra
    build_terra(terra_dir, thread_count, llvm)
  File "./install.py", line 116, in build_terra
    cwd=terra_dir)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'all', '-j', '12']' returned non-zero exit status 2
```

**Comment by elliottslaughter** [comment]
I'm a little surprised. As far as I know, Terra requires ncurses iff LLVM was built with it. If Ubuntu's copy of LLVM was built with it, I would have expected apt-get to find it as a dependency. However, I suppose it's also possible Terra's auto-detection is malfunctioning somehow.

**Comment by elliottslaughter** [comment]
Here's the check in Terra's Makefile. Can you please tell us what this returns for you?

https://github.com/zdevito/terra/blob/master/Makefile#L118-L121

Also can you tell us how you installed LLVM? If it came from an Ubuntu package repo, what distribution and version, etc.? I'd like to check if it's supposed to be linked to ncurses or not.

**Comment by pedronahum** [comment]
Hi @elliottslaughter ,

I wouldnt be surprised if this a mess created by me :o). 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

I did follow the steps, please see below:
```
sudo apt-get install clang-3.5 libclang-3.5-dev llvm-3.5-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
clang-3.5 is already the newest version (1:3.5.2-3ubuntu1).
libclang-3.5-dev is already the newest version (1:3.5.2-3ubuntu1).
llvm-3.5-dev is already the newest version (1:3.5.2-3ubuntu1).
```

Get current clang version, installed a couple of days ago using:
sudo apt-get install clang libclang-dev llvm-dev llvm

```
clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
I did try the compile Terra (link you provided above), and got a very similar error:
```
/usr/bin/ld: cannot find -lcurses
collect2: error: ld returned 1 exit status
# extract needed LLVM objects based on a dummy linker invocation
< build/llvm_objects/llvm_list build/bin/luajit-2.0.5 src/unpacklibraries.lua build/llvm_objects
# include all luajit objects, since the entire lua interface is used in terra 
mkdir -p build/lua_objects
cd build/lua_objects; ar x /home/pedro/terra/build/lib/libluajit-5.1.a
mkdir -p release/lib
rm -f release/lib/libterra.a
ar -cq release/lib/libterra.a build/tkind.o build/tcompiler.o build/tllvmutil.o build/tcwrapper.o build/tinline.o build/terra.o build/lparser.o build/lstring.o build/lobject.o build/lzio.o build/llex.o build/lctype.o build/treadnumber.o build/tcuda.o build/tdebug.o build/tinternalizedfiles.o build/lj_strscan.o build/llvm_objects/*/*.o build/lua_objects/*.o
ranlib release/lib/libterra.a
mkdir -p release/bin release/lib
g++ build/main.o build/linenoise.o -o release/bin/terra -g -Wl,-export-dynamic -Wl,--whole-archive release/lib/libterra.a -Wl,--no-whole-archive  -lcurses  -lz -ldl -pthread
/usr/bin/ld: cannot find -lcurses
collect2: error: ld returned 1 exit status
Makefile:237: recipe for target 'release/bin/terra' failed
make: *** [release/bin/terra] Error 1

```

**Comment by elliottslaughter** [comment]
Can you set `CLANG=clang-3.5` and `LLVM_CONFIG=llvm-config-3.5` in your environment, remove the terra directory, and build again? I'm wondering if Terra's Makefile is getting the versions mixed up.

Can you also show us what `llvm-config-3.5 --prefix` prints?

It occurs to me that `$(LLVM_PREFIX)/lib/libLLVMSupport.a` in the Terra Makefile might point to the wrong `libLLVMSupport.a` if `LLVM_PREFIX` is pointing to `/usr`. We might need to do something based on `$(LLVM_CONFIG) --libs` to make sure we get the right `.a` file.

**Comment by pedronahum** [comment]
Hi @elliottslaughter,

Sure, np! 

```
$ llvm-config-3.5 --prefix
/usr/lib/llvm-3.5
``` 
After making the requested changes:
```
$ clang --version
Ubuntu clang version 3.5.2-3ubuntu1 (tags/RELEASE_352/final) (based on LLVM 3.5.2)
Target: x86_64-pc-linux-gnu
Thread model: posix
``` 

```
$ llvm-config --prefix
/usr/lib/llvm-3.5
``` 

Unfortunately, after making all these changes, I get the same error:
```
/usr/bin/ld: cannot find -lcurses
collect2: error: ld returned 1 exit status
# extract needed LLVM objects based on a dummy linker invocation
< build/llvm_objects/llvm_list build/bin/luajit-2.0.5 src/unpacklibraries.lua build/llvm_objects
# include all luajit objects, since the entire lua interface is used in terra 
mkdir -p build/lua_objects
cd build/lua_objects; ar x /home/pedro/terra/build/lib/libluajit-5.1.a
mkdir -p release/lib
rm -f release/lib/libterra.a
ar -cq release/lib/libterra.a build/tkind.o build/tcompiler.o build/tllvmutil.o build/tcwrapper.o build/tinline.o build/terra.o build/lparser.o build/lstring.o build/lobject.o build/lzio.o build/llex.o build/lctype.o build/treadnumber.o build/tcuda.o build/tdebug.o build/tinternalizedfiles.o build/lj_strscan.o build/llvm_objects/*/*.o build/lua_objects/*.o
ranlib release/lib/libterra.a
mkdir -p release/bin release/lib
g++ build/main.o build/linenoise.o -o release/bin/terra -g -Wl,-export-dynamic -Wl,--whole-archive release/lib/libterra.a -Wl,--no-whole-archive  -lcurses  -lz -ldl -pthread
/usr/bin/ld: cannot find -lcurses
collect2: error: ld returned 1 exit status
Makefile:237: recipe for target 'release/bin/terra' failed
make: *** [release/bin/terra] Error 1

```

**Comment by elliottslaughter** [comment]
At this point, I probably just need to try this out myself. This might take several days; I'm out of the town at the moment.

**Comment by pedronahum** [comment]
No worries, as mentioned above, installing the libraries via apt-get seem to address the issue as the examples work.

**Comment by elliottslaughter** [comment]
Sorry for the delay. I created an issue at https://github.com/zdevito/terra/issues/307 to track progress on the upstream fix. Since this should go away when that fix is in place, I'm closing this issue for now.

Thanks again for reporting this.
