### ISSUE TITLE
Regent compiler hanging with somewhat pathological allocation

### ISSUE THREAD

**Issue by jcreus** [StanfordLegion/legion#477]
I was trying to reproduce a strange segfault as part of some larger codebase (which I'm happy to share if it helps, but this MWE seems to reproduce it). The culprit seems to be a struct that's larger than the stack size. While some of the segfaults are probably just because of that, others use heap-allocated memory and the size of the stack should not matter, and result in the compiler hanging and using more than 7 GB of RAM (in one instance it used all of 31 GB before being killed, but I haven't been able to reproduce it). I realize that this is a fairly pathological scenario (though it comes from an application where it would be useful), but it does seem to trigger some edge cases. Happy to help look into it further or share more code. Thanks!

For the legion repo, I'm at the latest stable commit, i.e. 6732fb6f61a631348c2ed7cd1317af444779b3b7 on Dec 27. For the terra repo, I'm at the latest master commit, i.e. 9e01a92c329af229e41f365deec26680f6bd6246.

```
import "regent"

local c = regentlib.c

Q = 16
N = 4782969
--N = 1000

-- Also fails if using fspace instead of struct
struct Doot {
  lens : uint16[N];
}


task segfault(vv : &Doot)
  c.printf("good day\n")
end

task hanging(vv : Doot)
  c.printf("good morning\n")
end

task top()

  c.printf("top begin\n")

  var hmmm : &Doot = [&Doot](c.malloc(Q*N));

  --this also fails but can probably be blamed on it being bigger than the stack
  --var hmmm : Doot[Q]
  
  segfault(hmmm)

  -- This one just makes the compiler hang, then exit with "C++ exception"
  -- Seems like it's probably because the struct is bigger than the stack size
  --hanging(hmmm[0])

  c.printf("task done\n")

end

print('calling regentlib.start')
regentlib.start(top)
print('regentlib.start finished')
```

**Comment by lightsighter** [comment]
Would you mind providing a stack trace just so we can confirm if it is a compiler or runtime issue? Thanks.

**Comment by elliottslaughter** [comment]
It's in LLVM, in instruction selection. (Backtrace at bottom.) Not sure why, but odds are if you replicated the same pattern in C you'd get exactly the same behavior.

But anyway, passing raw pointers is definitely going to break anyway. (Consider that any time you have multiple nodes, raw pointers simply aren't valid accross nodes, and even on a single node they defeat Legion's dependence analysis, so you could get bad behavior on single nodes too.)

Also just as a practical note, the amount of data we're talking about here is well beyond the point where it should be going into a region, even if the data is purely read-only. There is some point where it's advantageous to keep it in a task parameter, but that's probably under a couple of KB or so.

```
#0  0x0000000001481631 in std::enable_if<llvm::hashing::detail::is_hashable_data<unsigned int const>::value, llvm::hash_code>::type llvm::hashing::detail::hash_combine_range_impl<unsigned int const>(unsigned int const*, unsigned int const*) ()
#1  0x0000000001f53ea7 in llvm::FoldingSetNodeIDRef::ComputeHash() const ()
#2  0x0000000001f53ee3 in llvm::FoldingSetNodeID::ComputeHash() const ()
#3  0x0000000001f53cb4 in llvm::FoldingSetBase::GrowBucketCount(unsigned int) ()
#4  0x0000000001f53b85 in llvm::FoldingSetBase::InsertNode(llvm::FoldingSetBase::Node*, void*) ()
#5  0x0000000001e40806 in llvm::SelectionDAG::getRegister(unsigned int, llvm::EVT) ()
#6  0x0000000001e63438 in llvm::RegsForValue::getCopyToRegs(llvm::SDValue, llvm::SelectionDAG&, llvm::SDLoc const&, llvm::SDValue&, llvm::SDValue*, llvm::Value const*, llvm::ISD::NodeType) const ()
#7  0x0000000001e98453 in llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(llvm::Value const*, unsigned int) ()
#8  0x0000000001e9f377 in llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) ()
#9  0x0000000001ea82eb in llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, bool&) ()
#10 0x0000000001eb1b4c in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) ()
#11 0x0000000001eb3937 in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) ()
#12 0x0000000002227464 in (anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) ()
#13 0x00000000012b2221 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) ()
#14 0x00000000014ffc42 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
#15 0x00000000014ffcf3 in llvm::FPPassManager::runOnModule(llvm::Module&) ()
#16 0x00000000014ff88f in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
#17 0x0000000001a504fa in llvm::orc::SimpleCompiler::operator()(llvm::Module&) ()
#18 0x0000000001a50983 in std::_Function_handler<llvm::Expected<unsigned long> (), llvm::orc::LazyEmittingLayer<llvm::orc::IRCompileLayer<llvm::orc::RTDyldObjectLinkingLayer, llvm::orc::SimpleCompiler> >::EmissionDeferredModule::find(llvm::StringRef, bool, llvm::orc::IRCompileLayer<llvm::orc::RTDyldObjectLinkingLayer, llvm::orc::SimpleCompiler>&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#19 0x0000000001a4ec78 in llvm::orc::OrcMCJITReplacement::getGlobalValueAddress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#20 0x00000000009afa49 in JITGlobalValue (CU=0x65f4e40, gv=0x6a52998) at src/tcompiler.cpp:2774
#21 0x00000000009afb7c in terra_jit (L=0x40ee1378) at src/tcompiler.cpp:2788
#22 0x0000000003236df6 in lj_BC_FUNCC ()
#23 0x00000000031f73d0 in lua_pcall ()
#24 0x00000000009aabc8 in docall (L=0x40ee1378, narg=2, clear=0) at src/main.cpp:332
#25 0x00000000009aa1ca in main (argc=4, argv=0x7ffe17a5b0d8) at src/main.cpp:109
```

**Comment by jcreus** [comment]
Gotcha, yeah, that makes sense. Thanks!
