### ISSUE TITLE
assertion failures in DynamicTable

### ISSUE THREAD

**Issue by noahdesu** [StanfordLegion/legion#56]
@lightsighter I'm seeing the following assertion failures. it is somewhat inconsistent in that the same invocation may work with 1 node but not with 2. The only notable thing is that in these runs there is a single logical region that is large (e.g. > 4B elements, but square, so say > 2^16 x 2^16) partitioned into much smaller pieces.

```
tester_io: /home/nwatkins/src/legion/runtime//legion_utilities.h:8391: bool LegionRuntime::HighLevel::DynamicTable<ALLOCATOR>::has_entry(LegionRuntime::HighLevel::DynamicTable<ALLOCATOR>::IT) const [with ALLOCATOR = LegionRuntime::HighLevel::DynamicTableAllocator<LegionRuntime::HighLevel::PhysicalState, 10ul, 8ul>; LegionRuntime::HighLevel::DynamicTable<ALLOCATOR>::IT = int]: Assertion `(child != 0) && (child->level == (n->level -1)) && (index >= child->first_index) && (index <= child->last_index)' failed.
```

```
tester_io: /home/nwatkins/src/legion/runtime//legion_utilities.h:8559: LegionRuntime::HighLevel::DynamicTable<ALLOCATOR>::NodeBase* LegionRuntime::HighLevel::DynamicTable<ALLOCATOR>::lookup_leaf(LegionRuntime::HighLevel::Dynami
cTable<ALLOCATOR>::IT) [with ALLOCATOR = LegionRuntime::HighLevel::DynamicTableAllocator<LegionRuntime::HighLevel::PhysicalState, 10ul, 8ul>; LegionRuntime::HighLevel::DynamicTable<ALLOCATOR>::NodeBase = LegionRuntime::HighLeve
l::DynamicTableNodeBase<int>; typename ALLOCATOR::IT = int; LegionRuntime::HighLevel::DynamicTable<ALLOCATOR>::IT = int]: Assertion `(child != 0) && (child->level == (n->level - 1)) && (index >= child->first_index) && (index <=
 child->last_index)' failed.
```

**Comment by lightsighter** [comment]
Which of those four conditions is failing?  This piece of code has been stable for a very long time.  The non-deterministic nature of it leads me to believe that you have memory corruption going on from somewhere else in you program.

**Comment by noahdesu** [comment]
```
Assertion `(child->level == (n->level - 1))' failed.
```

**Comment by noahdesu** [comment]
These are the value

```
child->level 1, n->level-1 0
```

**Comment by lightsighter** [comment]
Is this repeatable?  Can you give me a minimal test case?

**Comment by lightsighter** [comment]
Two more questions:
1. Which branch?
2. What compiler are you using?

**Comment by streichler** [comment]
Noah, in addition to Mike's questions, can you test how strong the sensitivity is to the size of the logical region?  In particular, if it always happens when the total size is >= 2^32 and never happens when it's less, that would be curious.

**Comment by noahdesu** [comment]
@lightsighter branch is `noahdesu/legion rados4`. It's basically the DMA branch plus a version of attach/detach hacked up for rados, which admittedly is a large chunk of code. I was using gcc, I think 4.9 (whatever is default on rhel7).

@streichler  yeh, I had poked around a lot looking for some linearization into a 32-bit value, but no luck.  i'll try to collect some data today regarding bounds on region size for this problem (it may have to wait until im back in CA, today is last day at lab).

**Comment by lightsighter** [comment]
I actually saw this on the master branch tonight, but in the Realm version of the dynamic table:

/home/mebauer/extern_legion/legion/runtime//realm/dynamic_table.inl:177: Realm::DynamicTable<ALLOCATOR>::ET* Realm::DynamicTable<ALLOCATOR>::lookup_entry(Realm::DynamicTable<ALLOCATOR>::IT, int, typename ALLOCATOR::FreeList*) [with ALLOCATOR = Realm::DynamicTableAllocator<Realm::GenEventImpl, 10ul, 8ul>; Realm::DynamicTable<ALLOCATOR>::ET = Realm::GenEventImpl; Realm::DynamicTable<ALLOCATOR>::IT = int; typename ALLOCATOR::FreeList = Realm::DynamicTableFreeList<Realm::DynamicTableAllocator<Realm::GenEventImpl, 10ul, 8ul> >]: Assertion `(level_needed <= n->level) && (index >= n->first_index) && (index <= n->last_index)' failed.

It happened during shutdown of the runtime.  Unfortunately I couldn't get a backtrace as the owner MPI process killed the job.

**Comment by lightsighter** [comment]
Managed to get a backtrace.  No debugger capture yet...

[1] #8  0x00007f5f5b7a6a76 in __assert_fail_base (fmt=0x7f5f5b8f8370 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7c82c8 "(level_needed <= n->level) && (index >= n->first_index) && (index <= n->last_index)", file=file@entry=0x7c8280 "/home/mebauer/extern_legion/legion/runtime//realm/dynamic_table.inl", line=line@entry=177, function=function@entry=0x7ca060 <Realm::DynamicTable<Realm::DynamicTableAllocator<Realm::GenEventImpl, 10ul, 8ul> >::lookup_entry(int, int, Realm::DynamicTableFreeList<Realm::DynamicTableAllocator<Realm::GenEventImpl, 10ul, 8ul> >*)::__PRETTY_FUNCTION__> "Realm::DynamicTable<ALLOCATOR>::ET* Realm::DynamicTable<ALLOCATOR>::lookup_entry(Realm::DynamicTable<ALLOCATOR>::IT, int, typename ALLOCATOR::FreeList*) [with ALLOCATOR = Realm::DynamicTableAllocator<"...) at assert.c:92
[1] #9  0x00007f5f5b7a6b22 in __GI___assert_fail (assertion=0x7c82c8 "(level_needed <= n->level) && (index >= n->first_index) && (index <= n->last_index)", file=0x7c8280 "/home/mebauer/extern_legion/legion/runtime//realm/dynamic_table.inl", line=177, function=0x7ca060 <Realm::DynamicTable<Realm::DynamicTableAllocator<Realm::GenEventImpl, 10ul, 8ul> >::lookup_entry(int, int, Realm::DynamicTableFreeList<Realm::DynamicTableAllocator<Realm::GenEventImpl, 10ul, 8ul> >*)::__PRETTY_FUNCTION__> "Realm::DynamicTable<ALLOCATOR>::ET* Realm::DynamicTable<ALLOCATOR>::lookup_entry(Realm::DynamicTable<ALLOCATOR>::IT, int, typename ALLOCATOR::FreeList*) [with ALLOCATOR = Realm::DynamicTableAllocator<"...) at assert.c:101
[1] #10 0x00000000006c146f in Realm::DynamicTable<Realm::DynamicTableAllocator<Realm::GenEventImpl, 10ul, 8ul> >::lookup_entry(int, int, Realm::DynamicTableFreeList<Realm::DynamicTableAllocator<Realm::GenEventImpl, 10ul, 8ul> >*) ()
[1] #11 0x00000000006b8877 in Realm::RuntimeImpl::get_genevent_impl(Realm::Event) ()
[1] #12 0x00000000006fae30 in Realm::EventTriggerMessage::handle_request(Realm::EventTriggerMessage::RequestArgs) ()
[1] #13 0x00000000006bbe33 in IncomingShortMessage<Realm::EventTriggerMessage::RequestArgs, 147, &Realm::EventTriggerMessage::handle_request, 6>::run_handler() ()
[1] #14 0x0000000000714105 in IncomingMessageManager::handler_thread_loop() ()
[1] #15 0x00000000006e640d in Realm::KernelThread::pthread_entry(void*) ()
[1] #16 0x00007f5f5c84d182 in start_thread (arg=0x7f5f520d1700) at pthread_create.c:312
[1] #17 0x00007f5f5b871fbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by streichler** [comment]
I believe this to be one of the failure modes of the current HLR shutdown race condition.  Mike, let me know if you disagree.  (If you don't, I'm closing this bug.)

**Comment by lightsighter** [comment]
I'm not convinced of that yet.  I would prefer to leave it open.

**Comment by lightsighter** [comment]
A fix has been made to the high-level dynamic table implementation for this bug. I think we can account for the low-level faults as occurring during shutdown and therefore as something that needs to be dealt with as part of a better shutdown methodology. If we don't see anything in another month, then I think we can close it.

**Comment by lightsighter** [comment]
Haven't seen any problems with this issue in a long time so I'm going to close it.
