### ISSUE TITLE
Crash in lightweight Legion Spy mode

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#561]
The following steps lead to a crash when using the lightweight Legion Spy mode (crash at bottom of issue):

```
./install.py --debug
./regent.py examples/stencil_fast.rg -lg:spy -logfile spy_test_%.log
../tools/legion_spy.py -d spy_test_0.log
```

This goes away when using heavyweight Legion Spy mode (i.e. `CC_FLAGS=-DLEGION_SPY ./install.py --debug`).

We should probably add lightweight Spy to the CI and also make sure we run Spy tests with `-de` in addition to `-lpa` (the test does not crash with `-lpa`).

Crash looks like:

```
Reading log file spy_test_0.log...
Reducing top-level index space shapes...
Done
INFO: No logical dependence data was found so we are running logical analysis to show the dataflow graphs that the runtime should compute. These are not the actual dataflow graphs computed.
Performing logical analysis...
Performing logical dependence analysis for make_exterior_partition...
Pass
Performing logical dependence analysis for ghost_y_partition...
Pass
Performing logical dependence analysis for main...
Traceback (most recent call last):
  File "../tools/legion_spy.py", line 10930, in <module>
    main(temp_dir)
  File "../tools/legion_spy.py", line 10872, in main
    state.perform_logical_analysis(logical_checks, sanity_checks)
  File "../tools/legion_spy.py", line 10220, in perform_logical_analysis
    if not task.perform_logical_dependence_analysis(perform_checks):
  File "../tools/legion_spy.py", line 6800, in perform_logical_dependence_analysis
    if not op.perform_logical_analysis(perform_checks):
  File "../tools/legion_spy.py", line 5779, in perform_logical_analysis
    if not self.analyze_logical_fence(perform_checks):
  File "../tools/legion_spy.py", line 5733, in analyze_logical_fence
    self.add_incoming(prev_op)
  File "../tools/legion_spy.py", line 5208, in add_incoming
    assert dep.op2 == self
AttributeError: 'Operation' object has no attribute 'op2'
```

**Comment by lightsighter** [comment]
Doesn't reproduce in nopaint and later branches so I'm not going to fix it.
