### ISSUE TITLE
Assertion `it->impl != __null' failed in virtual void Legion::Internal::IndividualTask::trigger_dependence_analysis()

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#589]
I got the following assertion failure with the most recent master branch when I am running candle_uno (https://github.com/flexflow/FlexFlow/blob/master/examples/candle_uno.cc). The backtrace is as follows.

```
#0  0x00007fffd7c7e207 in raise () from /lib64/libc.so.6
#1  0x00007fffd7c7f8f8 in abort () from /lib64/libc.so.6
#2  0x00007fffd7c77026 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fffd7c770d2 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000233202b in Legion::Internal::IndividualTask::trigger_dependence_analysis (this=0x7ffa00438d60) at /home/users/zhihao/legion/runtime/legion/legion_tasks.cc:4985
#5  0x00000000022820f6 in Legion::Internal::Operation::execute_dependence_analysis (this=0x7ffa00438f10) at /home/users/zhihao/legion/runtime/legion/legion_ops.cc:366
#6  0x00000000022883c8 in Legion::Internal::SpeculativeOp::execute_dependence_analysis (this=0x7ffa00438f10) at /home/users/zhihao/legion/runtime/legion/legion_ops.cc:2288
#7  0x00000000022d9ce0 in Legion::Internal::MemoizableOp<Legion::Internal::SpeculativeOp>::execute_dependence_analysis (this=0x7ffa00438f10) at /home/users/zhihao/legion/runtime/legion/legion_ops.inl:124
#8  0x0000000002386a7f in Legion::Internal::InnerContext::process_dependence_stage (this=0x7ffa082017d0) at /home/users/zhihao/legion/runtime/legion/legion_context.cc:5770
#9  0x000000000238f6d0 in Legion::Internal::InnerContext::handle_dependence_stage (args=0x7ffa08199188) at /home/users/zhihao/legion/runtime/legion/legion_context.cc:7812
#10 0x00000000029be41c in Legion::Internal::Runtime::legion_runtime_task (args=0x7ffa08199188, arglen=12, userdata=0x45a9dd0, userlen=8, p=...) at /home/users/zhihao/legion/runtime/legion/runtime.cc:21669
#11 0x00000000035eaffa in Realm::LocalTaskProcessor::execute_task (this=0x4df69d0, func_id=4, task_args=...) at /home/users/zhihao/legion/runtime/realm/proc_impl.cc:967
#12 0x0000000002b747bd in Realm::Task::execute_on_processor (this=0x7ffa08198ff0, p=...) at /home/users/zhihao/legion/runtime/realm/tasks.cc:200
#13 0x0000000002b7886a in Realm::UserThreadTaskScheduler::execute_task (this=0x4df6ca0, task=0x7ffa08198ff0) at /home/users/zhihao/legion/runtime/realm/tasks.cc:1394
#14 0x0000000002b76c16 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x4df6ca0) at /home/users/zhihao/legion/runtime/realm/tasks.cc:903
#15 0x0000000002b7d2d6 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x4df6ca0) at /home/users/zhihao/legion/runtime/realm/threads.inl:97
#16 0x0000000002b54194 in Realm::UserThread::uthread_entry () at /home/users/zhihao/legion/runtime/realm/threads.cc:1032
#17 0x00007fffd7c90010 in ?? () from /lib64/libc.so.6
#18 0x0000000000000000 in ?? ()
```

**Comment by lightsighter** [comment]
This would happen if you passed in an "empty" future into the runtime, e.g. a future that you constructed yourself and didn't have a value associated with it. The runtime should probably handle this better, but did you intend to pass in an empty future?

**Comment by lightsighter** [comment]
If you think this is still a runtime bug then please make me a frozen process on sapling to look at.

**Comment by jiazhihao** [comment]
There should not be any empty future if the app runs correctly. Do you know how to track the life time of this feature? Such as which task created the future

**Comment by jiazhihao** [comment]
Turn out to be an application bug.

**Comment by lightsighter** [comment]
I've update the runtime to prune out uninitialized futures now whenever they are passed in so we don't get the internal assertion that we did here.
