### ISSUE TITLE
Legion: crash when tightening index space

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#684]
Reporting this for Mike:

Circuit running on 3 nodes with DCR crashes on a very small chance (~0.1%). Here is a backtrace:

```
...
#3  <signal handler called>
#4  0x00007f1ba094c65b in TightenIndexSpaceArgs (proxy=0x7f1b1c076880, this=0x7f1b4d7f93b0) at /home/wclee/legion/runtime/legion/region_tree.h:911
#5  Legion::Internal::IndexSpaceNodeT<1, long long>::tighten_index_space (this=0x7f1b1c076560) at /home/wclee/legion/runtime/legion/region_tree.inl:1589
#6  0x00007f1ba0941762 in Legion::Internal::IndexSpaceNodeT<1, long long>::set_realm_index_space (this=0x7f1b1c076560, source=0, value=...) at /home/wclee/legion/runtime/legion/region_tree.inl:1549
#7  0x00007f1ba09419ee in Legion::Internal::IndexSpaceNodeT<1, long long>::unpack_index_space (this=<optimized out>, derez=..., source=<optimized out>) at /home/wclee/legion/runtime/legion/region_tree.inl:2300
#8  0x00007f1ba0849752 in Legion::Internal::IndexSpaceNode::handle_index_space_set (forest=0x2268a090, derez=..., source=source@entry=0) at /home/wclee/legion/runtime/legion/region_tree.cc:7802
#9  0x00007f1ba0897689 in Legion::Internal::Runtime::handle_index_space_set (this=this@entry=0x226df050, derez=..., source=source@entry=0) at /home/wclee/legion/runtime/legion/runtime.cc:17356
#10 0x00007f1ba09021b1 in Legion::Internal::VirtualChannel::handle_messages (this=this@entry=0x7f1b28000930, num_messages=num_messages@entry=1, runtime=runtime@entry=0x226df050, remote_address_space=remote_address_space@entry=0, args=0x7f1b46111580 "\v", args@entry=0x7f1b4611156c "\a", arglen=<optimized out>, arglen@entry=56) at /home/wclee/legion/runtime/legion/runtime.cc:6858
#11 0x00007f1ba0903093 in Legion::Internal::VirtualChannel::process_message (this=0x7f1b28000930, args=args@entry=0x7f1b46111564, arglen=56, arglen@entry=64, runtime=0x226df050, remote_address_space=0) at /home/wclee/legion/runtime/legion/runtime.cc:6669
...
```

**Comment by lightsighter** [comment]
My own notes from the bug: three node runs, sending message from node 0 to node 2. The index space node on node 2 was deleted before the message arrived. Index space 2 owned the index space node because the handle was:
```
(gdb) p handle
$3 = {
  id = 11, 
  tid = 7, 
  type_tag = 258
}
```

**Comment by lightsighter** [comment]
I believe that this bug is fixed now. It's very hard to test, but the way that I fixed it was to add a reference to index space nodes that only gets removed once the index space is set, so it is now impossible for this error to occur. Closing the issue.
