### ISSUE TITLE
Realm Multi-Node Start-up Crash

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#70]
Caught this crash in start-up in Realm.  I've only seen it one time.  It looks like someone resized the vector while the loop on machine_impl.cc:247 was iterating over it.  However, I couldn't tell which thread modified it because it was long gone by the time the signal for the segfault was raised.  Since this happened in start-up, it should be a pretty small range of suspects.  No application code had started yet.

#0  0x00007f650b98e9bd in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f650b98e854 in __sleep (seconds=0) at ../sysdeps/unix/sysv/linux/sleep.c:137
#2  0x0000000000cd6e2e in Realm::realm_freeze (signal=11)
    at /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.cc:75
#3  <signal handler called>
#4  0x0000000000aa618a in Realm::Processor::operator!= (this=0x5f70000, rhs=...)
    at /home/mebauer/extern_legion/legion/runtime/realm/processor.h:41
#5  0x0000000000d6f081 in Realm::MachineImpl::get_proc_mem_affinity (this=0x31831e0, result=..., 
    restrict_proc=..., restrict_memory=...)
    at /home/mebauer/extern_legion/legion/runtime//realm/machine_impl.cc:247
#6  0x0000000000cda5dc in Realm::RuntimeImpl::init (this=0x3172d60, argc=0x7fff1991341c, 
    argv=0x7fff19913410) at /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.cc:889
#7  0x0000000000cd6efe in Realm::Runtime::init (this=0x7fff19913430, argc=0x7fff1991341c, 
    argv=0x7fff19913410) at /home/mebauer/extern_legion/legion/runtime//realm/runtime_impl.cc:106
#8  0x0000000000c44bea in LegionRuntime::HighLevel::Runtime::start (argc=28, argv=0x7fff19913618, 
    background=false) at /home/mebauer/extern_legion/legion/runtime//legion/runtime.cc:14737
#9  0x0000000000a35b69 in LegionRuntime::HighLevel::HighLevelRuntime::start (argc=28, 
    argv=0x7fff19913618, background=false)
    at /home/mebauer/extern_legion/legion/runtime//legion/legion.cc:3658
#10 0x00000000009f0df5 in main (argc=28, argv=0x7fff19913618) at main.cc:96

**Comment by lightsighter** [comment]
Caught it again.  Same place.  All other threads look to be asleep once the signal is raised.  Should probably also point out that this only happens on multi-node jobs.  Might be related to the announce active messages updating the same data structure.  Just a hypothesis.
