### ISSUE TITLE
tools: legion_spy crash when processing a large spy log

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#948]
I have stored the log file on sapling at the path `/home/rohany/pennant_assert_failure_spy.log`. I ran `tools/legion_spy.py -dez <filename>` and saw this failure:

```
Traceback (most recent call last):
  File "../tools/legion_spy.py", line 12401, in <module>
    main(temp_dir)
  File "../tools/legion_spy.py", line 12356, in main
    state.perform_physical_analysis(physical_checks, sanity_checks)
  File "../tools/legion_spy.py", line 11586, in perform_physical_analysis
    if not top_task.perform_task_physical_verification(perform_checks):
  File "../tools/legion_spy.py", line 7704, in perform_task_physical_verification
    if not op.perform_op_physical_verification(perform_checks):
  File "../tools/legion_spy.py", line 6956, in perform_op_physical_verification
    for point in itervalues(self.points):
  File "../tools/legion_spy.py", line 142, in itervalues
    return obj.values() if sys.version_info > (3,) else obj.viewvalues()
AttributeError: 'NoneType' object has no attribute 'viewvalues'
```

I'm using python2 and ran the version of `legion_spy` on the branch `runtime-auto-mapper`. A `git diff` shows that there are no differences to that file on the branch vs master.

**Comment by lightsighter** [comment]
This file does not look like the right log file to reproduce the problem. When I run the file you've provided above, it starts to perform the emulation analysis. However the backtrace for this crash is attempting to perform the verification analysis which should not happen with just the `-dez` flags. Verification happens with the `-p` flag. Please provide the full Legion Spy output prior to the crash.

**Comment by rohany** [comment]
I've left a log file `legion_spy.log` in the same directory the file above is in. To generate it I ran 
```
legion/tools/legion_spy.py -dez pennant_assert_failure_spy.log &> legion_spy.log
```
and the invocation took around 1 hour and 30 minutes to complete. 
```
rohany@sapling:~$ tail -n 20 legion_spy.log
  Performing physical emulation analysis for adv_pos_half (UID 167046)...
  Performing physical emulation analysis for adv_pos_half (UID 167047)...
  Performing physical emulation analysis for adv_pos_half (UID 167048)...
  Performing physical emulation analysis for calc_centers (UID 167051)...
  Performing physical emulation analysis for calc_centers (UID 167052)...
  Performing physical emulation analysis for calc_centers (UID 167053)...
Traceback (most recent call last):
  File "legion/tools/legion_spy.py", line 12401, in <module>
    main(temp_dir)
  File "legion/tools/legion_spy.py", line 12356, in main
    state.perform_physical_analysis(physical_checks, sanity_checks)
  File "legion/tools/legion_spy.py", line 11586, in perform_physical_analysis
    if not top_task.perform_task_physical_verification(perform_checks):
  File "legion/tools/legion_spy.py", line 7704, in perform_task_physical_verification
    if not op.perform_op_physical_verification(perform_checks):
  File "legion/tools/legion_spy.py", line 6956, in perform_op_physical_verification
    for point in itervalues(self.points):
  File "legion/tools/legion_spy.py", line 142, in itervalues
    return obj.values() if sys.version_info > (3,) else obj.viewvalues()
AttributeError: 'NoneType' object has no attribute 'viewvalues'
```

**Comment by lightsighter** [comment]
When you captured this log file, was it from a run that exited cleanly or did you kill the run in the middle?

**Comment by rohany** [comment]
The run failed in the middle due to an application assertion failure.

For some context, we saw an assertion failure in the pennant application when changing the mapping used between iterations of the application. Alex suggested to capture a legion spy log when this failure occurred in case that the dependence analysis was failing in some way.

**Comment by lightsighter** [comment]
> The run failed in the middle due to an application assertion failure

The emulation mode is not designed to work (or even detect) cases where the run failed in the middle. Emulation mode assumes that the run finished successfully.

> Alex suggested to capture a legion spy log when this failure occurred in case that the dependence analysis was failing in some way.

You have to use a version of the runtime built with `-DLEGION_SPY` in `CC_FLAGS` or you won't be able to run Legion Spy's verification mode. This is why you're getting emulation mode. You should be able to use Pennant's logging facilities to detect exactly the iteration where the data diverges from the gold-standard output and then log just the few iterations leading up to it with the corresponding mapping decisions for verification by Legion Spy. In general, Legion Spy is going to be unable to verify any Pennant runs over about 100 iterations at most depending on the scale of the machine being used.

**Comment by rohany** [comment]
> You have to use a version of the runtime built with -DLEGION_SPY in CC_FLAGS or you won't be able to run Legion Spy's verification mode. 

I see. I'll try this.

> You should be able to use Pennant's logging facilities to detect exactly the iteration where the data diverges from the gold-standard output and then log just the few iterations leading up to it with the corresponding mapping decisions for verification by Legion Spy.

The failure occurs non-deterministically, not at particular iterations, but at particular invocations of the pennant application itself. I'll see what I can do though.

**Comment by lightsighter** [comment]
You're recording your mapper decisions though right? That should allow to replay them pretty easily to reproduce the issue I would think.

What exactly is the failure mode? Is the mesh turning itself inside out? By how much?

**Comment by rohany** [comment]
> You're recording your mapper decisions though right? That should allow to replay them pretty easily to reproduce the issue I would think.

It's not clear from our logs that one particular string of mapping decisions causes the failure, just that we are changing mappings between invocations of the simulation.

> What exactly is the failure mode? Is the mesh turning itself inside out? By how much?

An assertion is raised (`sv negative in calc_volumes_full`). I'm not familiar enough with the application itself to say what the interpretation of this error is.

**Comment by lightsighter** [comment]
How many iterations are you into the simulation at this point?

**Comment by elliottslaughter** [comment]
> An assertion is raised (sv negative in calc_volumes_full). I'm not familiar enough with the application itself to say what the interpretation of this error is.

This is a sanity check on the mesh to make sure that it does not violate basic laws of physics. I think this one means that the area of a mesh cell became negative, which is obviously bad.

Bottom line is that the simulation is producing the wrong answer. This is just an assert that tells you that prior to reaching the end of the run.

By the way, do you validate the result at the end of each iteration? If not, then you might want to consider enabling that. You might find that this isn't the only mapping that's going bad.

**Comment by lightsighter** [comment]
I'm not even sure it is a mapping that is going bad. When I was looking at the Legion Spy logs the simulation was being run for 100K+ iterations which is way more than most Pennant runs require to converge. After convergence we might be playing in the space of low order effects perturbing the simulation into non-physical results.

**Comment by rohany** [comment]
I'm sorry for the delay in responding.

Let me clarify the exact situation. Our application is structured like this (all within the same regent program)

```
for epoch in 0 ... N:
  pick a new mapping m
  Re-initialize pennant
  Run pennant under mapping m
```

The assertion failure that I mentioned is raised non deterministically in one of these calls to pennant. The pennant app is being run for a normal number of iterations, but it is just run repeatedly. I could not get the error to occur when I adjusted our application to only ever use the same mapping on each invocation.

We aren't currently running the validation between iterations, so I can try that.

> How many iterations are you into the simulation at this point?

As far as I can tell, there isn't a fixed iteration that we always fail at.

**Comment by lightsighter** [comment]
This is the kind of thing that delta-debugging should be able to find automatically. You should gradually be able to reduce this down to the minimum set of mapping decisions that lead to the problem so we can get something reproduceable. Without a small example that is reproduceable this is going to be nearly impossible to debug.
