### ISSUE TITLE
Compile error [CPU w/ GASNet]

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/legion#972]
Hi, I'm running into issues compiling Legion, on Lawrence Livermore's Quartz system. I've been able to compile the GPU version successfully, but I get errors when building the CPU version.

```
module --force purge
module load gcc/4.9.3
module load openmpi/2.0.0
module load python
module load paraview/5.4
export CC=gcc
export CXX=g++
export LEGION_DIR=/usr/workspace/melone1/legion
export HDF_ROOT="$LEGION_DIR"/language/hdf/install
export SCRATCH=/p/lscratchh/melone1
export USE_CUDA=0
export USE_OPENMP=1
export USE_GASNET=1
export USE_HDF=1
export MAX_DIM=3
export GASNET_VERSION="GASNet-1.32.0"


git clone -b control_replication https://gitlab.com/StanfordLegion/legion.git "$LEGION_DIR"
cd "$LEGION_DIR"/language
scripts/setup_env.py --llvm-version 60 --terra-url 'https://github.com/StanfordLegion/terra.git' --terra-branch 'luajit2.1'
```

Here's the error:

```
/usr/WS2/melone1/legion/runtime/legion/legion_allocation.h:197:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
/usr/WS2/melone1/legion/runtime/legion/legion_allocation.h: In function 'void* Legion::Internal::legion_alloc_aligned(size_t) [with T = Legion::Internal::FillView; bool BYTES = true; size_t = long unsigned int]':
/usr/WS2/melone1/legion/runtime/legion/legion_allocation.h:197:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
make: *** [/usr/WS2/melone1/legion/runtime/legion/runtime.cc.o] Error 1
/usr/WS2/melone1/legion/language/terra.build /usr/WS2/melone1/legion/language/terra
Traceback (most recent call last):
  File "/usr/WS2/melone1/legion/language/install.py", line 536, in <module>
    driver()
  File "/usr/WS2/melone1/legion/language/install.py", line 533, in driver
    install(**vars(args))
  File "/usr/WS2/melone1/legion/language/install.py", line 434, in install
    extra_flags, thread_count, verbose)
  File "/usr/WS2/melone1/legion/language/install.py", line 357, in install_bindings
    cwd=bindings_dir)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'LG_RT_DIR=/usr/WS2/melone1/legion/runtime', 'DEFINE_HEADERS_DIR=/usr/WS2/melone1/legion/bindings/regent', 'DEBUG=0', 'USE_CUDA=0', 'USE_OPENMP=1', 'USE_PYTHON=0', 'USE_LLVM=0', 'USE_GASNET=1', 'USE_HDF=1', 'USE_SPY=0', 'GASNET=/usr/WS2/melone1/legion/language/gasnet/release', 'CONDUIT=ibv', 'GCC=g++', '-j', '72']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "./scripts/setup_env.py", line 539, in <module>
    driver(**vars(args))
  File "./scripts/setup_env.py", line 491, in driver
    conduit, thread_count)
  File "./scripts/setup_env.py", line 215, in build_regent
    env=env)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/WS2/melone1/legion/language/install.py', '--with-terra', '/usr/WS2/melone1/legion/language/terra.build', '--rdir', 'auto', '-j', '72', '--no-cmake']' returned non-zero exit status 1.
```

I would appreciate any guidance. Thanks!

**Comment by lightsighter** [comment]
Can you share which branch you are on? This line number doesn't align with `master` or `stable`.

One thing I will say if you're not using the `stable` branch is that we did recently upgrade Legion's minimum c++ version to c++11 and gcc 4.9's support for c++11 wasn't fully complete and still had some bugs in it. You might try a slightly newer version of gcc (>= 5) to see if it makes things better.

**Comment by cmelone** [comment]
I am no longer getting this error, was using the `control_replication` branch.
