### ISSUE TITLE
LegionProf issue

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#989]
I got this error message with the attached prof log
```
Reading log file prof_0.gz...
parsing prof_0.gz
Matched 45761 objects
Generating interactive visualization files in directory legion_prof
Traceback (most recent call last):
  File "/home/kihiro/Softwares/legion/tools/legion_prof.py", line 4036, in <module>
    main()
  File "/home/kihiro/Softwares/legion/tools/legion_prof.py", line 4030, in main
    file_names, show_channels, show_instances, force)
  File "/home/kihiro/Softwares/legion/tools/legion_prof.py", line 3860, in emit_interactive_visualization
    mem_level = mem.emit_tsv(mem_tsv_file, 0)
  File "/home/kihiro/Softwares/legion/tools/legion_prof.py", line 846, in emit_tsv
    point.thing.level, None)
  File "/home/kihiro/Softwares/legion/tools/legion_prof.py", line 1853, in emit_tsv
    inst_name = repr(self)
  File "/home/kihiro/Softwares/legion/tools/legion_prof.py", line 1981, in __repr__
    if (pos+1)%4 == 0 and pos != dim_order:
NameError: name 'dim_order' is not defined
```
I am on commit 22954a1842f8334013743172637d32d232547786 on `control_replication`.
[prof_0.gz](https://github.com/StanfordLegion/legion/files/5751717/prof_0.gz)

**Comment by lightsighter** [comment]
You can safely comment out these two lines for now and nothing bad will happen:
https://gitlab.com/StanfordLegion/legion/-/blob/master/tools/legion_prof.py#L1981-1982
@seemamirch will need to say if that is the correct long term fix.

**Comment by seemamirch** [comment]
pushed a fix to master 
https://gitlab.com/StanfordLegion/legion/-/commit/7961c04906048570b3cd50ba2a407cf2ebc6fbf8

**Comment by bandokihiro** [comment]
fixed, thanks
