### ISSUE TITLE
Legion prof failing with additional legion spy output.

### ISSUE THREAD

**Issue by LonelyCat124** [StanfordLegion/legion#997]
Hi,
I'm having some issues trying to analyse performance/dependencies for my code. From my first glance at the profile, the limit looks to be dependencies between tasks (which would be unexpected), which probably means I've poorly defined my data usage between tasks.

I was planning to use legion spy with profile to check dependencies, but when trying to get legion prof to analyze (as https://legion.stanford.edu/profiling/ says to do) I get an error:
```
-bash-4.2$ ../../shared/legion/tools/legion_prof.py prof_0.gz spy_0.log
Reading log file prof_0.gz...
parsing prof_0.gz
Matched 78360 objects
Traceback (most recent call last):
  File "../../shared/legion/tools/legion_prof.py", line 4036, in <module>
    main()
  File "../../shared/legion/tools/legion_prof.py", line 4006, in main
    deserializer.search_for_spy_data(file_name)
  File "/lustre/scafellpike/local/HT03020/lxm18/shared/legion/tools/legion_serializer.py", line 209, in search_for_spy_data
    if legion_spy.config_pat.match(line) or \
TypeError: cannot use a string pattern on a bytes-like object
-bash-4.2$ ../../shared/legion/tools/legion_prof.py spy_0.log prof_0.gz
Traceback (most recent call last):
  File "../../shared/legion/tools/legion_prof.py", line 4036, in <module>
    main()
  File "../../shared/legion/tools/legion_prof.py", line 4006, in main
    deserializer.search_for_spy_data(file_name)
  File "/lustre/scafellpike/local/HT03020/lxm18/shared/legion/tools/legion_serializer.py", line 209, in search_for_spy_data
    if legion_spy.config_pat.match(line) or \
TypeError: cannot use a string pattern on a bytes-like object
```

I can run legion_prof on the profile fine, and legion spy on the spy trace fine, just when trying to combine the two I get this error

**Comment by LonelyCat124** [comment]
So I changed `search_for_spy_data` to this (removing `'rb'`)
```
    def search_for_spy_data(self, filename):
        with open(filename, 'r') as log:
            for line in log:
                if legion_spy.config_pat.match(line) or \
                   legion_spy.detailed_config_pat.match(line):
                   self.state.has_spy_data = True
                   break
```
which gave me a new error:

```
DLHRT0063% python3 ~/Legion/legion/tools/legion_prof.py prof_0.gz spy_0.log
Reading log file prof_0.gz...
parsing prof_0.gz
Matched 78360 objects
Generating interactive visualization files in directory legion_prof
Traceback (most recent call last):
  File "/home/aidan/Legion/legion/tools/legion_prof.py", line 4036, in <module>
    main()
  File "/home/aidan/Legion/legion/tools/legion_prof.py", line 4030, in main
    file_names, show_channels, show_instances, force)
  File "/home/aidan/Legion/legion/tools/legion_prof.py", line 3793, in emit_interactive_visualization
    op_dependencies, transitive_map = self.get_op_dependencies(file_names)
  File "/home/aidan/Legion/legion/tools/legion_prof.py", line 3491, in get_op_dependencies
    self.spy_state = legion_spy.State(None, False, True, True, True, False)
TypeError: __init__() missing 1 required positional argument: 'eq_graph_on_error'
```

**Comment by LonelyCat124** [comment]
I'll add a caveat that the above patch makes it run, but I don't know whether it is the correct output.

**Comment by elliottslaughter** [comment]
This issue is old, but for what it's worth, `legion_prof_rs` now parses Legion Spy output and is quite a bit faster than Python, and also arguably more correct in a few corner cases.
