### ISSUE TITLE
Assertion failure in legion tracing

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#999]
I encountered the following assertion failure when enabling tracing for multi-node runs. This is using the most recent control_replication branch. Running the same program on a single node works fine.

```
#6  0x00002000200a56d4 in __assert_fail_base () from /lib64/libc.so.6
#7  0x00002000200a57c4 in __assert_fail () from /lib64/libc.so.6
#8  0x00000000118f137c in Legion::Internal::TraceInfo::base_sanity_check (this=0x200050835058) at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/legion_analysis.h:471
#9  0x0000000011a28a2c in Legion::Internal::TraceInfo::record_complete_replay (this=0x200050835058, local=0x200070704cb8, ready_event=...)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/legion_analysis.h:446
#10 0x0000000011f02f4c in Legion::Internal::ReplFenceOp::trigger_mapping (this=0x200070704a30)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/legion_replication.cc:5407
#11 0x000000001213751c in Legion::Internal::Runtime::legion_runtime_task (args=0x2000541c5a50, arglen=12, userdata=0x554f0ea0, userlen=8, p=...)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/legion/runtime.cc:28578
#12 0x0000000013d9378c in Realm::LocalTaskProcessor::execute_task (this=0x55470f70, func_id=4, task_args=...)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/proc_impl.cc:1124
#13 0x0000000014c6c09c in Realm::Task::execute_on_processor (this=0x2000541c58d0, p=...) at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/tasks.cc:307
#14 0x0000000014c724a4 in Realm::UserThreadTaskScheduler::execute_task (this=0x554712c0, task=0x2000541c58d0)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/tasks.cc:1646
#15 0x0000000014c6fcac in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x554712c0) at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/tasks.cc:1127
#16 0x0000000014c7b4e0 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop> (obj=0x554712c0)
    at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/threads.inl:97
#17 0x0000000013afcf4c in Realm::UserThread::uthread_entry () at /ccs/home/zhihao/FlexFlow/legion/runtime/realm/threads.cc:1335
#18 0x00002000200c37fc in makecontext () from /lib64/libc.so.6
```

**Comment by lightsighter** [comment]
Pull and try again.

**Comment by jiazhihao** [comment]
Fixed
